import type { LanguagePackCatalog } from "../../../../platform/languagePacks/common/languagePacksService.js";
import { ASH_LOCALIZATION_CATALOG_VERSION } from "../../../../platform/languagePacks/common/languagePackContract.js";

const english: LanguagePackCatalog = {
	schemaVersion: 1,
	locale: "en",
	languageName: "English",
	localizedLanguageName: "English",
	catalogVersion: ASH_LOCALIZATION_CATALOG_VERSION,
	bundles: {
		ash: {
			"trace.address": "Trace address",
			"trace.token": "Trace token",
			"trace.connect": "Connect",
			"trace.disconnect": "Disconnect",
			"trace.clear": "Clear",
			"trace.export": "Export filtered OTLP",
			"trace.help": "Help",
			"trace.filter": "Filter by name, outcome or trace ID",
			"trace.timeline": "Trace timeline",
			"trace.details": "Span details",
			"trace.hint": "Trace viewer. Press Alt+F1 for keyboard and connection help.",
			"trace.count": "{0} shown / {1} retained · {2} dropped",
			"trace.row": "{0} · {1} · +{2} ms · {3} ms",
			"trace.empty": "No spans. Connect, then perform an action in Ash.",
			"trace.helpTitle": "Trace viewer help",
			"trace.helpText": "Enable tracing before starting App Server: set ASH_TRACE_WEBSOCKET_ADDR to 127.0.0.1:4319 and ASH_TRACE_WEBSOCKET_TOKEN to a random 64-digit hexadecimal token. Enter that address and token here. Only new completed spans are received. Connect starts a new capture; Disconnect keeps the capture. Up to 2,000 spans and 8 MiB are retained; dropped spans are counted. Tab moves between controls. Arrow keys, Home and End select spans. The timeline gives each span’s name, result, relative start and duration as text; Span details contains selectable OTLP JSON with trace and parent IDs. Filtering also limits the OTLP export. Tokens and captures are kept only in this editor. Escape closes this help dialog.",
			"trace.succeeded": "Succeeded",
			"trace.failed": "Failed",
			"trace.cancelled": "Cancelled",
			"trace.disconnected": "Disconnected",
			"trace.connecting": "Connecting…",
			"trace.connected": "Connected · listening for completed spans",
			"trace.configurationError": "Use a loopback ws:// address with no query and a 64-digit hexadecimal token.",
			"trace.connectionError": "Connection failed. Check the running App Server, address and token.",
			"trace.protocolError": "Invalid trace stream. The connection was closed.",
			"trace.verbosity": "Trace viewer accessibility help",
			"trace.verbosityDescription": "Announce the keyboard help hint when the trace viewer receives focus.",
			"trace.title": "Trace viewer",
			"trace.open": "Developer: Open trace viewer",
			"quickInput.title": "Quick Pick",
			"quickInput.results": "Quick Pick results",
			"quickInput.empty": "No matching results",
			"quickCommand.label": "Command Palette",
			"gotoSymbol.label": "Go to Symbol...",
			"gotoSymbol.dialog": "Go to Symbol",
			"gotoSymbol.placeholder": "Type a symbol name",
			"iPadShowKeyboard.label": "Show Keyboard",
			"gotoOffset": "Go to Offset...",
			"gotoOffset.dialog": "Go to Offset",
			"gotoOffset.input": "Character offset",
			"gotoOffset.placeholder": "Offset",
			"gotoLine.dialog": "Go to Line or Column",
			"gotoLine.input": "Line number and optional column",
			"gotoLine.placeholder": "Line[:Column]",
			"toggleHighContrast.label": "Toggle High Contrast Theme",
			"inspectTokens.label": "Developer: Inspect Tokens",
			"inspectTokens.title": "Token details",
			"inspectTokens.language": "Language",
			"inspectTokens.scope": "Token type",
			"inspectTokens.modifiers": "Modifiers",
			"inspectTokens.foreground": "Foreground",
			"inspectTokens.analyzing": "Analyzing…",
			"inspectTokens.comment": "Comment",
			"inspectTokens.string": "String",
			"inspectTokens.regex": "Regular expression",
			"inspectTokens.other": "Other",
			"quickCommand.placeholder": "Type the name of a command to run",
			"folding.fold.description": "Collapse the selected folding ranges.",
			"folding.unfold.description": "Expand the selected folding ranges.",
			"folding.arguments": "Folding options",
			"folding.arguments.description": "levels sets the number of levels (default: 1). direction selects up or down. selectionLines supplies zero-based lines instead of the current selections. Fold without levels or direction finds the first expanded range at each line or above it.",
		},
		"ash.menu": {
			file: "File",
			edit: "Edit",
			selection: "Selection",
			view: "View",
			go: "Go",
			run: "Run",
			terminal: "Terminal",
			help: "Help",
		},
		"ash.actions": {
			showPrimarySidebar: "Show Primary Side Bar",
			hidePrimarySidebar: "Hide Primary Side Bar",
			showSecondarySidebar: "Show Secondary Side Bar",
			hideSecondarySidebar: "Hide Secondary Side Bar",
			showPanel: "Show Panel",
			hidePanel: "Hide Panel",
			maximizePanel: "Maximize Panel",
			restoreEditorArea: "Restore Editor Area",
			closePanel: "Close Panel",
		},
		"ash.views": {
			explorer: "Explorer",
			search: "Search",
			git: "Git",
			changes: "Changes",
			agentReview: "Agent Review",
			graph: "Graph",
			chat: "Chat",
			agent: "Agent",
			agentSessions: "Agent Sessions",
			problems: "Problems",
			output: "Output",
			terminal: "Terminal",
			testing: "Testing",
			tasks: "Tasks",
			runAndDebug: "Run and Debug",
			debugConsole: "Debug Console",
			ports: "Ports",
			refactorPreview: "Refactor Preview",
		},
		"ash.regions": {
			primarySidebar: "Primary sidebar",
			primarySidebarViews: "Primary side bar views",
			agentSidebar: "Agent sidebar",
			agentSidebarViews: "Agent sidebar views",
			auxiliarySidebar: "Auxiliary sidebar",
			auxiliarySidebarViews: "Auxiliary sidebar views",
			panel: "Panel",
			panelViews: "Panel views",
			additionalViews: "Additional views",
			applicationMenu: "Application menu",
			editor: "Editor",
			editorActions: "Editor actions",
			openEditors: "Open editors",
			editorShortcuts: "Editor shortcuts",
		},
		"ash.marketplace": {
			searchMarketplace: "Search Marketplace",
			searchLanguageExtensions: "Search language extensions",
			searchPackages: "Search Plugins, Skills, MCPs…",
			browse: "Browse Marketplace",
			packageTypes: "Marketplace package types",
			filterAll: "All",
			filterPlugins: "Plugins",
			filterMcps: "MCPs",
			filterSkills: "Skills",
			filterLanguages: "Languages",
			filterLocalization: "Localization",
			filterThemes: "Themes",
			loading: "Loading Marketplace…",
			unavailable: "Marketplace unavailable.",
			noMatching: "No matching packages.",
			packageCount: "{count} package",
			packageCountPlural: "{count} packages",
			noTypeFound: "No {type} packages found",
			explore: "Explore Marketplace packages",
			tryDifferent: "Try a different search or clear the current filters.",
			installDescription: "Install Plugins, Skills, MCP servers, language support, and themes from the signed catalog.",
			clearFilters: "Clear filters",
			installed: "Installed · activation is separate",
			removalPending: "Removal pending",
			available: "Available",
			install: "Install",
			uninstall: "Uninstall",
			officialMcp: "Listed in the official MCP Registry · {name}@{version}",
			official: "Marketplace official package",
			thirdParty: "Third-party package",
			operationFailed: "Marketplace operation failed.",
		},
		"ash.settings": {
			"chrome.search": "Search settings",
			"chrome.categories": "Settings categories",
			"chrome.noResults": "No settings found.",
			"chrome.modalTitle": "Ash Settings",
			"displayLanguage.title": "Display Language",
			"displayLanguage.description": "Choose the language used by the Ash interface.",
			"displayLanguage.restart": "Some interface areas update after reopening Settings.",
			"displayLanguage.builtin": "Built-in",
			"displayLanguage.marketplace": "Marketplace",
			"displayLanguage.installMore": "Install more languages from Marketplace",
			"displayLanguage.loading": "Loading available languages…",
			"displayLanguage.unavailable": "Marketplace language packs are unavailable.",
			"displayLanguage.install": "Install",
			"displayLanguage.installed": "Installed",
			"displayLanguage.select": "Interface language",
			"categories.general.label": "General",
			"categories.general.description": "Configure core application behavior and accessibility.",
			"categories.appearance.label": "Appearance",
			"categories.appearance.description": "Customize the visual appearance of Ash.",
			"categories.editor.label": "Editor",
			"categories.editor.description": "Configure text editing, fonts, search, and diff behavior.",
			"groups.agents.label": "Agents",
			"groups.agents.description": "Create agents and teams, then configure their shared capabilities.",
			"categories.agents.label": "My Agents",
			"categories.agents.description": "Manage reusable agents and their bounded subagent delegation.",
			"categories.teams.label": "Teams",
			"categories.teams.description": "Compose reusable multi-agent teams with explicit members, roles, and coordination.",
			"categories.agent-defaults.label": "Defaults",
			"categories.agent-defaults.description": "Choose the default agent and shared execution behavior.",
			"categories.models.label": "Models",
			"categories.models.description": "Choose models and configure model-specific behavior.",
			"categories.rules.label": "Rules",
			"categories.rules.description": "Configure the instructions and rules agents follow.",
			"categories.skills.label": "Skills",
			"categories.skills.description": "Manage reusable skills that agents can activate.",
			"categories.tools-and-mcps.label": "Tools & MCPs",
			"categories.tools-and-mcps.description": "Configure tools and Model Context Protocol connections.",
			"categories.hooks.label": "Hooks",
			"categories.hooks.description": "Configure automated actions around agent workflow events.",
		},
	},
};

const chinese: LanguagePackCatalog = {
	schemaVersion: 1,
	locale: "zh-CN",
	languageName: "Chinese (Simplified)",
	localizedLanguageName: "简体中文",
	catalogVersion: ASH_LOCALIZATION_CATALOG_VERSION,
	bundles: {
		ash: {
			"trace.address": "Trace 地址",
			"trace.token": "Trace 令牌",
			"trace.connect": "连接",
			"trace.disconnect": "断开",
			"trace.clear": "清空",
			"trace.export": "导出筛选后的 OTLP",
			"trace.help": "帮助",
			"trace.filter": "按名称、结果或 Trace ID 筛选",
			"trace.timeline": "Trace 时间线",
			"trace.details": "Span 详情",
			"trace.hint": "Trace 查看器。按 Alt+F1 查看键盘操作和连接帮助。",
			"trace.count": "显示 {0} 条 / 保留 {1} 条 · 已丢弃 {2} 条",
			"trace.row": "{0} · {1} · +{2} 毫秒 · {3} 毫秒",
			"trace.empty": "暂无 span。连接后，在 Ash 中执行操作。",
			"trace.helpTitle": "Trace 查看器帮助",
			"trace.helpText": "启动 App Server 前开启采集：将 ASH_TRACE_WEBSOCKET_ADDR 设为 127.0.0.1:4319，将 ASH_TRACE_WEBSOCKET_TOKEN 设为随机的 64 位十六进制令牌。在此输入相同的地址和令牌。只接收连接后完成的 span。连接会开始新的采集；断开会保留已采集数据。最多保留 2,000 条 span 和 8 MiB，丢弃数量会显示。按 Tab 切换控件，用方向键、Home 和 End 选择 span。时间线以文字显示名称、结果、相对开始时间和耗时；Span 详情提供可选择复制的 OTLP JSON，包含 trace 和父 span ID。筛选也会限制导出的 OTLP 数据。令牌和采集数据只保存在当前编辑器中。按 Escape 关闭帮助。",
			"trace.succeeded": "成功",
			"trace.failed": "失败",
			"trace.cancelled": "已取消",
			"trace.disconnected": "已断开",
			"trace.connecting": "正在连接…",
			"trace.connected": "已连接 · 正在接收已完成的 span",
			"trace.configurationError": "请使用不带查询参数的本机回环 ws:// 地址，以及 64 位十六进制令牌。",
			"trace.connectionError": "连接失败。请检查 App Server 是否运行、地址和令牌是否正确。",
			"trace.protocolError": "Trace 数据格式无效，连接已关闭。",
			"trace.verbosity": "Trace 查看器无障碍帮助",
			"trace.verbosityDescription": "Trace 查看器获得焦点时朗读键盘帮助提示。",
			"trace.title": "Trace 查看器",
			"trace.open": "开发者：打开 Trace 查看器",
			"quickInput.title": "快速选择",
			"quickInput.results": "快速选择结果",
			"quickInput.empty": "没有匹配结果",
			"quickCommand.label": "命令面板",
			"gotoSymbol.label": "转到符号...",
			"gotoSymbol.dialog": "转到符号",
			"gotoSymbol.placeholder": "输入符号名称",
			"iPadShowKeyboard.label": "显示键盘",
			"gotoOffset": "转到字符偏移量...",
			"gotoOffset.dialog": "转到字符偏移量",
			"gotoOffset.input": "字符偏移量",
			"gotoOffset.placeholder": "偏移量",
			"gotoLine.dialog": "转到行或列",
			"gotoLine.input": "行号及可选列号",
			"gotoLine.placeholder": "行[:列]",
			"toggleHighContrast.label": "切换高对比度主题",
			"inspectTokens.label": "开发者：检查词法单元",
			"inspectTokens.title": "词法单元详情",
			"inspectTokens.language": "语言",
			"inspectTokens.scope": "词法单元类型",
			"inspectTokens.modifiers": "修饰符",
			"inspectTokens.foreground": "前景色",
			"inspectTokens.analyzing": "正在分析…",
			"inspectTokens.comment": "注释",
			"inspectTokens.string": "字符串",
			"inspectTokens.regex": "正则表达式",
			"inspectTokens.other": "其他",
			"quickCommand.placeholder": "输入要运行的命令名称",
			"folding.fold.description": "折叠选定的范围。",
			"folding.unfold.description": "展开选定的折叠范围。",
			"folding.arguments": "折叠选项",
			"folding.arguments.description": "levels 指定处理层数，默认为 1。direction 选择向上（up）或向下（down）。selectionLines 使用从 0 开始的行号替代当前选区。折叠时若不指定 levels 和 direction，则处理各行所在范围或其上层首个尚未折叠的范围。",
		},
		"ash.menu": {
			file: "文件",
			edit: "编辑",
			selection: "选择",
			view: "查看",
			go: "转到",
			run: "运行",
			terminal: "终端",
			help: "帮助",
		},
		"ash.actions": {
			showPrimarySidebar: "显示主侧栏",
			hidePrimarySidebar: "隐藏主侧栏",
			showSecondarySidebar: "显示辅助侧栏",
			hideSecondarySidebar: "隐藏辅助侧栏",
			showPanel: "显示面板",
			hidePanel: "隐藏面板",
			maximizePanel: "最大化面板",
			restoreEditorArea: "恢复编辑器区域",
			closePanel: "关闭面板",
		},
		"ash.views": {
			explorer: "资源管理器",
			search: "搜索",
			git: "Git",
			changes: "更改",
			agentReview: "Agent 审查",
			graph: "图表",
			chat: "聊天",
			agent: "Agent",
			agentSessions: "Agent 会话",
			problems: "问题",
			output: "输出",
			terminal: "终端",
			testing: "测试",
			tasks: "任务",
			runAndDebug: "运行和调试",
			debugConsole: "调试控制台",
			ports: "端口",
			refactorPreview: "重构预览",
		},
		"ash.regions": {
			primarySidebar: "主侧栏",
			primarySidebarViews: "主侧栏视图",
			agentSidebar: "Agent 侧栏",
			agentSidebarViews: "Agent 侧栏视图",
			auxiliarySidebar: "辅助侧栏",
			auxiliarySidebarViews: "辅助侧栏视图",
			panel: "面板",
			panelViews: "面板视图",
			additionalViews: "其他视图",
			applicationMenu: "应用程序菜单",
			editor: "编辑器",
			editorActions: "编辑器操作",
			openEditors: "打开的编辑器",
			editorShortcuts: "编辑器快捷方式",
		},
		"ash.marketplace": {
			searchMarketplace: "搜索 Marketplace",
			searchLanguageExtensions: "搜索语言扩展",
			searchPackages: "搜索插件、技能、MCP…",
			browse: "浏览 Marketplace",
			packageTypes: "Marketplace 软件包类型",
			filterAll: "全部",
			filterPlugins: "插件",
			filterMcps: "MCP",
			filterSkills: "技能",
			filterLanguages: "语言",
			filterLocalization: "界面语言",
			filterThemes: "主题",
			loading: "正在加载 Marketplace…",
			unavailable: "Marketplace 暂不可用。",
			noMatching: "没有匹配的软件包。",
			packageCount: "{count} 个软件包",
			packageCountPlural: "{count} 个软件包",
			noTypeFound: "未找到 {type} 软件包",
			explore: "探索 Marketplace 软件包",
			tryDifferent: "请尝试其他搜索词，或清除当前筛选条件。",
			installDescription: "从已签名目录安装插件、技能、MCP 服务、语言支持和主题。",
			clearFilters: "清除筛选条件",
			installed: "已安装 · 需单独激活",
			removalPending: "等待移除",
			available: "可安装",
			install: "安装",
			uninstall: "卸载",
			officialMcp: "已列入官方 MCP Registry · {name}@{version}",
			official: "Marketplace 官方软件包",
			thirdParty: "第三方软件包",
			operationFailed: "Marketplace 操作失败。",
		},
		"ash.settings": {
			"chrome.search": "搜索设置",
			"chrome.categories": "设置类别",
			"chrome.noResults": "未找到设置。",
			"chrome.modalTitle": "Ash 设置",
			"displayLanguage.title": "显示语言",
			"displayLanguage.description": "选择 Ash 界面使用的语言。",
			"displayLanguage.restart": "部分界面将在重新打开设置后更新。",
			"displayLanguage.builtin": "内置",
			"displayLanguage.marketplace": "Marketplace",
			"displayLanguage.installMore": "从 Marketplace 安装更多语言",
			"displayLanguage.loading": "正在加载可用语言…",
			"displayLanguage.unavailable": "Marketplace 语言包暂时不可用。",
			"displayLanguage.install": "安装",
			"displayLanguage.installed": "已安装",
			"displayLanguage.select": "界面语言",
			"categories.general.label": "常规",
			"categories.general.description": "配置应用核心行为和辅助功能。",
			"categories.appearance.label": "外观",
			"categories.appearance.description": "自定义 Ash 的视觉外观。",
			"categories.editor.label": "编辑器",
			"categories.editor.description": "配置文本编辑、字体、搜索和差异显示。",
			"groups.agents.label": "Agent",
			"groups.agents.description": "创建 Agent 与团队，并配置它们共享的能力。",
			"categories.agents.label": "我的 Agent",
			"categories.agents.description": "管理可复用 Agent 及其受限的子 Agent 委托。",
			"categories.teams.label": "团队",
			"categories.teams.description": "通过明确的成员、角色与协调方式组合可复用的多 Agent 团队。",
			"categories.agent-defaults.label": "默认设置",
			"categories.agent-defaults.description": "选择默认 Agent 和共享执行行为。",
			"categories.models.label": "模型",
			"categories.models.description": "选择模型并配置模型特定行为。",
			"categories.rules.label": "规则",
			"categories.rules.description": "配置 Agent 遵循的指令和规则。",
			"categories.skills.label": "技能",
			"categories.skills.description": "管理 Agent 可激活的可复用技能。",
			"categories.tools-and-mcps.label": "工具与 MCP",
			"categories.tools-and-mcps.description": "配置工具和 Model Context Protocol 连接。",
			"categories.hooks.label": "Hooks",
			"categories.hooks.description": "配置 Agent 工作流事件前后的自动化操作。",
		},
	},
};

export const builtinLanguagePackCatalogs: readonly LanguagePackCatalog[] = [english, chinese];
