import { expect, test } from '../../../automation/test.js';
import { Editor } from '../../../automation/editor.js';

test('Cowork and Code retain separate editors while transferring the selected draft and attachments', async ({ application, target, workbench }) => {
	let page = await workbench.openAgentsWindow(target.kind);
	const navigation = page.locator('.ash-sessions-activity-content');
	const conversation = page.locator('[data-part="sessions"]');
	await expect(conversation.locator('.ash-cowork')).toBeVisible();
	await expect(conversation.locator('.ash-chat')).toHaveCount(0);
	const editor = new Editor(conversation);
	await editor.waitForEditorFocus();
	await page.keyboard.insertText('Prepare a presentation');
	const coworkInput = await editor.input.elementHandle();
	const composer = conversation.locator('.ash-sessions-cowork-input');
	await composer.locator('input[type="file"]').setInputFiles({ name: 'brief.txt', mimeType: 'text/plain', buffer: Buffer.from('Presentation brief') });
	await expect(composer.getByRole('button', { name: 'Remove brief.txt', exact: true })).toBeVisible();
	const identity = await conversation.locator('.ash-cowork').getAttribute('data-untitled-session-id');
	await navigation.getByRole('button', { name: 'Code', exact: true }).click();
	await expect(conversation.locator('.ash-chat')).toBeVisible();
	await expect(conversation.locator('.ash-cowork')).toHaveCount(0);
	await editor.waitForEditorContents(text => text === 'Prepare a presentation');
	await expect(conversation.locator('.ash-chat')).toHaveAttribute('data-untitled-session-id', identity!);
	expect(await editor.input.evaluate((input, previous) => input === previous, coworkInput)).toBe(false);
	await editor.input.focus();
	await page.keyboard.press('ControlOrMeta+A');
	await page.keyboard.insertText('Updated presentation brief');
	await navigation.getByRole('button', { name: 'Chat', exact: true }).click();
	await expect(conversation.locator('.ash-cowork')).toBeVisible();
	await editor.waitForEditorContents(text => text === 'Updated presentation brief');
	await expect(composer.getByRole('button', { name: 'Remove brief.txt', exact: true })).toBeVisible();
	expect(await editor.input.evaluate((input, previous) => input === previous, coworkInput)).toBe(true);
	await navigation.getByRole('button', { name: 'Collaboration', exact: true }).click();
	await expect(conversation.locator('.ash-cowork')).toBeVisible();
	await expect(page.locator('.ash-teams-panel')).toBeVisible();
	await navigation.getByRole('button', { name: 'Chat', exact: true }).click();
	await editor.input.focus();
	await page.keyboard.press('Alt+F1');
	await expect(page.locator('.ash-accessible-view-content')).toHaveValue(/attach files|attachments/i);
	await page.keyboard.press('Escape');
	await editor.waitForEditorFocus();
	await coworkInput?.dispose();
	page = await workbench.reopenAgentsWindow(application, page);
	await expect(page.locator('[data-part="sessions"] .ash-cowork')).toBeVisible();
	await new Editor(page.locator('[data-part="sessions"]')).waitForEditorContents(text => text === 'Updated presentation brief');
	await expect(page.locator('.ash-sessions-cowork-input').getByRole('button', { name: 'Remove brief.txt', exact: true })).toBeVisible();
});
