#!/bin/sh
while read -r local_ref local_oid remote_ref remote_oid
do
    case "$local_oid" in
        0000000000000000000000000000000000000000) continue ;;
    esac
    pnpm exec node build/importCase.ts --check --revision "$local_oid" || exit $?
done
