import { RawContextKey } from '../../../../platform/contextkey/common/contextkey.js';

export const CONTEXT_DISASSEMBLY_VIEW_FOCUS = new RawContextKey<boolean>('disassemblyViewFocus', false);
export const CONTEXT_DEBUG_STATE = new RawContextKey<string>('debugState', 'inactive');
export const DEBUG_VIEW_ID = "workbench.view.debug";
export const DISASSEMBLY_VIEW_ID = 'workbench.debug.disassemblyView';
export const OPEN_DISASSEMBLY_VIEW_COMMAND_ID = 'debug.action.openDisassemblyView';
export const DEBUG_CONSOLE_VIEW_ID = "workbench.panel.debugConsole";
export const FOCUS_DEBUG_CONSOLE_COMMAND_ID = "workbench.debug.action.focusRepl";
export const CLEAR_DEBUG_CONSOLE_COMMAND_ID = "workbench.debug.panel.action.clearReplAction";
export const START_DEBUG_COMMAND_ID = "workbench.action.debug.start";
export const STOP_DEBUG_COMMAND_ID = "workbench.action.debug.stop";
export const STOP_ALL_DEBUG_COMMAND_ID = "workbench.action.debug.stopAll";
export const RESTART_DEBUG_COMMAND_ID = "workbench.action.debug.restart";
export const CONTINUE_DEBUG_COMMAND_ID = "workbench.action.debug.continue";
export const PAUSE_DEBUG_COMMAND_ID = "workbench.action.debug.pause";
export const STEP_OVER_DEBUG_COMMAND_ID = "workbench.action.debug.stepOver";
export const STEP_INTO_DEBUG_COMMAND_ID = "workbench.action.debug.stepInto";
export const STEP_OUT_DEBUG_COMMAND_ID = "workbench.action.debug.stepOut";
export const BREAKPOINT_EDITOR_CONTRIBUTION_ID = 'editor.contrib.breakpoint';
