import { expect, test } from '../../../automation/test.js';
import { Menus } from '../../../automation/menus.js';
import { Editor } from '../../../automation/editor.js';
import { QuickAccess } from '../../../automation/quickaccess.js';

test('Sessions restores the Library repository and its registered containers through entry startup', async ({ application, target, workbench }) => {
	let page = await workbench.openAgentsWindow(target.kind);
	const draft = new Editor(page.locator('.ash-sessions-chat-slot.active:visible'));
	await draft.waitForEditorFocus();
	await page.keyboard.insertText('Keep the conversation when Library is restored');
	await page.locator('.ash-sessions-activity-content').getByRole('button', { name: 'Library', exact: true }).click();
	await expect(page.locator('[data-part="editor"] .ash-library')).toBeVisible();
	await page.locator('[data-part="titlebar"]').getByRole('button', { name: 'Hide sidebar', exact: true }).click();
	await expect(page.locator('[data-part="sidebar"]')).toBeHidden();
	page = await workbench.reopenAgentsWindow(application, page);
	const navigation = page.locator('.ash-sessions-activity-content');
	await expect(navigation.getByRole('button', { name: 'Library', exact: true })).toHaveAttribute('aria-current', 'page');
	await expect(page.locator('[data-part="editor"] .ash-library')).toBeVisible();
	await expect(page.locator('[data-part="sidebar"]')).toBeHidden();
	await expect(page.locator('[data-part="auxiliarybar"] [data-view-id="sessions.library.details.view"]')).toBeVisible();
	await page.locator('[data-part="titlebar"]').getByRole('button', { name: 'Show sidebar', exact: true }).click();
	await expect(page.locator('[data-part="sidebar"] [data-view-id="sessions.library.navigation.view"]')).toBeVisible();
	await navigation.getByRole('button', { name: 'Chat', exact: true }).click();
	await new Editor(page.locator('.ash-sessions-chat-slot.active:visible')).waitForEditorContents(text => text === 'Keep the conversation when Library is restored');
});

test('Creator contributions share one entry container while Library categories keep the repository entry', async ({ target, workbench }) => {
	const page = await workbench.openAgentsWindow(target.kind);
	const navigation = page.locator('.ash-sessions-activity-content');
	await navigation.getByRole('button', { name: 'Creator', exact: true }).click();
	const entries = page.locator('[data-part="sidebar"] [data-view-container-id="sessions.creator.navigation"]');
	await expect(entries.locator('[data-view-id]')).toHaveCount(8);
	const make = entries.locator('[data-view-id="sessions.creator.navigation.make"]');
	const header = make.locator('.ash-pane-view-header-button');
	await header.click();
	await expect(header).toHaveAttribute('aria-expanded', 'false');
	await expect(make.locator('.ash-creator-navigation')).toBeHidden();
	await header.press('ArrowRight');
	await expect(header).toHaveAttribute('aria-expanded', 'true');
	const makeButton = make.locator('.ash-creator-navigation').getByRole('button', { name: 'Make', exact: true });
	await makeButton.focus();
	await page.keyboard.press('Alt+F1');
	await expect(page.locator('.ash-accessible-view-content')).toHaveValue(/View generated code, run a preview and continue with an Agent/);
	await page.keyboard.press('Escape');
	await expect(makeButton).toBeFocused();
	await page.keyboard.press('Enter');
	await expect(page.locator('.ash-creator')).toBeVisible();
	await expect(page.locator('.ash-creator-home')).toBeHidden();
	await expect(entries).toBeVisible();
	await entries.getByRole('button', { name: 'Creator home', exact: true }).click();
	await expect(page.locator('.ash-creator-home')).toBeVisible();
	await entries.locator('[data-view-id="sessions.creator.navigation.design"] .ash-creator-navigation').getByRole('button', { name: 'Design', exact: true }).click();
	await expect(page.getByRole('region', { name: 'Design canvas' })).toBeVisible();
	await expect(page.locator('[data-part="sidebar"] [data-view-container-id="workbench.sessions.sidebar.designLayers"]')).toBeVisible();
	await navigation.getByRole('button', { name: 'Library', exact: true }).click();
	const libraryInput = await page.locator('[data-part="editor"] .ash-library').elementHandle();
	const libraryNavigation = page.locator('[data-view-id="sessions.library.navigation.view"]');
	await libraryNavigation.getByRole('button', { name: 'Favorites', exact: true }).click();
	await libraryNavigation.getByRole('button', { name: 'All', exact: true }).click();
	await expect(navigation.getByRole('button', { name: 'Library', exact: true })).toHaveAttribute('aria-current', 'page');
	await expect(page.locator('[data-part="sidebar"] [data-view-id]:visible')).toHaveCount(1);
	await expect(page.locator('[data-part="auxiliarybar"] [data-view-id]:visible')).toHaveCount(1);
	expect(await page.locator('[data-part="editor"] .ash-library').evaluate((element, retained) => element === retained, libraryInput)).toBe(true);
});

test('Sessions pages keep Code tabs separate and retain dirty files and Design state', async ({ target, workbench }) => {
	const page = await workbench.openAgentsWindow(target.kind);
	const navigation = page.locator('.ash-sessions-activity-content');
	const code = navigation.getByRole('button', { name: 'Code', exact: true });
	const creator = navigation.getByRole('button', { name: 'Creator', exact: true });
	const library = navigation.getByRole('button', { name: 'Library', exact: true });
	await code.click();
	await new QuickAccess(page).runCommand('workbench.action.files.newUntitledFile');
	const codeEditor = page.locator('[data-part="editor"]');
	const codeTabs = codeEditor.locator('.ash-editor-group:not(.ash-editor-group-locked) .ash-editor-title-control').getByRole('tab', { includeHidden: true });
	const file = new Editor(codeEditor);
	await file.waitForEditorFocus();
	await page.keyboard.insertText('Keep this unsaved Code file');
	const tabs = await codeTabs.allTextContents();
	await creator.click();
	await page.locator('.ash-creator').getByRole('button', { name: 'Design', exact: true }).click();
	await expect(creator).toHaveAttribute('aria-current', 'page');
	await expect(codeEditor).toBeVisible();
	await expect(file.input).toBeHidden();
	const canvas = page.getByRole('region', { name: 'Design canvas' });
	await expect(canvas).toBeVisible();
	await canvas.focus();
	await page.keyboard.press('r');
	await page.keyboard.press('+');
	const world = canvas.locator('.ash-canvas-world');
	const transform = await world.evaluate(element => (element as HTMLElement).style.transform);
	await expect(canvas.locator('[data-shape-id]')).toHaveCount(1);
	await expect(page.getByRole('tab', { name: 'Untitled design', exact: true, includeHidden: true })).toHaveCount(0);
	await expect(codeTabs).toHaveText(tabs);
	await library.click();
	await expect(library).toHaveAttribute('aria-current', 'page');
	const search = page.locator('.ash-library').getByRole('searchbox');
	await search.fill('Keep this Library search');
	await expect(canvas).toBeHidden();
	await expect(page.getByRole('tab', { name: 'Library', exact: true })).toBeVisible();
	await code.click();
	await expect(codeEditor).toBeVisible();
	await file.waitForEditorContents(text => text === 'Keep this unsaved Code file');
	await expect(codeTabs).toHaveText(tabs);
	await creator.focus();
	await page.keyboard.press('Enter');
	await page.locator('.ash-creator').getByRole('button', { name: 'Design', exact: true }).click();
	await expect(canvas).toBeVisible();
	await expect.poll(() => world.evaluate(element => (element as HTMLElement).style.transform)).toBe(transform);
	await expect(canvas.locator('[data-shape-id]')).toHaveCount(1);
	await expect(page.locator('[data-part="auxiliarybar"]').getByRole('spinbutton', { name: 'X', exact: true })).toBeVisible();
	await expect(page.getByRole('dialog')).toHaveCount(0);
	await library.click();
	await expect(search).toHaveValue('Keep this Library search');
});

test('Sessions registered pages coordinate Parts and retain drafts through drag and keyboard ordering', async ({ application, target, workbench }) => {
	let page = await workbench.openAgentsWindow(target.kind);
	const navigation = page.locator('.ash-sessions-activity-content');
	const items = navigation.locator('.ash-sessions-activity-top .ash-action-view-item');
	const chat = navigation.getByRole('button', { name: 'Chat', exact: true });
	const creator = navigation.getByRole('button', { name: 'Creator', exact: true });
	const editor = new Editor(page.locator('.ash-sessions-chat-slot.active:visible'));
	await editor.waitForEditorFocus();
	await page.keyboard.insertText('Retain the navigation draft');
	await editor.waitForEditorContents(text => text === 'Retain the navigation draft');
	const retainedChat = await chat.elementHandle();
	await navigation.locator('[data-action-id="sessions.open.creator"]').dragTo(navigation.locator('[data-action-id="sessions.open.chat"]'), { targetPosition: { x: 8, y: 2 } });
	await expect(items.first()).toHaveAttribute('draggable', 'true');
	await expect.poll(() => items.evaluateAll(elements => elements.map(element => (element as HTMLElement).dataset.actionId))).toEqual(['sessions.open.creator', 'sessions.open.chat', 'sessions.open.teams', 'sessions.open.library', 'sessions.open.code']);
	await expect(chat).toHaveAttribute('aria-current', 'page');
	expect(await chat.evaluate((element, retained) => element === retained, retainedChat)).toBe(true);
	await navigation.getByRole('button', { name: 'Code', exact: true }).click();
	await new QuickAccess(page).runCommand('workbench.action.files.newUntitledFile');
	await expect(page.locator('[data-part="editor"]').getByRole('tab', { name: 'Untitled-1', exact: true })).toBeVisible();
	await creator.click();
	await page.locator('.ash-creator').getByRole('button', { name: 'Design', exact: true }).click();
	await expect(creator).toHaveAttribute('aria-current', 'page');
	await expect(page.locator('[data-part="sessions"]')).toBeHidden();
	await expect(page.locator('[data-part="editor"]')).toBeVisible();
	await expect(page.locator('[data-part="editor"] .ash-creator')).toBeVisible();
	await expect(page.getByRole('tab', { name: 'Untitled design', exact: true })).toHaveCount(0);
	await expect(page.locator('[data-part="sidebar"]')).toBeVisible();
	await expect(page.locator('[data-part="auxiliarybar"]')).toBeVisible();
	await expect(page.locator('[data-part="panel"]')).toBeHidden();
	await navigation.getByRole('button', { name: 'Library', exact: true }).click();
	await expect(page.locator('[data-part="editor"] .ash-library')).toBeVisible();
	await expect(page.locator('[data-part="sidebar"]')).toBeVisible();
	await expect(page.locator('[data-part="editor"]')).toBeVisible();
	await expect(page.locator('[data-part="auxiliarybar"]')).toBeVisible();
	await chat.click();
	await editor.waitForEditorContents(text => text === 'Retain the navigation draft');
	await creator.focus();
	await new Menus(page).select(application, () => page.keyboard.press('Shift+F10'), ['Move later']);
	await expect(creator).toBeFocused();
	await expect.poll(() => items.evaluateAll(elements => elements.map(element => (element as HTMLElement).dataset.actionId))).toEqual(['sessions.open.chat', 'sessions.open.creator', 'sessions.open.teams', 'sessions.open.library', 'sessions.open.code']);
	await expect(chat).toHaveAttribute('aria-current', 'page');
	await page.keyboard.press('Home');
	await expect(chat).toBeFocused();
	await page.keyboard.press('End');
	await expect(navigation.getByRole('button', { name: 'Code', exact: true })).toBeFocused();
	await page.keyboard.press('Enter');
	await expect(navigation.getByRole('button', { name: 'Code', exact: true })).toHaveAttribute('aria-current', 'page');
	await expect(page.locator('[data-part="sessions"]')).toBeVisible();
	await expect(page.locator('[data-part="editor"]').getByRole('tab', { name: 'Untitled-1', exact: true })).toHaveAttribute('aria-selected', 'true');
	await expect(page.locator('[data-part="auxiliarybar"]')).toBeVisible();
	await chat.click();
	await editor.waitForEditorContents(text => text === 'Retain the navigation draft');
	await new Menus(page).select(application, () => chat.click({ button: 'right' }), ['Activity Bar Position', 'Top']);
	await expect(page.locator('.ash-sessions-activity-host.top')).toBeVisible();
	await expect(navigation.locator('[role="toolbar"]')).toHaveAttribute('aria-orientation', 'horizontal');
	await navigation.locator('[data-action-id="sessions.open.code"]').dragTo(navigation.locator('[data-action-id="sessions.open.teams"]'), { targetPosition: { x: 2, y: 8 } });
	await expect.poll(() => items.evaluateAll(elements => elements.map(element => (element as HTMLElement).dataset.actionId))).toEqual(['sessions.open.chat', 'sessions.open.creator', 'sessions.open.code', 'sessions.open.teams', 'sessions.open.library']);
	await expect(chat).toHaveAttribute('aria-current', 'page');
	await chat.focus();
	await page.keyboard.press('ArrowRight');
	await expect(creator).toBeFocused();
	await page.reload();
	await expect(page.locator('.ash-sessions-activity-host.top')).toBeVisible();
	await expect(chat).toHaveAttribute('aria-current', 'page');
	await expect.poll(() => items.evaluateAll(elements => elements.map(element => (element as HTMLElement).dataset.actionId))).toEqual(['sessions.open.chat', 'sessions.open.creator', 'sessions.open.code', 'sessions.open.teams', 'sessions.open.library']);
	await editor.waitForEditorContents(text => text === 'Retain the navigation draft');
	await retainedChat!.dispose();
});

for (const theme of ['Ash High Contrast Dark', 'Ash High Contrast Light']) {
	test(`Sessions registered navigation retains selection and exposes hover and keyboard focus in ${theme}`, async ({ application, target, workbench }) => {
		await workbench.quickaccess.runCommand('workbench.action.selectTheme');
		const search = workbench.page.locator('.ash-quick-pick').getByRole('combobox');
		await search.fill(theme);
		await search.press('Enter');
		await expect(workbench.page.locator('.ash-quick-pick')).toHaveCount(0);
		let page = workbench.page;
		if (target.kind === 'browser') {
			await page.locator('[data-action-id="ash.code.open-sessions"] button').click();
		} else {
			if (!('windows' in application)) { throw new Error('Expected Electron windows'); }
			const opened = application.waitForEvent('window');
			await page.locator('[data-action-id="workbench.action.chat.openAgentsWindow.titleBar"] button').click();
			page = await opened;
		}
		await expect(page.locator('#app')).toHaveAttribute('data-color-scheme', theme.endsWith('Dark') ? 'high-contrast-dark' : 'high-contrast-light');
		const navigation = page.locator('.ash-sessions-activity-content');
		const chat = navigation.getByRole('button', { name: 'Chat', exact: true });
		const library = navigation.getByRole('button', { name: 'Library', exact: true });
		await page.mouse.move(400, 180);
		const selectedBackground = await chat.evaluate(button => getComputedStyle(button).backgroundColor);
		await expect(chat).toHaveCSS('outline-style', 'solid');
		await chat.hover();
		await expect(chat).toHaveCSS('background-color', selectedBackground);
		await library.hover();
		await expect(library).not.toHaveAttribute('aria-current');
		await expect(library).not.toHaveCSS('background-color', 'rgba(0, 0, 0, 0)');
		await expect(library).toHaveCSS('outline-style', 'solid');
		await chat.focus();
		await page.keyboard.press('ArrowDown');
		const collaboration = navigation.getByRole('button', { name: 'Collaboration', exact: true });
		await expect(collaboration).toBeFocused();
		await expect(collaboration).toHaveCSS('outline-style', 'solid');
		expect(await collaboration.evaluate(button => parseFloat(getComputedStyle(button).outlineWidth))).toBeGreaterThan(0);
		await expect(chat).toHaveAttribute('aria-current', 'page');
		await page.keyboard.press('End');
		const creator = navigation.getByRole('button', { name: 'Creator', exact: true });
		await expect(creator).toBeFocused();
		await page.keyboard.press('Enter');
		await expect(creator).toHaveAttribute('aria-current', 'page');
		await expect(chat).not.toHaveAttribute('aria-current');
		await expect(page.locator('[data-part="editor"]')).toBeVisible();
		await expect(page.locator('[data-part="editor"] .ash-creator')).toBeVisible();
	});
}
