[package]
name = "ash-tcp-tunnel"
version.workspace = true
edition.workspace = true
license = "Apache-2.0"
publish.workspace = true

[lib]
name = "tcp_tunnel"
doctest = false

[dependencies]
async-utils = { package = "ash-async-utils", path = "../async-utils" }
bytes = { workspace = true }
h3 = { workspace = true }
h3-quinn = { workspace = true }
http = { workspace = true }
quinn = { workspace = true, features = ["runtime-tokio", "rustls-ring"] }
rustls = { workspace = true }
thiserror = { workspace = true }
tokio = { workspace = true, features = ["io-util", "macros", "sync"] }
url = { workspace = true }

[dev-dependencies]
pretty_assertions = { workspace = true }
rcgen = { workspace = true, features = ["ring"] }

[lints]
workspace = true
