packages:
  - build
  - app-ts
  - test/scenario
engineStrict: true
allowBuilds:
  electron: true
  esbuild: true
  native-keymap: true
  native-is-elevated: false
  sharp: true
  unrs-resolver: true
  workerd: true
