// Generated by `ash-app-server-protocol generate_protocol`. Do not edit.
export const APPROVAL_MODE_DEFINITIONS = [
  {
    "id": "auto",
    "label": {
      "key": "permissions.auto.label",
      "english": "Auto",
      "chinese": "自动",
      "japanese": "自動",
      "french": "Auto"
    },
    "description": {
      "key": "permissions.auto.description",
      "english": "Review operations automatically; ask you when uncertain",
      "chinese": "自动审核操作，无法判断时询问你",
      "japanese": "操作を自動審査し、判断できない場合は確認します",
      "french": "Examiner automatiquement les opérations ; vous demander en cas d’incertitude"
    },
    "requiresConfirmation": false
  },
  {
    "id": "manual",
    "label": {
      "key": "permissions.manual.label",
      "english": "Manual",
      "chinese": "手动",
      "japanese": "手動",
      "french": "Manuel"
    },
    "description": {
      "key": "permissions.manual.description",
      "english": "Ask you when an operation needs approval",
      "chinese": "操作需要授权时由你确认",
      "japanese": "操作に承認が必要な場合は確認します",
      "french": "Vous demander lorsqu’une opération nécessite une autorisation"
    },
    "requiresConfirmation": false
  },
  {
    "id": "bypassPermissions",
    "label": {
      "key": "permissions.bypassPermissions.label",
      "english": "Bypass permissions",
      "chinese": "跳过权限审批",
      "japanese": "承認をスキップ",
      "french": "Ignorer les autorisations"
    },
    "description": {
      "key": "permissions.bypassPermissions.description",
      "english": "Skip most approvals; access limits still apply",
      "chinese": "跳过大部分审批，访问范围限制仍然有效",
      "japanese": "ほとんどの承認を省略します。アクセス制限は引き続き適用されます",
      "french": "Ignorer la plupart des autorisations ; les limites d’accès restent en vigueur"
    },
    "requiresConfirmation": true
  }
] as const;
