// Generated by `ash-app-server-protocol generate_protocol`. Do not edit.
import type { BrowserCloseParams } from './types/BrowserCloseParams.js';
import type { BrowserCreateParams } from './types/BrowserCreateParams.js';
import type { BrowserCreateResult } from './types/BrowserCreateResult.js';
import type { BrowserObserveParams } from './types/BrowserObserveParams.js';
import type { BrowserObserveResult } from './types/BrowserObserveResult.js';
import type { BrowserPerformParams } from './types/BrowserPerformParams.js';
import type { BrowserPerformResult } from './types/BrowserPerformResult.js';
import type { BrowserSharingSetParams } from './types/BrowserSharingSetParams.js';
import type { ExtensionClientRequestParams } from './types/ExtensionClientRequestParams.js';
import type { ExtensionClientResult } from './types/ExtensionClientResult.js';
import type { TextDocumentApplyParams } from './types/TextDocumentApplyParams.js';
import type { TextDocumentApplyResult } from './types/TextDocumentApplyResult.js';
import type { TextDocumentListParams } from './types/TextDocumentListParams.js';
import type { TextDocumentListResult } from './types/TextDocumentListResult.js';
import type { TextDocumentReadParams } from './types/TextDocumentReadParams.js';
import type { TextDocumentReadResult } from './types/TextDocumentReadResult.js';
import type { TextDocumentReleaseParams } from './types/TextDocumentReleaseParams.js';
import type { JsonRpcError, JsonRpcRequest, JsonRpcResponse } from './protocol.js';

export interface AppServerServerRequestMap {
  "extensionClient/request": { params: ExtensionClientRequestParams; response: ExtensionClientResult };
  "textDocument/list": { params: TextDocumentListParams; response: TextDocumentListResult };
  "textDocument/read": { params: TextDocumentReadParams; response: TextDocumentReadResult };
  "textDocument/apply": { params: TextDocumentApplyParams; response: TextDocumentApplyResult };
  "textDocument/release": { params: TextDocumentReleaseParams; response: null };
  "browser/create": { params: BrowserCreateParams; response: BrowserCreateResult };
  "browser/sharing/set": { params: BrowserSharingSetParams; response: null };
  "browser/observe": { params: BrowserObserveParams; response: BrowserObserveResult };
  "browser/perform": { params: BrowserPerformParams; response: BrowserPerformResult };
  "browser/close": { params: BrowserCloseParams; response: null };
}
export type AppServerServerRequestMethod = keyof AppServerServerRequestMap;
export type ServerRequestParams<M extends AppServerServerRequestMethod> = AppServerServerRequestMap[M]["params"];
export type ServerRequestResult<M extends AppServerServerRequestMethod> = AppServerServerRequestMap[M]["response"];
export type AppServerServerRequest<M extends AppServerServerRequestMethod> = JsonRpcRequest<ServerRequestParams<M>> & { method: M };
export type AppServerServerResponse<M extends AppServerServerRequestMethod> = JsonRpcResponse<ServerRequestResult<M>, JsonRpcError>;
export type AppServerServerRequestDefinition<M extends AppServerServerRequestMethod> = {
readonly method: M;
readonly __params?: ServerRequestParams<M>;
readonly __result?: ServerRequestResult<M>;
};
export const APP_SERVER_SERVER_REQUESTS: { [M in AppServerServerRequestMethod]: AppServerServerRequestDefinition<M> } = {
  "extensionClient/request": { method: "extensionClient/request" },
  "textDocument/list": { method: "textDocument/list" },
  "textDocument/read": { method: "textDocument/read" },
  "textDocument/apply": { method: "textDocument/apply" },
  "textDocument/release": { method: "textDocument/release" },
  "browser/create": { method: "browser/create" },
  "browser/sharing/set": { method: "browser/sharing/set" },
  "browser/observe": { method: "browser/observe" },
  "browser/perform": { method: "browser/perform" },
  "browser/close": { method: "browser/close" },
};
