// Generated by `ash-app-server-protocol generate_protocol`. Do not edit.
export const APP_SERVER_PROTOCOL_MAJOR = 7 as const;
export const APP_SERVER_SCHEMA_HASH = "sha256:81c59a39e1c79aa87854148d3bb36d14086f2f3fbd31dac674b581b98a6ea6c2" as const;
export type JsonRpcVersion = "2.0";
export type JsonRpcId = number | string | null;
export type JsonRpcRequest<P> = { jsonrpc: JsonRpcVersion; id: JsonRpcId; method: string; params: P };
export type JsonRpcNotification<P> = { jsonrpc: JsonRpcVersion; method: string; params: P };
export type JsonRpcSuccess<R> = { jsonrpc: JsonRpcVersion; id: JsonRpcId; result: R };
export type JsonRpcFailure<E> = { jsonrpc: JsonRpcVersion; id: JsonRpcId; error: E };
export type JsonRpcResponse<R, E> = JsonRpcSuccess<R> | JsonRpcFailure<E>;
export type JsonRpcError = { code: number; message: string; data: unknown };
