// Generated by `ash-app-server-protocol generate_protocol`. Do not edit.
import type { WebWorkspaceDirectory } from './WebWorkspaceDirectory.js';
export type WebWorkspaceListResult = { path: string, parent: string | null, directories: Array<WebWorkspaceDirectory>, };
