[package]
name = "ash-github"
version.workspace = true
edition.workspace = true
license-file.workspace = true
publish.workspace = true

[lib]
doctest = false

[dependencies]
base64.workspace = true
url = { workspace = true, features = ["serde"] }
serde = { workspace = true, features = ["derive"] }
serde_json = { workspace = true }
tokio = { workspace = true, features = ["rt", "time", "macros"] }
ash-http-client = { workspace = true }
ash-async-utils = { workspace = true }
ash-login = { workspace = true }
ash-secrets = { workspace = true }
[lints]
workspace = true
