[package]
name = "ash-livekit-client"
version.workspace = true
edition.workspace = true
license-file.workspace = true
publish.workspace = true

[lib]
name = "livekit_client"

[dependencies]
livekit-net.workspace = true
async-trait.workspace = true
ash-http-client = { path = "../http-client" }
ash-websocket-client = { path = "../websocket-client" }
livekit = { workspace = true, features = ["tokio", "rustls-tls-webpki-roots"] }
futures = { workspace = true }
tokio = { workspace = true, features = ["macros", "rt-multi-thread", "sync", "time"] }
thiserror = { workspace = true }
url = { workspace = true }

[dev-dependencies]
rustls.workspace = true
tokio-rustls.workspace = true
tokio-tungstenite.workspace = true
livekit-api = { package = "ash-livekit-api", path = "../livekit-api" }
ash-secrets = { workspace = true }
tempfile = { workspace = true }

[lints]
workspace = true
