// Generated by `ash-app-server-protocol generate_protocol`. Do not edit.
import type { AccountCreditBalanceDto } from './AccountCreditBalanceDto.js';
import type { AccountRateLimitDto } from './AccountRateLimitDto.js';

export type AccountRateLimitsReadResult = { provider: string, accountId: string, plan: string, limits: Array<AccountRateLimitDto>, credits: AccountCreditBalanceDto | null, };
