// Generated by `ash-app-server-protocol generate_protocol`. Do not edit.
import type { ModelRef } from './ModelRef.js';
import type { ReasoningEffort } from './ReasoningEffort.js';

export type AdvisorConfig = { model: ModelRef, enabled: boolean, reasoningEffort?: ReasoningEffort | null, maxCalls: number, maxOutputTokens: number, };
