// Generated by `ash-app-server-protocol generate_protocol`. Do not edit.
import type { AdvisorConfig } from './AdvisorConfig.js';

export type AdvisorSelection = { "type": "default" } | { "type": "off" } | { "type": "model", config: AdvisorConfig, };
