// Generated by `ash-app-server-protocol generate_protocol`. Do not edit.
import type { EnvironmentDraft } from './EnvironmentDraft.js';

export type ApprovalEnvironmentScanResult = { root: string, draft: EnvironmentDraft, };
