// Generated by `ash-app-server-protocol generate_protocol`. Do not edit.
import type { ApprovalEnvironmentScope } from './ApprovalEnvironmentScope.js';

export type ApprovalEnvironmentReadParams = { scope: ApprovalEnvironmentScope, };
