// Generated by `ash-app-server-protocol generate_protocol`. Do not edit.
import type { EnvironmentProfile } from './EnvironmentProfile.js';

export type ApprovalEnvironmentReadResult = { root: string, profile: EnvironmentProfile, };
