// Generated by `ash-app-server-protocol generate_protocol`. Do not edit.
import type { EnvironmentDraft } from './EnvironmentDraft.js';
import type { HistoryCoverage } from './HistoryCoverage.js';

export type ApprovalEnvironmentScanResult = { root: string, draft: EnvironmentDraft, history?: HistoryCoverage | null, };
