// Generated by `ash-app-server-protocol generate_protocol`. Do not edit.
import type { ApprovalEnvironmentScope } from './ApprovalEnvironmentScope.js';
import type { EntryInput } from './EntryInput.js';

export type ApprovalEnvironmentSaveParams = { scope: ApprovalEnvironmentScope, commandId: string, expectedRevision: number, draftId?: string | null, entries: Array<EntryInput>, };
