// Generated by `ash-app-server-protocol generate_protocol`. Do not edit.
import type { EnvironmentProfile } from './EnvironmentProfile.js';
import type { ScanOptions } from './ScanOptions.js';

export type ApprovalEnvironmentReadResult = { root: string, profile: EnvironmentProfile, scanOptions: ScanOptions, };
