// Generated by `ash-app-server-protocol generate_protocol`. Do not edit.
import type { AssetVersionResult } from './AssetVersionResult.js';

export type AssetCatalogEntry = { version: AssetVersionResult, addedAt: bigint, favorite: boolean, collectionIds: Array<string>, };
