// Generated by `ash-app-server-protocol generate_protocol`. Do not edit.
import type { AttachmentRef } from './AttachmentRef.js';

export type AttachmentMaterializeResult = { attachment: AttachmentRef, };
