// Generated by `ash-app-server-protocol generate_protocol`. Do not edit.
import type { BackupRecordDto } from './BackupRecordDto.js';

export type BackupListResult = { backups: Array<BackupRecordDto>, };
