// Generated by `ash-app-server-protocol generate_protocol`. Do not edit.
import type { CallRole } from './CallRole.js';

export type CallRoleParams = { resourceId: string, operationId: string, revision: number, memberId: string, role: CallRole, };
