// Generated by `ash-app-server-protocol generate_protocol`. Do not edit.
import type { CallRole } from './CallRole.js';

export type CallInviteParams = { resourceId: string, operationId: string, revision: number, role: CallRole, };
