// Generated by `ash-app-server-protocol generate_protocol`. Do not edit.
import type { CallScreenFrame } from './CallScreenFrame.js';

export type CallScreenFrames = { mediaEpoch: number, tracks: Array<string>, frames: Array<CallScreenFrame>, };
