// Generated by `ash-app-server-protocol generate_protocol`. Do not edit.
import type { CallConnection } from './CallConnection.js';
import type { CallParticipant } from './CallParticipant.js';
import type { CallSnapshot } from './CallSnapshot.js';

export type CallStatus = { resourceId: string, sequence: number, connection: CallConnection, call: CallSnapshot, memberId: string, participants: Array<CallParticipant>, muted: boolean, deafened: boolean, microphoneAllowed: boolean, error: string | null, };
