// Generated by `ash-app-server-protocol generate_protocol`. Do not edit.
import type { CallScreenSource } from './CallScreenSource.js';

export type CallScreenSources = { sources: Array<CallScreenSource>, };
