// Generated by `ash-app-server-protocol generate_protocol`. Do not edit.
export type CallControl = { "type": "mute" } | { "type": "unmute" } | { "type": "deafen" } | { "type": "undeafen" } | { "type": "selectDevice", operationId: string, revision: number, } | { "type": "volume", trackId: string, volume: number, };
