// Generated by `ash-app-server-protocol generate_protocol`. Do not edit.
import type { ScreenTarget } from './ScreenTarget.js';

export type CallControl = { "type": "mute" } | { "type": "unmute" } | { "type": "deafen" } | { "type": "undeafen" } | { "type": "shareScreen", target: ScreenTarget, } | { "type": "stopScreenShare" } | { "type": "selectDevice", operationId: string, revision: number, } | { "type": "volume", trackId: string, volume: number, };
