// Generated by `ash-app-server-protocol generate_protocol`. Do not edit.
import type { CallControl } from './CallControl.js';

export type CallControlParams = { resourceId: string, control: CallControl, };
