// Generated by `ash-app-server-protocol generate_protocol`. Do not edit.
import type { CommandSource } from './CommandSource.js';

export type CommandEvidence = { occurrences: number, sessionCount: number, samples: Array<CommandSource>, };
