// Generated by `ash-app-server-protocol generate_protocol`. Do not edit.
import type { ModelContextInspection } from './ModelContextInspection.js';

export type ContextReadResult = { context: ModelContextInspection, };
