// Generated by `ash-app-server-protocol generate_protocol`. Do not edit.
import type { ContextReadScope } from './ContextReadScope.js';

export type ContextReadParams = { scope: ContextReadScope, };
