// Generated by `ash-app-server-protocol generate_protocol`. Do not edit.
import type { ContextToolDefinition } from './ContextToolDefinition.js';
import type { ModelContextInspection } from './ModelContextInspection.js';

export type ContextReadResult = { context: ModelContextInspection,
/**
 * Populated only for diagnostics; definitions and counts come from the same catalog sample.
 */
toolDefinitions: Array<ContextToolDefinition>, };
