// Generated by `ash-app-server-protocol generate_protocol`. Do not edit.
import type { SessionId } from './SessionId.js';
import type { ThreadId } from './ThreadId.js';

export type ContextReadScope = { "type": "environment" } | { "type": "thread", sessionId: SessionId, threadId: ThreadId, };
