// Generated by `ash-app-server-protocol generate_protocol`. Do not edit.
export type ContextCompactionPolicy = { "mode": "summary", summaryTokens: number, recentTokens: number, } | { "mode": "handoff", bufferTokens: number, stateTokens: number, };
