// Generated by `ash-app-server-protocol generate_protocol`. Do not edit.
import type { CustomProviderProtocolDto } from './CustomProviderProtocolDto.js';

export type CustomProviderConfigDto = { contextWindow: number, order: number, model?: string | null, modelAliases?: { [key in string]: string } | null, name: string, protocol: CustomProviderProtocolDto, };
