// Generated by `ash-app-server-protocol generate_protocol`. Do not edit.
export type DictationModelStatus = { modelId: string,
/**
 * Installed package availability does not imply an active loaded recognizer.
 */
available: boolean, };
