// Generated by `ash-app-server-protocol generate_protocol`. Do not edit.
import type { DictationInputDevice } from './DictationInputDevice.js';

export type DictationOptions = { inputDevices: Array<DictationInputDevice>,
/**
 * Empty means language hints are not supported by this backend/model.
 */
languages: Array<string>, };
