// Generated by `ash-app-server-protocol generate_protocol`. Do not edit.
import type { DictationCloudProvider } from './DictationCloudProvider.js';

export type DictationBackend = { "type": "local", modelId: string, } | { "type": "cloud", provider: DictationCloudProvider, modelId: string, };
