// Generated by `ash-app-server-protocol generate_protocol`. Do not edit.
import type { DictationBackend } from './DictationBackend.js';

export type DictationStartParams = { resourceId: string, backend: DictationBackend,
/**
 * Physical microphone identity from dictation/options; None follows the system default.
 */
inputDevice: string | null,
/**
 * Explicit provider language hint; None delegates detection to the model.
 */
language: string | null, };
