// Generated by `ash-app-server-protocol generate_protocol`. Do not edit.
import type { DictationModelStage } from './DictationModelStage.js';

export type DictationModelStatus = { modelId: string,
/**
 * Installed package availability does not imply an active loaded recognizer.
 */
available: boolean, sizeBytes: number,
/**
 * Last process-owned preparation stage, including its terminal result.
 */
stage: DictationModelStage | null, };
