// Generated by `ash-app-server-protocol generate_protocol`. Do not edit.
import type { DictationModelStatus } from './DictationModelStatus.js';

export type DictationModelList = { models: Array<DictationModelStatus>, };
