// Generated by `ash-app-server-protocol generate_protocol`. Do not edit.
import type { DictationBackend } from './DictationBackend.js';

export type DictationOptionsParams = { backend: DictationBackend, };
