// Generated by `ash-app-server-protocol generate_protocol`. Do not edit.
import type { SourceKind } from './SourceKind.js';

export type EnvironmentSource = { id: string, kind: SourceKind, label: string, revision: string, };
