// Generated by `ash-app-server-protocol generate_protocol`. Do not edit.
import type { CommandEvidence } from './CommandEvidence.js';
import type { SourceKind } from './SourceKind.js';

export type EnvironmentSource = { id: string, kind: SourceKind, label: string, revision: string, command?: CommandEvidence | null, };
