// Generated by `ash-app-server-protocol generate_protocol`. Do not edit.
import type { EntryKind } from './EntryKind.js';
import type { EnvironmentSource } from './EnvironmentSource.js';

export type EnvironmentEntry = { id: string, kind: EntryKind, title: string, content: string, source: EnvironmentSource,
/**
 * Approval accepts this description as background, not as authorization for an action.
 */
accepted: boolean, current: boolean, };
