// Generated by `ash-app-server-protocol generate_protocol`. Do not edit.
import type { EnvironmentEntry } from './EnvironmentEntry.js';

export type EnvironmentProfile = { revision: number, entries: Array<EnvironmentEntry>, };
