// Generated by `ash-app-server-protocol generate_protocol`. Do not edit.
import type { EnvDirDto } from './EnvDirDto.js';

export type EnvWorkspaceSetResult = { cwd: string, dirs: Array<EnvDirDto>, };
