// Generated by `ash-app-server-protocol generate_protocol`. Do not edit.
import type { DirGrantDto } from './DirGrantDto.js';

export type EnvWorkspaceSetParams = { path: string, grant: DirGrantDto, };
