// Generated by `ash-app-server-protocol generate_protocol`. Do not edit.
import type { ExtensionHostActivationEventDto } from './ExtensionHostActivationEventDto.js';

export type ExtensionHostActivateParams = { extensionId: string, activationGeneration: number, event: ExtensionHostActivationEventDto, };
