// Generated by `ash-app-server-protocol generate_protocol`. Do not edit.
import type { ExtensionHostCommandContributionDto } from './ExtensionHostCommandContributionDto.js';

export type ExtensionHostActivationDto = { events: Array<string>, commands: Array<ExtensionHostCommandContributionDto>, };
