// Generated by `ash-app-server-protocol generate_protocol`. Do not edit.
import type { ExtensionDiagnosticSeverity } from './ExtensionDiagnosticSeverity.js';
import type { ExtensionTextPosition } from './ExtensionTextPosition.js';

export type ExtensionDiagnostic = { start: ExtensionTextPosition, end: ExtensionTextPosition, message: string, severity: ExtensionDiagnosticSeverity, source: string | null, code: string | null, };
