// Generated by `ash-app-server-protocol generate_protocol`. Do not edit.
export type ExtensionHostActivationEventDto = { "type": "command", command: string, } | { "type": "language", languageId: string, } | { "type": "startupFinished", };
