// Generated by `ash-app-server-protocol generate_protocol`. Do not edit.
import type { ExtensionTextEdit } from './ExtensionTextEdit.js';

export type ExtensionDocumentEdit = { uri: string, version: number, edits: Array<ExtensionTextEdit>, };
