// Generated by `ash-app-server-protocol generate_protocol`. Do not edit.
import type { ExtensionTextPosition } from './ExtensionTextPosition.js';

export type ExtensionTextEdit = { start: ExtensionTextPosition, end: ExtensionTextPosition, text: string, };
