// Generated by `ash-app-server-protocol generate_protocol`. Do not edit.
import type { ExtensionConfigurationTarget } from './ExtensionConfigurationTarget.js';
import type { ExtensionDocumentEdit } from './ExtensionDocumentEdit.js';
import type { ExtensionMessageSeverity } from './ExtensionMessageSeverity.js';
import type { JsonValue } from './JsonValue.js';

export type ExtensionClientOperation = { "operation": "executeCommand", command: string, arguments: Array<JsonValue>, } | { "operation": "readDocument", uri: string, } | { "operation": "readWorkspaceFile", path: string, } | { "operation": "listDocuments" } | { "operation": "applyEdit", documents: Array<ExtensionDocumentEdit>, } | { "operation": "readConfiguration", section: string, resource: string | null, } | { "operation": "updateConfiguration", section: string, value: JsonValue, target: ExtensionConfigurationTarget, } | { "operation": "showMessage", message: string, severity: ExtensionMessageSeverity, } | { "operation": "showQuickPick", items: Array<string>, placeholder: string, };
