// Generated by `ash-app-server-protocol generate_protocol`. Do not edit.
export type ExtensionHostLifecycleDto = "dormant" | "stopped" | "starting" | "handshaking" | "ready" | "recovering" | "crashLoop" | "failed";
