// Generated by `ash-app-server-protocol generate_protocol`. Do not edit.
import type { FileGlobTarget } from './FileGlobTarget.js';

export type FileGlobParams = { operationId: string, target: FileGlobTarget, includePatterns: Array<string>, excludePatterns: Array<string>, maxResults: number, };
