// Generated by `ash-app-server-protocol generate_protocol`. Do not edit.
import type { SessionId } from './SessionId.js';

export type FileGlobTarget = { "type": "workspace", dirId: string, } | { "type": "session", sessionId: SessionId, path: string, };
