// Generated by `ash-app-server-protocol generate_protocol`. Do not edit.
import type { SessionDirSelector } from './SessionDirSelector.js';

export type FsPasteSystemFilesParams = { dirId?: string, sessionDirectory?: SessionDirSelector, path: string, moveRequested: boolean, };
