// Generated by `ash-app-server-protocol generate_protocol`. Do not edit.
export type GitBranchDto = { name: string, objectId: string, current: boolean, upstream: string | null,
/**
 * Whether another worktree has checked out this branch. Older servers omit this field.
 */
checkedOutElsewhere?: boolean, };
