// Generated by `ash-app-server-protocol generate_protocol`. Do not edit.
import type { GitComparisonModeDto } from './GitComparisonModeDto.js';

export type GitCompareChangesParams = { repositoryId?: string, objectId: string, baseReference: string, mode: GitComparisonModeDto, };
