// Generated by `ash-app-server-protocol generate_protocol`. Do not edit.
import type { GitConflictResolutionDto } from './GitConflictResolutionDto.js';

export type GitCompleteConflictParams = { repositoryId?: string, path: string, expectedStageIds: [string | null, string | null, string | null], expectedResultObjectId: string | null, resolution: GitConflictResolutionDto, };
