// Generated by `ash-app-server-protocol generate_protocol`. Do not edit.
import type { GitIntegrationDto } from './GitIntegrationDto.js';
import type { GitNamedRefDto } from './GitNamedRefDto.js';
import type { GitStashDto } from './GitStashDto.js';

export type GitCatalogResult = { tags: Array<GitNamedRefDto>, stashes: Array<GitStashDto>, remotes: Array<string>, operation: GitIntegrationDto | null, };
