// Generated by `ash-app-server-protocol generate_protocol`. Do not edit.
import type { GitCommandOutcomeDto } from './GitCommandOutcomeDto.js';
import type { GitIntegrationDto } from './GitIntegrationDto.js';
import type { GitStatusResult } from './GitStatusResult.js';

export type GitCommandResult = { status: GitStatusResult, outcome: GitCommandOutcomeDto, operation: GitIntegrationDto | null, };
