// Generated by `ash-app-server-protocol generate_protocol`. Do not edit.
export type GitCommitFileParams = { repositoryId?: string, objectId: string, path: string,
/**
 * Exact base returned by compareChanges; omission compares with the commit's first parent.
 */
parentObjectId?: string, };
