// Generated by `ash-app-server-protocol generate_protocol`. Do not edit.
import type { GitIntegrationDto } from './GitIntegrationDto.js';
import type { GitStashModeDto } from './GitStashModeDto.js';

export type GitCommandDto = { "kind": "fetchAndCheckout", remote: string, remoteIdentity: string, reference: string, objectId: string, name: string, } | { "kind": "pushBranch", remote: string, remoteIdentity: string, name: string, branch: string, expectedHead: string, } | { "kind": "createBranchAt", name: string, objectId: string, } | { "kind": "checkoutDetached", objectId: string, } | { "kind": "checkoutRemoteBranch", name: string, reference: string, } | { "kind": "renameBranch", name: string, newName: string, } | { "kind": "deleteRemoteBranch", remote: string, name: string, } | { "kind": "merge", reference: string, } | { "kind": "rebase", reference: string, } | { "kind": "cherryPick", reference: string,
/**
 * One-based parent defining a merge commit's changes.
 */
mainline?: number, } | { "kind": "continue", operation: GitIntegrationDto, } | { "kind": "abort", operation: GitIntegrationDto, } | { "kind": "stash", message: string, mode: GitStashModeDto, } | { "kind": "applyStash", objectId: string, } | { "kind": "popStash", objectId: string, } | { "kind": "dropStash", objectId: string, } | { "kind": "createTag", name: string, reference: string, } | { "kind": "deleteTag", name: string, } | { "kind": "addRemote", name: string, url: string, } | { "kind": "removeRemote", name: string, } | { "kind": "amend", message: string, } | { "kind": "undoCommit", expectedHead: string, };
