// Generated by `ash-app-server-protocol generate_protocol`. Do not edit.
import type { GitCommandDto } from './GitCommandDto.js';

export type GitCommandParams = { repositoryId?: string, command: GitCommandDto, };
