// Generated by `ash-app-server-protocol generate_protocol`. Do not edit.
import type { GitFetchModeDto } from './GitFetchModeDto.js';

export type GitFetchParams = { repositoryId?: string, mode?: GitFetchModeDto, };
