// Generated by `ash-app-server-protocol generate_protocol`. Do not edit.
import type { IssueRepository } from './IssueRepository.js';

export type GitHubCommentUpdateParams = { operationId: string, repository: IssueRepository, commentId: number, body: string, };
