// Generated by `ash-app-server-protocol generate_protocol`. Do not edit.
import type { IssueRepository } from './IssueRepository.js';
import type { IssueState } from './IssueState.js';

export type GitHubPullRequestListParams = { operationId: string, repository: IssueRepository, state: IssueState, page: number, };
