// Generated by `ash-app-server-protocol generate_protocol`. Do not edit.
import type { IssueRepository } from './IssueRepository.js';

export type GitHubLabelParams = { operationId: string, repository: IssueRepository, name: string, color: string, };
