// Generated by `ash-app-server-protocol generate_protocol`. Do not edit.
import type { GitHubDiffSide } from './GitHubDiffSide.js';

export type GitHubReviewCommentInput = { path: string, line: number, side: GitHubDiffSide, body: string, };
