// Generated by `ash-app-server-protocol generate_protocol`. Do not edit.
import type { GitHubReviewCommentInput } from './GitHubReviewCommentInput.js';
import type { GitHubReviewEvent } from './GitHubReviewEvent.js';
import type { IssueRepository } from './IssueRepository.js';

export type GitHubPullRequestReviewParams = { operationId: string, accountId?: string, repository: IssueRepository, number: number, commit: string, event: GitHubReviewEvent, body: string, comments: Array<GitHubReviewCommentInput>, };
