// Generated by `ash-app-server-protocol generate_protocol`. Do not edit.
import type { IssueRepository } from './IssueRepository.js';

export type GitHubCommentDeleteParams = { operationId: string, repository: IssueRepository, commentId: number, };
