// Generated by `ash-app-server-protocol generate_protocol`. Do not edit.
export type GitHubCommit = { sha: string, url: string, message: string, author: string, committedAt: string, additions: number, deletions: number, };
