// Generated by `ash-app-server-protocol generate_protocol`. Do not edit.
export type GitHubPullRequest = { number: number, title: string, body: string, url: string, state: string, draft: boolean, mergedAt: string | null, mergeable: boolean | null, headCommit: string, headBranch: string, headRepository: string | null, baseBranch: string, autoMerge: boolean, };
