// Generated by `ash-app-server-protocol generate_protocol`. Do not edit.
import type { IssueSummary } from './IssueSummary.js';

export type GitHubIssueListResult = { issues: Array<IssueSummary>, nextPage: number | null, notice: string, };
