// Generated by `ash-app-server-protocol generate_protocol`. Do not edit.
import type { GitHubDiffSide } from './GitHubDiffSide.js';
import type { GitHubReviewCommentsResult } from './GitHubReviewCommentsResult.js';

export type GitHubReviewThread = { id: string, path: string, line: number | null, side: GitHubDiffSide, resolved: boolean, outdated: boolean, canResolve: boolean, comments: GitHubReviewCommentsResult, };
