// Generated by `ash-app-server-protocol generate_protocol`. Do not edit.
import type { GitHubCancelStatus } from './GitHubCancelStatus.js';

export type GitHubCancelResult = { status: GitHubCancelStatus, };
