// Generated by `ash-app-server-protocol generate_protocol`. Do not edit.
import type { GitHubForkBranches } from './GitHubForkBranches.js';
import type { IssueRepository } from './IssueRepository.js';

export type GitHubForkCreateParams = { operationId: string, accountId?: string, repository: IssueRepository, organization: string | null, name: string, branches: GitHubForkBranches, };
