// Generated by `ash-app-server-protocol generate_protocol`. Do not edit.
import type { IssueRepository } from './IssueRepository.js';

export type GitHubChecksParams = { operationId: string, repository: IssueRepository, commit: string, page: number, };
