// Generated by `ash-app-server-protocol generate_protocol`. Do not edit.
import type { GitHubPullRequestReference } from './GitHubPullRequestReference.js';
import type { SessionId } from './SessionId.js';

export type GitHubSessionPullRequestParams = { sessionId: SessionId, reference: GitHubPullRequestReference, };
