// Generated by `ash-app-server-protocol generate_protocol`. Do not edit.
import type { GitHubReviewThread } from './GitHubReviewThread.js';

export type GitHubReviewThreadsResult = { threads: Array<GitHubReviewThread>, nextCursor: string | null, };
