// Generated by `ash-app-server-protocol generate_protocol`. Do not edit.
import type { IssueComment } from './IssueComment.js';

export type GitHubCommentListResult = { comments: Array<IssueComment>, nextPage: number | null, };
