// Generated by `ash-app-server-protocol generate_protocol`. Do not edit.
export type GitHubPullRequestReview = { id: number, body: string, state: string, url: string, commit: string, submittedAt: string | null, };
