// Generated by `ash-app-server-protocol generate_protocol`. Do not edit.
import type { GitHubPullRequestReference } from './GitHubPullRequestReference.js';

export type GitHubSessionPullRequestsResult = { references: Array<GitHubPullRequestReference>, };
