// Generated by `ash-app-server-protocol generate_protocol`. Do not edit.
export type GitHubRepositoryResult = { defaultBranch: string, fullName: string, allowMergeCommit: boolean, allowSquashMerge: boolean, allowRebaseMerge: boolean, allowAutoMerge: boolean, };
