// Generated by `ash-app-server-protocol generate_protocol`. Do not edit.
import type { GitHubMergeMethod } from './GitHubMergeMethod.js';
import type { IssueRepository } from './IssueRepository.js';

export type GitHubPullRequestMergeParams = { operationId: string, repository: IssueRepository, number: number, commit: string, method: GitHubMergeMethod, };
