// Generated by `ash-app-server-protocol generate_protocol`. Do not edit.
import type { GitHubReviewComment } from './GitHubReviewComment.js';

export type GitHubReviewCommentsResult = { comments: Array<GitHubReviewComment>, nextCursor: string | null, };
