// Generated by `ash-app-server-protocol generate_protocol`. Do not edit.
import type { IssueRepository } from './IssueRepository.js';

export type GitHubFileReadParams = { operationId: string, accountId?: string, repository: IssueRepository, commit: string, path: string, };
