// Generated by `ash-app-server-protocol generate_protocol`. Do not edit.
import type { GitHubNotification } from './GitHubNotification.js';

export type GitHubNotificationsResult = { notifications: Array<GitHubNotification>, nextPage: number | null, };
