// Generated by `ash-app-server-protocol generate_protocol`. Do not edit.
import type { GitChangeFileComparisonDto } from './GitChangeFileComparisonDto.js';
import type { GitIndexSelectionDto } from './GitIndexSelectionDto.js';

export type GitIndexEditParams = { repositoryId?: string, path: string, comparison: GitChangeFileComparisonDto, expectedOriginal: string | null, expectedModified: string | null, selection: GitIndexSelectionDto, };
