// Generated by `ash-app-server-protocol generate_protocol`. Do not edit.
export type HistoryCoverage = { sessionsAvailable: number, sessionsScanned: number, commandsAvailable: number, commandsScanned: number, factsAvailable: number, factsIncluded: number, };
