// Generated by `ash-app-server-protocol generate_protocol`. Do not edit.
import type { HookConfigDto } from './HookConfigDto.js';

export type HookSourceDto = { namespace: string, configPath: string, hooks: Array<HookConfigDto>, };
