// Generated by `ash-app-server-protocol generate_protocol`. Do not edit.
import type { InstructionImportSource } from './InstructionImportSource.js';
import type { SessionDirSelector } from './SessionDirSelector.js';

export type InstructionImportPreviewParams = { source: InstructionImportSource, directory: SessionDirSelector, sources: Array<string>, };
