// Generated by `ash-app-server-protocol generate_protocol`. Do not edit.
import type { InstructionImportDiagnosticDto } from './InstructionImportDiagnosticDto.js';
import type { InstructionImportSourceDto } from './InstructionImportSourceDto.js';

export type InstructionImportPreviewResult = { source: InstructionImportSourceDto | null, target: string, targetConflict: boolean, diagnostics: Array<InstructionImportDiagnosticDto>, };
