// Generated by `ash-app-server-protocol generate_protocol`. Do not edit.
import type { InstructionDiagnosticCodeDto } from './InstructionDiagnosticCodeDto.js';
import type { InstructionSource } from './InstructionSource.js';

export type InstructionCatalogDiagnosticDto = { source: InstructionSource, relativePath: string | null, code: InstructionDiagnosticCodeDto, message: string, };
