// Generated by `ash-app-server-protocol generate_protocol`. Do not edit.
import type { InstructionDiagnosticDto } from './InstructionDiagnosticDto.js';
import type { InstructionImportItem } from './InstructionImportItem.js';

export type InstructionImportPreviewResult = {
/**
 * Canonical destination root; item targets are relative to this directory.
 */
targetDirectory: string, digest: string, items: Array<InstructionImportItem>, diagnostics: Array<InstructionDiagnosticDto>, };
