// Generated by `ash-app-server-protocol generate_protocol`. Do not edit.
import type { InstructionCatalogDiagnosticDto } from './InstructionCatalogDiagnosticDto.js';
import type { InstructionDto } from './InstructionDto.js';

export type InstructionListResult = { instructions: Array<InstructionDto>, diagnostics: Array<InstructionCatalogDiagnosticDto>, };
