// Generated by `ash-app-server-protocol generate_protocol`. Do not edit.
import type { ContentDigest } from './ContentDigest.js';
import type { InstructionSource } from './InstructionSource.js';

export type InstructionRef = { source: InstructionSource, relativePath: string, digest: ContentDigest, };
