// Generated by `ash-app-server-protocol generate_protocol`. Do not edit.
import type { InstructionImportScopeDto } from './InstructionImportScopeDto.js';

export type InstructionImportPreviewParams = { scope: InstructionImportScopeDto, };
