// Generated by `ash-app-server-protocol generate_protocol`. Do not edit.
import type { InstructionImportSource } from './InstructionImportSource.js';
import type { InstructionScopeDto } from './InstructionScopeDto.js';
import type { SessionDirSelector } from './SessionDirSelector.js';

export type InstructionImportParams = {
/**
 * Selects both source layout and destination ownership; never inferred from a path.
 */
scope: InstructionScopeDto, source: InstructionImportSource,
/**
 * Authorized source root: project directory or external user home.
 */
directory: SessionDirSelector, sources: Array<string>, digest: string, };
