// Generated by `ash-app-server-protocol generate_protocol`. Do not edit.
export type InstructionDiagnosticCodeDto = "sourceUnavailable" | "entryLimitExceeded" | "unsupportedFileType" | "symlinkNotAllowed" | "invalidName" | "invalidFrontmatter" | "invalidLoadPolicy" | "contentTooLarge" | "contentInvalidUtf8" | "emptyBody";
