// Generated by `ash-app-server-protocol generate_protocol`. Do not edit.
import type { InstructionLoadPolicyDto } from './InstructionLoadPolicyDto.js';
import type { InstructionRef } from './InstructionRef.js';

export type InstructionDto = { reference: InstructionRef, name: string, loadPolicy: InstructionLoadPolicyDto, path: string, };
