// Generated by `ash-app-server-protocol generate_protocol`. Do not edit.
import type { InstructionImportStatus } from './InstructionImportStatus.js';

export type InstructionImportItem = { source: string, target: string, content: string, status: InstructionImportStatus, message: string | null, };
