// Generated by `ash-app-server-protocol generate_protocol`. Do not edit.
import type { InstructionImportScopeDto } from './InstructionImportScopeDto.js';

export type InstructionImportApplyParams = { scope: InstructionImportScopeDto, relativePath: string, expectedSha256: string, expectedTarget: string, };
