// Generated by `ash-app-server-protocol generate_protocol`. Do not edit.
export type InstructionImportDiagnosticCodeDto = "metadataUnavailable" | "unexpectedFileType" | "symlinkNotAllowed" | "escapesSelectedRoot" | "invalidContent" | "limitExceeded";
