// Generated by `ash-app-server-protocol generate_protocol`. Do not edit.
import type { InstructionImportDiagnosticCodeDto } from './InstructionImportDiagnosticCodeDto.js';

export type InstructionImportDiagnosticDto = { relativePath: string, code: InstructionImportDiagnosticCodeDto, };
