// Generated by `ash-app-server-protocol generate_protocol`. Do not edit.
import type { InstructionDiagnosticDto } from './InstructionDiagnosticDto.js';
import type { InstructionImportItem } from './InstructionImportItem.js';

export type InstructionImportPreviewResult = { digest: string, items: Array<InstructionImportItem>, diagnostics: Array<InstructionDiagnosticDto>, };
