// Generated by `ash-app-server-protocol generate_protocol`. Do not edit.
import type { IssueReporterCancelStatus } from './IssueReporterCancelStatus.js';

export type IssueReporterCancelResult = { status: IssueReporterCancelStatus, };
