// Generated by `ash-app-server-protocol generate_protocol`. Do not edit.
import type { SessionDirSelector } from './SessionDirSelector.js';

export type LanguageServersParams = { dirId?: string, sessionDirectory?: SessionDirSelector, };
