// Generated by `ash-app-server-protocol generate_protocol`. Do not edit.
import type { MarketplaceCapabilityKindDto } from './MarketplaceCapabilityKindDto.js';

export type MarketplaceSearchParams = { query: string, packageType: string | null, capabilityKind: MarketplaceCapabilityKindDto | null,
/**
 * Requires a signed language-server route, excluding static-only language resources.
 */
languageId: string | null, limit: number | null, };
