// Generated by `ash-app-server-protocol generate_protocol`. Do not edit.
import type { MarketplacePackageRefDto } from './MarketplacePackageRefDto.js';

export type MarketplaceEditorExtensionPolicyDto = { installationId: string, package: MarketplacePackageRefDto,
/**
 * Entry selection does not promise API compatibility. Missing entries remain resources-only.
 */
entrypoint: string | null, enabled: boolean, granted: boolean, };
