// Generated by `ash-app-server-protocol generate_protocol`. Do not edit.
export type MediaState = { "state": "preparing" } | { "state": "ready" } | { "state": "rotating", previousRoom: string, } | { "state": "closing" } | { "state": "closed" };
