// Generated by `ash-app-server-protocol generate_protocol`. Do not edit.
import type { DirId } from './DirId.js';
import type { ProjectId } from './ProjectId.js';
import type { TeamId } from './TeamId.js';

export type MemoryScope = { "type": "profile" } | { "type": "project", projectId: ProjectId, } | { "type": "team", teamId: TeamId, } | { "type": "dir", dirId: DirId, };
