// Generated by `ash-app-server-protocol generate_protocol`. Do not edit.
import type { ContextCompactionPolicy } from './ContextCompactionPolicy.js';
import type { ModelContextAllocation } from './ModelContextAllocation.js';
import type { ModelContextCategoryUsage } from './ModelContextCategoryUsage.js';
import type { ModelContextUsage } from './ModelContextUsage.js';
import type { ModelRef } from './ModelRef.js';

export type ModelContextInspection = { compactionPolicy: ContextCompactionPolicy, model: ModelRef | null, estimatedTokens: number, estimatorRevision: string, categories: Array<ModelContextCategoryUsage>, allocation: ModelContextAllocation | null, latestRequest: ModelContextUsage | null, };
