// Generated by `ash-app-server-protocol generate_protocol`. Do not edit.
import type { CapabilitySupport } from './CapabilitySupport.js';
import type { ModelAcceleration } from './ModelAcceleration.js';
import type { ModelInputModality } from './ModelInputModality.js';
import type { ModelReasoningSummary } from './ModelReasoningSummary.js';
import type { ModelServiceTier } from './ModelServiceTier.js';
import type { ModelToolOutputLimit } from './ModelToolOutputLimit.js';
import type { ModelVerbosity } from './ModelVerbosity.js';

export type ModelSettings = {
/**
 * Declared input kinds; `None` means unknown, while a declared list includes text.
 */
input_modalities: Array<ModelInputModality> | null,
/**
 * Support for a verbosity request parameter, not a promise about actual response length.
 */
verbosity: CapabilitySupport,
/**
 * Ash request default; requires confirmed verbosity support.
 */
default_verbosity: ModelVerbosity | null,
/**
 * Support for returning reasoning summaries, separate from effort and replayable reasoning state.
 */
reasoning_summary: CapabilitySupport,
/**
 * Ash summary default; omission leaves it unspecified, while [`ModelReasoningSummary::None`] suppresses summaries.
 */
default_reasoning_summary: ModelReasoningSummary | null,
/**
 * Exact provider request IDs and display copy; a listed tier does not establish entitlement.
 */
service_tiers: Array<ModelServiceTier> | null,
/**
 * Ash request default referencing a declared tier ID; absence sends no default override.
 */
default_service_tier: string | null,
/**
 * Mechanism selected by the product's acceleration preference; distinct from explicit request values.
 */
acceleration: ModelAcceleration | null,
/**
 * Core's model-visible tool-result truncation budget, not a provider inference parameter.
 */
tool_output_limit: ModelToolOutputLimit | null, };
