// Generated by `ash-app-server-protocol generate_protocol`. Do not edit.
import type { CapabilitySupport } from './CapabilitySupport.js';
import type { ModelInputModality } from './ModelInputModality.js';
import type { ModelReasoningSummary } from './ModelReasoningSummary.js';
import type { ModelServiceTier } from './ModelServiceTier.js';
import type { ModelToolOutputLimit } from './ModelToolOutputLimit.js';
import type { ModelVerbosity } from './ModelVerbosity.js';

export type ModelSettings = { inputModalities: Array<ModelInputModality> | null, verbosity: CapabilitySupport, defaultVerbosity: ModelVerbosity | null, reasoningSummary: CapabilitySupport, defaultReasoningSummary: ModelReasoningSummary | null, serviceTiers: Array<ModelServiceTier> | null, defaultServiceTier: ModelServiceTier | null, toolOutputLimit: ModelToolOutputLimit | null, };
