// Generated by `ash-app-server-protocol generate_protocol`. Do not edit.
export type ModelContextSourceUsage = { name: string,
/**
 * Catalog entry count, including metadata omitted by the prompt byte limit.
 * Individual instruction and tool sources have no catalog count.
 */
itemCount: number | null, tokens: number, };
