// Generated by `ash-app-server-protocol generate_protocol`. Do not edit.
import type { ModelCapabilities } from './ModelCapabilities.js';
import type { ModelRef } from './ModelRef.js';
import type { Personality } from './Personality.js';
import type { ReasoningEffort } from './ReasoningEffort.js';

export type ModelCatalogEntry = { model: ModelRef, displayName: string, contextWindow: number | null, autoCompactTokenLimit: number | null, availableContextWindow?: number | null, capabilities: ModelCapabilities, supportedReasoningEfforts: Array<ReasoningEffort>, modelReasoningEffort: ReasoningEffort | null, defaultPersonality: Personality | null, };
