// Generated by `ash-app-server-protocol generate_protocol`. Do not edit.
import type { ModelId } from './ModelId.js';
import type { ModelSpeed } from './ModelSpeed.js';

export type ModelAcceleration = { "type": "serviceTier", serviceTier: string, } | { "type": "speed", speed: ModelSpeed, name: string, description: string, } | { "type": "model", model: ModelId, name: string, description: string, };
