// Generated by `ash-app-server-protocol generate_protocol`. Do not edit.
import type { CapabilitySupport } from './CapabilitySupport.js';
import type { ModelSettings } from './ModelSettings.js';

export type ModelCapabilities = { tools: CapabilitySupport, reasoning: CapabilitySupport, parallelToolCalls: CapabilitySupport, personality: CapabilitySupport, imageDetailOriginal: CapabilitySupport,
/**
 * Whether acceleration is supported; [`crate::ModelSettings::acceleration`] declares its mechanism.
 */
fastMode: CapabilitySupport, };
