// Generated by `ash-app-server-protocol generate_protocol`. Do not edit.
import type { CommandId } from './CommandId.js';
import type { ModelRef } from './ModelRef.js';

export type ModelPreferencesUpdateParams = { command_id: CommandId, expected_revision: number, model: ModelRef, fast?: boolean | null, context_window?: number | null, };
