// Generated by `ash-app-server-protocol generate_protocol`. Do not edit.
import type { CommandId } from './CommandId.js';
import type { ModelRef } from './ModelRef.js';

export type ModelPreferencesUpdateParams = { commandId: CommandId, expectedRevision: number, model: ModelRef, fast?: boolean | null, contextWindow?: number | null, };
