// Generated by `ash-app-server-protocol generate_protocol`. Do not edit.
export type ModelContextAllocation = { contextWindow: number, autoCompactWindow: number, autoCompactAt: number, autoCompactBuffer: number, reservedOutput: number, safetyMargin: number, };
