// Generated by `ash-app-server-protocol generate_protocol`. Do not edit.
export type ModelRetirement = {
/**
 * Exact shutdown date in YYYY-MM-DD form; null means announced without a confirmed date.
 * Earliest possible dates are not exact shutdown dates. Keep date-only values out of time zones.
 */
shutdown_date: string | null, };
