// Generated by `ash-app-server-protocol generate_protocol`. Do not edit.
import type { CommandId } from './CommandId.js';
import type { HttpCompatibilityModeDto } from './HttpCompatibilityModeDto.js';

export type NetworkHttpConfigureParams = { commandId: CommandId, expectedRevision: number, httpMode: HttpCompatibilityModeDto, };
