// Generated by `ash-app-server-protocol generate_protocol`. Do not edit.
import type { NetworkCheckOutcomeDto } from './NetworkCheckOutcomeDto.js';

export type NetworkCheckDto = { connection: string, targetId: string | null, outcome: NetworkCheckOutcomeDto, };
