// Generated by `ash-app-server-protocol generate_protocol`. Do not edit.
import type { NetworkCheckDto } from './NetworkCheckDto.js';
import type { NetworkReadResult } from './NetworkReadResult.js';

export type NetworkDiagnosticsRunResult = { network: NetworkReadResult, checks: Array<NetworkCheckDto>, };
