// Generated by `ash-app-server-protocol generate_protocol`. Do not edit.
import type { NetworkFailureDto } from './NetworkFailureDto.js';

export type NetworkCheckOutcomeDto = { "type": "reachable", httpStatus: number, } | { "type": "accountAvailable" } | { "type": "failed", failure: NetworkFailureDto, };
