// Generated by `ash-app-server-protocol generate_protocol`. Do not edit.
import type { NetworkTargetDto } from './NetworkTargetDto.js';

export type NetworkReadResult = { targets: Array<NetworkTargetDto>, };
