// Generated by `ash-app-server-protocol generate_protocol`. Do not edit.
import type { PluginCommandResultDto } from './PluginCommandResultDto.js';

export type PluginInstallLocalResult = { id: string, version: string, digest: string, command: PluginCommandResultDto, };
