// Generated by `ash-app-server-protocol generate_protocol`. Do not edit.
import type { PluginPermissionDto } from './PluginPermissionDto.js';

export type PluginPackageDto = { id: string, version: string, digest: string, displayName: string, permissions: Array<PluginPermissionDto>, hasEditorExtensions: boolean, enabled: boolean, granted: boolean, effective: boolean, revoked: boolean, };
