// Generated by `ash-app-server-protocol generate_protocol`. Do not edit.
import type { PluginDirectoryAccessDto } from './PluginDirectoryAccessDto.js';

export type PluginPermissionDto = { "type": "directory", access: PluginDirectoryAccessDto, } | { "type": "process", executable: string, } | { "type": "network", hosts: Array<string>, };
