// Generated by `ash-app-server-protocol generate_protocol`. Do not edit.
import type { ModelAccess } from './ModelAccess.js';
import type { ProviderApiKeyPolicyDto } from './ProviderApiKeyPolicyDto.js';

export type ProviderCatalogEntryDto = { connection: string, access: ModelAccess, active: boolean, configured: boolean, ready: boolean, provider: string, displayName: string, apiKeyPolicy: ProviderApiKeyPolicyDto, apiKeyConfigured: boolean, };
