// Generated by `ash-app-server-protocol generate_protocol`. Do not edit.
import type { CommandId } from './CommandId.js';

export type ProviderActivateParams = { commandId: CommandId, expectedRevision: number, connection: string, };
