// Generated by `ash-app-server-protocol generate_protocol`. Do not edit.
import type { ApprovalMode } from './ApprovalMode.js';
import type { CollaborationMode } from './CollaborationMode.js';
import type { CommandId } from './CommandId.js';
import type { ModelRef } from './ModelRef.js';
import type { ReasoningEffort } from './ReasoningEffort.js';
import type { SessionId } from './SessionId.js';
import type { ThreadId } from './ThreadId.js';
import type { ToolMode } from './ToolMode.js';
import type { TurnId } from './TurnId.js';
import type { UserInput } from './UserInput.js';

export type QueueInput = { commandId: CommandId, sessionId: SessionId, threadId: ThreadId,
/**
 * Execution directory selected by the host when accepting the message.
 */
directory: string, input: Array<UserInput>, mode: CollaborationMode, model: ModelRef | null, reasoningEffort: ReasoningEffort | null, toolMode: ToolMode, approvalMode: ApprovalMode, steerTurn: TurnId | null, };
