// Generated by `ash-app-server-protocol generate_protocol`. Do not edit.
import type { ApprovalMode } from './ApprovalMode.js';
import type { CollaborationMode } from './CollaborationMode.js';
import type { CommandId } from './CommandId.js';
import type { InputItem } from './InputItem.js';
import type { ModelRef } from './ModelRef.js';
import type { ReasoningEffort } from './ReasoningEffort.js';
import type { SessionId } from './SessionId.js';
import type { ThreadId } from './ThreadId.js';
import type { ToolMode } from './ToolMode.js';

export type QueueEnqueueParams = { commandId: CommandId, sessionId: SessionId, threadId: ThreadId, input: Array<InputItem>, mode: CollaborationMode, model?: ModelRef | null, reasoningEffort?: ReasoningEffort | null, toolMode?: ToolMode | null, approvalMode: ApprovalMode, };
