// Generated by `ash-app-server-protocol generate_protocol`. Do not edit.
export type ResponseDebugContext = { requestId: string | null, cfRay: string | null, authError: string | null, authErrorCode: string | null, };
