// Generated by `ash-app-server-protocol generate_protocol`. Do not edit.
export type ScanOptions = { recentCommands: boolean, shellHistory: boolean, otherRepositories: boolean, summarizeWithModel: boolean, };
