// Generated by `ash-app-server-protocol generate_protocol`. Do not edit.
export type SessionWorkspaceSelection = { "type": "current" } | { "type": "local", root: string, } | { "type": "ssh", host: string, root: string, };
