// Generated by `ash-app-server-protocol generate_protocol`. Do not edit.
import type { ModelRef } from './ModelRef.js';
import type { SessionExecutionTarget } from './SessionExecutionTarget.js';
import type { SessionId } from './SessionId.js';
import type { SessionManagerInfo } from './SessionManagerInfo.js';
import type { SessionStatus } from './SessionStatus.js';
import type { SessionThread } from './SessionThread.js';
import type { Thread } from './Thread.js';

export type Session = { sessionId: SessionId, title: string, status: SessionStatus, executionTarget?: SessionExecutionTarget | null,
/**
 * Current model selected on the Session root Thread; child and fork models are excluded.
 */
model?: ModelRef | null, manager: SessionManagerInfo, threads: Array<SessionThread>, };
