// Generated by `ash-app-server-protocol generate_protocol`. Do not edit.
import type { CodeSnapshot } from './CodeSnapshot.js';
import type { ContentDigest } from './ContentDigest.js';
import type { SourceTask } from './SourceTask.js';

export type TaskPackage = { deliveryId: ContentDigest, source: SourceTask, title: string, instructions: string,
/**
 * Explicit handoff context and source acceptance evidence; never hidden reasoning.
 */
context: string, code: CodeSnapshot, };
