// Generated by `ash-app-server-protocol generate_protocol`. Do not edit.
import type { QueueStatus } from './QueueStatus.js';
import type { StableTurnError } from './StableTurnError.js';
import type { TaskReceipt } from './TaskReceipt.js';
import type { TurnId } from './TurnId.js';
import type { TurnStatus } from './TurnStatus.js';

export type TaskReport = { receipt: TaskReceipt, queueStatus: QueueStatus, turnId: TurnId | null, turnStatus: TurnStatus | null, turnError: StableTurnError | null, message: string | null, messageTruncated: boolean, error: string | null, };
