// Generated by `ash-app-server-protocol generate_protocol`. Do not edit.
import type { AgentId } from './AgentId.js';
import type { TeamId } from './TeamId.js';

export type TeamMessageListParams = { teamId: TeamId, readerId: AgentId, };
