// Generated by `ash-app-server-protocol generate_protocol`. Do not edit.
import type { AgentId } from './AgentId.js';
import type { SessionId } from './SessionId.js';
import type { TeamId } from './TeamId.js';
import type { TeamMemberDto } from './TeamMemberDto.js';
import type { TeamRunId } from './TeamRunId.js';
import type { ThreadId } from './ThreadId.js';

export type TeamRunDto = { runId: TeamRunId, teamId: TeamId, teamRevision: number, members: Array<TeamMemberDto>, coordinatorId: AgentId, sessionId: SessionId, coordinatorThreadId: ThreadId, objective: string, };
