// Generated by `ash-app-server-protocol generate_protocol`. Do not edit.
import type { CommandId } from './CommandId.js';
import type { TeamCommandDto } from './TeamCommandDto.js';
import type { TeamId } from './TeamId.js';

export type TeamCommandParams = { commandId: CommandId, teamId: TeamId, expectedRevision: number, command: TeamCommandDto, };
