// Generated by `ash-app-server-protocol generate_protocol`. Do not edit.
import type { TerminalProcessReady } from './TerminalProcessReady.js';

export type TerminalProcessInfo = { ready: TerminalProcessReady, cwd: string | null, rows: number, cols: number, };
