// Generated by `ash-app-server-protocol generate_protocol`. Do not edit.
import type { TerminalProcessReady } from './TerminalProcessReady.js';
import type { TerminalReconnectLease } from './TerminalReconnectLease.js';

export type TerminalAttachResult = { ready: TerminalProcessReady, terminalId: string, reconnect: TerminalReconnectLease, };
