// Generated by `ash-app-server-protocol generate_protocol`. Do not edit.
export type TestingSource = {
/**
 * Slash-separated path relative to the authorized workspace directory.
 */
path: string, line: number, };
