// Generated by `ash-app-server-protocol generate_protocol`. Do not edit.
import type { TestingState } from './TestingState.js';

export type TestingResult = { testId: string, state: TestingState, durationMs: number, output: string, outputTruncated: boolean, failurePath: string | null, failureLine: number | null, };
