// Generated by `ash-app-server-protocol generate_protocol`. Do not edit.
import type { TestingSource } from './TestingSource.js';
import type { TestingTargetKind } from './TestingTargetKind.js';

export type TestingItem = { id: string, package: string, target: string, targetKind: TestingTargetKind, name: string, source: TestingSource | null, debuggable: boolean, };
