// Generated by `ash-app-server-protocol generate_protocol`. Do not edit.
import type { TestingItem } from './TestingItem.js';
import type { TestingOperationKind } from './TestingOperationKind.js';
import type { TestingOperationStatus } from './TestingOperationStatus.js';
import type { TestingResult } from './TestingResult.js';

export type TestingSnapshot = { operationId: string, kind: TestingOperationKind, status: TestingOperationStatus, tests: Array<TestingItem>, results: Array<TestingResult>, error: string | null, sequence: number, };
