// Generated by `ash-app-server-protocol generate_protocol`. Do not edit.
import type { TestingTargetKind } from './TestingTargetKind.js';

export type TestingItem = { id: string, package: string, target: string, targetKind: TestingTargetKind, name: string,
/**
 * Slash-separated path relative to the authorized workspace directory.
 */
path: string, line: number, };
