// Generated by `ash-app-server-protocol generate_protocol`. Do not edit.
import type { TextDocumentChangeDto } from './TextDocumentChangeDto.js';
import type { ThreadId } from './ThreadId.js';
import type { TurnId } from './TurnId.js';

export type TextDocumentApplyParams = { threadId: ThreadId, turnId: TurnId, changes: Array<TextDocumentChangeDto>, };
