// Generated by `ash-app-server-protocol generate_protocol`. Do not edit.
import type { TextDocumentContentDto } from './TextDocumentContentDto.js';

export type TextDocumentListResult = { "kind": "documents", documents: Array<TextDocumentContentDto>, } | { "kind": "failed", message: string, };
