// Generated by `ash-app-server-protocol generate_protocol`. Do not edit.
import type { TextDocumentChangeDto } from './TextDocumentChangeDto.js';

export type TextDocumentApplyParams = { changes: Array<TextDocumentChangeDto>, };
