// Generated by `ash-app-server-protocol generate_protocol`. Do not edit.
import type { CommandId } from './CommandId.js';

export type TgrepDisableAndDeleteParams = { commandId: CommandId, expectedRevision: number, };
