// Generated by `ash-app-server-protocol generate_protocol`. Do not edit.
import type { ConfigCommandResult } from './ConfigCommandResult.js';
import type { LocalIndexClearOutcomeDto } from './LocalIndexClearOutcomeDto.js';

export type TgrepDisableAndDeleteResult = { config: ConfigCommandResult, deletion: LocalIndexClearOutcomeDto, };
