// Generated by `ash-app-server-protocol generate_protocol`. Do not edit.
export type TgrepIndexStatusResult = { enabled: boolean, active: boolean, indexing: boolean, ready: boolean, indexedFileCount: number, watcherActive: boolean, };
