// Generated by `ash-app-server-protocol generate_protocol`. Do not edit.
import type { AudioAttachmentRef } from './AudioAttachmentRef.js';
import type { CommandId } from './CommandId.js';
import type { ContentPart } from './ContentPart.js';
import type { ImageAttachmentRef } from './ImageAttachmentRef.js';
import type { ItemId } from './ItemId.js';
import type { ReasoningState } from './ReasoningState.js';
import type { ToolCallBinding } from './ToolCallBinding.js';
import type { ToolCallId } from './ToolCallId.js';
import type { ToolName } from './ToolName.js';
import type { TurnId } from './TurnId.js';

export type ThreadItem = { "type": "userAudioAttachment", clientId?: CommandId | null, itemId: ItemId, turnId: TurnId, attachment: AudioAttachmentRef, } | { "type": "userMessage",
/**
 * The submitting command's ID, shared by all input parts of that submission.
 * Older stored items have no ID and cannot acknowledge a pending client submission.
 */
clientId?: CommandId | null, itemId: ItemId, turnId: TurnId, text: string, } | { "type": "userContext", clientId?: CommandId | null, itemId: ItemId, turnId: TurnId, name: string, content: string, } | { "type": "userImage", clientId?: CommandId | null, itemId: ItemId, turnId: TurnId, url: string, } | { "type": "userImageAttachment", clientId?: CommandId | null, itemId: ItemId, turnId: TurnId, attachment: ImageAttachmentRef, } | { "type": "agentMessage", itemId: ItemId, turnId: TurnId, text: string, } | { "type": "reasoning", itemId: ItemId, turnId: TurnId, text: string, state: Array<ReasoningState>, } | { "type": "plan", itemId: ItemId, turnId: TurnId, text: string, } | { "type": "toolCall", itemId: ItemId, turnId: TurnId, toolCallId: ToolCallId, name: ToolName, argumentsJson: string, binding?: ToolCallBinding | null, } | { "type": "toolResult", itemId: ItemId, turnId: TurnId, toolCallId: ToolCallId, text: string, content?: Array<ContentPart> | null, isError: boolean, };
