// Generated by `ash-app-server-protocol generate_protocol`. Do not edit.
export type ToolActivity = { "type": "read", target: string, } | { "type": "search", target: string, } | { "type": "list", target: string, } | { "type": "edit", target: string, } | { "type": "run" };
