// Generated by `ash-app-server-protocol generate_protocol`. Do not edit.
export type TurnChangeCommitStateDto = "partiallyCommitted" | "idle" | "queued" | "committing" | "committed" | "conflict" | "failed";
