// Generated by `ash-app-server-protocol generate_protocol`. Do not edit.
import type { CommandId } from './CommandId.js';
import type { SessionId } from './SessionId.js';
import type { ThreadId } from './ThreadId.js';
import type { TurnChangeSelectionDto } from './TurnChangeSelectionDto.js';

export type TurnChangesPrepareCommitParams = { commandId: CommandId, sessionId: SessionId, threadId: ThreadId, selections: Array<TurnChangeSelectionDto>, message: string, };
