// Generated by `ash-app-server-protocol generate_protocol`. Do not edit.
import type { ThreadGoalStatus } from './ThreadGoalStatus.js';

export type UserGoalChange = { "type": "set", goalId: string, objective?: string | null, status?: ThreadGoalStatus | null, } | { "type": "clear", goalId: string, };
