// Generated by `ash-app-server-protocol generate_protocol`. Do not edit.
import type { ImageAttachmentRef } from './ImageAttachmentRef.js';
import type { InstructionRef } from './InstructionRef.js';
import type { SkillRef } from './SkillRef.js';

export type UserInput = { "type": "text", text: string, } | { "type": "context", name: string, content: string, filePath?: string, } | { "type": "imageAttachment", attachment: ImageAttachmentRef, } | { "type": "image", url: string, } | { "type": "localImage", path: string, } | { "type": "skill", skill: SkillRef, } | { "type": "instruction", reference: InstructionRef, } | { "type": "mention", name: string, path: string, };
