// Generated by `ash-app-server-protocol generate_protocol`. Do not edit.
import type { SlashCommandDefinition } from './types/SlashCommandDefinition.js';

export const PRODUCT_SLASH_COMMANDS = {
  "marketplace": {
    "name": "marketplace",
    "description": "find and install Marketplace packages",
    "argumentMode": "optional",
    "argumentHint": "<query>"
  },
  "plugins": {
    "name": "plugins",
    "description": "manage installed packages and exact versions",
    "argumentMode": "none"
  },
  "skills": {
    "name": "skills",
    "description": "browse and manage skills",
    "argumentMode": "none"
  },
  "lsp": {
    "name": "lsp",
    "description": "manage language servers and find packages",
    "argumentMode": "optional",
    "argumentHint": "<language-id>"
  },
  "permission": {
    "name": "permission",
    "description": "choose permissions for the next Turn",
    "argumentMode": "optional",
    "argumentHint": "<manual|auto|bypassPermissions>"
  },
  "guardian": {
    "name": "guardian",
    "description": "prepare and review project background for Guardian",
    "argumentMode": "optional",
    "argumentHint": "[setup]"
  }
} as const satisfies Readonly<Record<string, SlashCommandDefinition>>;
