// Generated by `ash-app-server-protocol generate_protocol`. Do not edit.
export const APP_SERVER_PROTOCOL_MAJOR = 7 as const;
export const APP_SERVER_PROTOCOL_REVISION = 7 as const;
export const APP_SERVER_CAPABILITY_VERSION = 10 as const;
export const APP_SERVER_SCHEMA_HASH = "sha256:38b780b5377cf6ffb1747bd176d2e6cafaae39bdb7b0a058998e8d141063180b" as const;
export type JsonRpcVersion = "2.0";
export type JsonRpcId = number | string | null;
export type JsonRpcRequest<P> = { jsonrpc: JsonRpcVersion; id: JsonRpcId; method: string; params: P };
export type JsonRpcNotification<P> = { jsonrpc: JsonRpcVersion; method: string; params: P };
export type JsonRpcSuccess<R> = { jsonrpc: JsonRpcVersion; id: JsonRpcId; result: R };
export type JsonRpcFailure<E> = { jsonrpc: JsonRpcVersion; id: JsonRpcId; error: E };
export type JsonRpcResponse<R, E> = JsonRpcSuccess<R> | JsonRpcFailure<E>;
export type JsonRpcError = { code: number; message: string; data: unknown };
