// Generated by `ash-app-server-protocol generate_protocol`. Do not edit.
export const APP_SERVER_PROTOCOL_MAJOR = 7 as const;
export const APP_SERVER_PROTOCOL_REVISION = 13 as const;
export const APP_SERVER_CAPABILITY_VERSION = 16 as const;
export const APP_SERVER_SCHEMA_HASH = "sha256:d5a83c926390f07bcf69e26890d6c3af32676da898239672624f9f7142abb681" as const;
export type JsonRpcVersion = "2.0";
export type JsonRpcId = number | string | null;
export type JsonRpcRequest<P> = { jsonrpc: JsonRpcVersion; id: JsonRpcId; method: string; params: P };
export type JsonRpcNotification<P> = { jsonrpc: JsonRpcVersion; method: string; params: P };
export type JsonRpcSuccess<R> = { jsonrpc: JsonRpcVersion; id: JsonRpcId; result: R };
export type JsonRpcFailure<E> = { jsonrpc: JsonRpcVersion; id: JsonRpcId; error: E };
export type JsonRpcResponse<R, E> = JsonRpcSuccess<R> | JsonRpcFailure<E>;
export type JsonRpcError = { code: number; message: string; data: unknown };
