[package]
name = "ash-attachments"
version.workspace = true
edition.workspace = true
license-file.workspace = true
publish.workspace = true

[lib]
doctest = false
name = "ash_attachments"
path = "src/lib.rs"

[dependencies]
attachment-store = { workspace = true }
audio = { workspace = true }
thiserror = { workspace = true }
url = { workspace = true }
ash-http-client = { workspace = true }
ash-protocol = { workspace = true }
ash-utils-image = { workspace = true }

[dev-dependencies]
tempfile = { workspace = true }
image = { workspace = true, features = ["png"] }

[lints]
workspace = true
