//! Agent operation and host contracts, independent of the Core implementation.

#![deny(private_bounds, private_interfaces, unreachable_pub)]

mod browser;
mod checkpoint;
mod commands;
mod error;
mod hooks;
mod model;
mod observer;
mod policy;
mod runtime;
mod thread;
mod view;
mod worktree;

pub use browser::BrowserAction;
pub use browser::BrowserActionResult;
pub use browser::BrowserCapability;
pub use browser::BrowserError;
pub use browser::BrowserObservation;
pub use browser::BrowserObserveRequest;
pub use browser::BrowserTargetId;
pub use browser::CreateBrowserTargetRequest;
pub use browser::CreateBrowserTargetResult;
pub use browser::ElementTarget;
pub use browser::MediaResource;
pub use browser::TextInputTarget;
pub use checkpoint::CheckpointCapture;
pub use checkpoint::MessageCheckpointSource;
pub use commands::CreateBranchRequest;
pub use commands::ForkThreadRequest;
pub use commands::InterruptTurnRequest;
pub use commands::ReplaceThreadRequest;
pub use commands::ResolveTurnInteractionRequest;
pub use commands::RestoreMessageRequest;
pub use commands::RewindThreadRequest;
pub use commands::SequenceExpectation;
pub use commands::SetGoalRequest;
pub use commands::SetGoalResult;
pub use commands::ShellTurnInvocation;
pub use commands::StartThreadRequest;
pub use commands::SteerTurnRequest;
pub use error::CoreError;
pub use hooks::AfterToolHookRequest;
pub use hooks::BeforeToolHookDecision;
pub use hooks::BeforeToolHookRequest;
pub use hooks::HookExecutionEvent;
pub use hooks::HookExecutionObserver;
pub use hooks::HookOutcome;
pub use hooks::HookService;
pub use hooks::NoHookExecutionObserver;
pub use hooks::TurnCompletedHookRequest;
pub use model::ModelImageInputLimits;
pub use model::ModelImageInputPolicy;
pub use model::ModelSelection;
pub use model::ModelService;
pub use model::ModelStreamSink;
pub use observer::TurnExecutionFinished;
pub use observer::TurnExecutionKind;
pub use observer::TurnExecutionObserver;
pub use observer::TurnExecutionStarted;
pub use observer::TurnExecutionTerminalState;
pub use observer::TurnToolExecutionFinished;
pub use observer::TurnToolExecutionStarted;
pub use policy::ActionPolicyService;
pub use runtime::AcceptedCommand;
pub use runtime::AgentRuntime;
pub use runtime::CompactThreadRequest;
pub use runtime::InteractionLifecycle;
pub use runtime::SubmitShellRequest;
pub use runtime::SubmitTurnRequest;
pub use runtime::SubmittedCommand;
pub use runtime::TurnReceipt;
pub use thread::LeaseGuard;
pub use thread::ThreadUpdateSink;
pub use thread::WriterLease;
pub use view::SessionView;
pub use view::ThreadView;
pub use view::TurnState;
pub use worktree::ThreadWorktreeBinder;
pub use worktree::ThreadWorktreeBindingRequest;
