[package]
name = "ash-slash-commands"
version.workspace = true
edition.workspace = true
license-file.workspace = true
publish.workspace = true

[lib]
doctest = false
name = "ash_slash_commands"
path = "src/lib.rs"

[features]
json-schema = ["dep:schemars"]
export = ["json-schema", "dep:ts-rs"]

[dependencies]
fuzzy-match = { workspace = true }
serde = { workspace = true, features = ["derive"] }
schemars = { workspace = true, optional = true }
ts-rs = { workspace = true, features = ["no-serde-warnings"], optional = true }

[dev-dependencies]
serde_json = { workspace = true }

[lints]
workspace = true
