[package]
name = "ash-call"
version.workspace = true
edition.workspace = true
license-file.workspace = true
publish.workspace = true

[lib]
name = "call"

[dependencies]
serde = { workspace = true }
serde_json = { workspace = true }
rusqlite = { workspace = true }
rand = { workspace = true }
sha2 = { workspace = true }
thiserror = { workspace = true }
ash-secrets = { workspace = true }

[dev-dependencies]
tempfile = { workspace = true }

[lints]
workspace = true
