// Generated by `ash-app-server-protocol generate_protocol`. Do not edit.
import type { AccountRateLimitWindowDto } from './AccountRateLimitWindowDto.js';

export type AccountRateLimitDto = { id: string, name: string | null, model: string | null, allowed: boolean | null, limitReached: boolean | null, primary: AccountRateLimitWindowDto | null, secondary: AccountRateLimitWindowDto | null, };
