// Generated by `ash-app-server-protocol generate_protocol`. Do not edit.
import type { AccountCreditBalanceDto } from './AccountCreditBalanceDto.js';
import type { AccountRateLimitDto } from './AccountRateLimitDto.js';
import type { AccountXaiUsageDto } from './AccountXaiUsageDto.js';

export type AccountRateLimitsReadResult = { provider: string, accountId: string, plan: string | null, limits: Array<AccountRateLimitDto>, credits: AccountCreditBalanceDto | null, xai?: AccountXaiUsageDto | null, };
