// Generated by `ash-app-server-protocol generate_protocol`. Do not edit.
import type { AccountDto } from './AccountDto.js';

export type AccountReadResult = {
/**
 * Decimal text preserves the full Rust revision in JavaScript clients.
 */
revision: string, accounts: Array<AccountDto>, };
