// Generated by `ash-app-server-protocol generate_protocol`. Do not edit.
import type { AgentToolCapabilityDto } from './AgentToolCapabilityDto.js';

export type AgentCapabilitiesReadResult = { tools: Array<AgentToolCapabilityDto>, localProcessSandboxConfigured: boolean, sandboxBackends: Array<string>, directoryGrantsReadable: boolean, };
