// Generated by `ash-app-server-protocol generate_protocol`. Do not edit.
import type { AgentRoleSource } from './AgentRoleSource.js';

export type AgentRoleEntry = { name: string, description: string, source: AgentRoleSource, };
