// Generated by `ash-app-server-protocol generate_protocol`. Do not edit.
import type { ToolAuthorityDto } from './ToolAuthorityDto.js';
import type { ToolExposureDto } from './ToolExposureDto.js';
import type { ToolSourceDto } from './ToolSourceDto.js';
import type { ToolSourceProvenance } from './ToolSourceProvenance.js';

export type AgentToolCapabilityDto = { name: string, description: string, source: ToolSourceDto, sourceChain: Array<ToolSourceProvenance>, exposure: ToolExposureDto, authority: ToolAuthorityDto, };
