// Generated by `ash-app-server-protocol generate_protocol`. Do not edit.
import type { AgentToolCapabilityDto } from './AgentToolCapabilityDto.js';
import type { SandboxDiagnosticDto } from './SandboxDiagnosticDto.js';

export type AgentCapabilitiesReadResult = { tools: Array<AgentToolCapabilityDto>, localProcessSandboxConfigured: boolean, sandboxBackends: Array<string>, sandboxDiagnostics: Array<SandboxDiagnosticDto>, directoryGrantsReadable: boolean, };
