// Generated by `ash-app-server-protocol generate_protocol`. Do not edit.
import type { AgentRoleEntry } from './AgentRoleEntry.js';

export type AgentRoleListResult = { agents: Array<AgentRoleEntry>, };
