// Generated by `ash-app-server-protocol generate_protocol`. Do not edit.
import type { SessionId } from './SessionId.js';
import type { ThreadId } from './ThreadId.js';

export type AppHostOperation = { "type": "openFile", path: string, line: number | null, } | { "type": "openBrowser", url: string, } | { "type": "openTerminal", } | { "type": "openReview", original: string, modified: string, } | { "type": "navigate", sessionId: SessionId, threadId: ThreadId, } | { "type": "listSections", } | { "type": "createSection", name: string, } | { "type": "renameSection", sectionId: string, name: string, } | { "type": "deleteSection", sectionId: string, } | { "type": "moveSession", sessionId: SessionId, sectionId: string | null, } | { "type": "reorderSection", sectionId: string, sessionIds: Array<SessionId>, } | { "type": "checkUpdate", } | { "type": "confetti", };
