// Generated by `ash-app-server-protocol generate_protocol`. Do not edit.
import type { AppHostOperation } from './AppHostOperation.js';
import type { SessionId } from './SessionId.js';
import type { ThreadId } from './ThreadId.js';
import type { TurnId } from './TurnId.js';

export type AppHostRequestParams = { sessionId: SessionId, threadId: ThreadId, turnId: TurnId, operation: AppHostOperation, };
