// Generated by `ash-app-server-protocol generate_protocol`. Do not edit.
import type { ApprovalEnvironmentScope } from './ApprovalEnvironmentScope.js';
import type { ModelRef } from './ModelRef.js';
import type { ScanOptions } from './ScanOptions.js';

export type ApprovalEnvironmentScanParams = { scope: ApprovalEnvironmentScope, operationId: string, options: ScanOptions, model?: ModelRef | null, };
