// Generated by `ash-app-server-protocol generate_protocol`. Do not edit.
import type { ModelRef } from './ModelRef.js';
import type { ReasoningEffort } from './ReasoningEffort.js';

export type ApprovalReviewModelSelection = { "type": "automatic" } | { "type": "explicit", model: ModelRef, connection?: string | null, reasoningEffort?: ReasoningEffort | null, };
