// Generated by `ash-app-server-protocol generate_protocol`. Do not edit.
import type { AssetCatalogEntry } from './AssetCatalogEntry.js';
import type { AssetCollection } from './AssetCollection.js';

export type AssetCatalogResult = { entries: Array<AssetCatalogEntry>, collections: Array<AssetCollection>, };
