// Generated by `ash-app-server-protocol generate_protocol`. Do not edit.
import type { AudioMediaType } from './AudioMediaType.js';
import type { ContentDigest } from './ContentDigest.js';

export type AudioAttachmentRef = { contentDigest: ContentDigest, mediaType: AudioMediaType, encodedBytes: number, durationMs: number, };
