// Generated by `ash-app-server-protocol generate_protocol`. Do not edit.
import type { BackupWorkspaceDto } from './BackupWorkspaceDto.js';

export type BackupWorkspacesResult = { workspaces: Array<BackupWorkspaceDto>, };
