// Generated by `ash-app-server-protocol generate_protocol`. Do not edit.
import type { BackupContentDto } from './BackupContentDto.js';

export type BackupRecordDto = { content: BackupContentDto, revision: string, updatedAt: number, };
