// Generated by `ash-app-server-protocol generate_protocol`. Do not edit.
export type BackupWorkspaceDto = { id: string, folders: Array<string>, configuration: string | null, remoteAuthority: string | null, };
