// Generated by `ash-app-server-protocol generate_protocol`. Do not edit.
import type { BackupContentDto } from './BackupContentDto.js';
import type { BackupWorkspaceDto } from './BackupWorkspaceDto.js';

export type BackupWriteParams = { clientId: string, workspace: BackupWorkspaceDto, content: BackupContentDto, expectedRevision: string | null, };
