// Generated by `ash-app-server-protocol generate_protocol`. Do not edit.
import type { Thread } from './Thread.js';

export type BrowserCreateParams = {
/**
 * The durable Thread owning this request; a transport connection is not an agent identity.
 */
threadId: string, url: string, networkToken?: string, };
