// Generated by `ash-app-server-protocol generate_protocol`. Do not edit.
import type { BrowserPerformActionDto } from './BrowserPerformActionDto.js';

export type BrowserPerformParams = { threadId: string, networkToken?: string, action: BrowserPerformActionDto, };
