// Generated by `ash-app-server-protocol generate_protocol`. Do not edit.
export type BrowserCapability = {
/**
 * Version 3 enforces backend authorization for every network request from an isolated agent page.
 */
version: number, observe: boolean, input: boolean, };
