// Generated by `ash-app-server-protocol generate_protocol`. Do not edit.
export type CallDeployment = { "type": "local" } | { "type": "server", url: string, administrator: string, } | { "type": "invitation", url: string, credential: string, };
