// Generated by `ash-app-server-protocol generate_protocol`. Do not edit.
import type { CallDeployment } from './CallDeployment.js';

export type CallStartParams = { resourceId: string, operationId: string, deviceId: string, deployment: CallDeployment, };
