// Generated by `ash-app-server-protocol generate_protocol`. Do not edit.
import type { ScreenTarget } from './ScreenTarget.js';

export type CallScreenSource = { target: ScreenTarget, title: string, width: number, height: number, };
