// Generated by `ash-app-server-protocol generate_protocol`. Do not edit.
import type { CallMember } from './CallMember.js';
import type { MediaState } from './MediaState.js';

export type CallSnapshot = { id: string, revision: number, mediaEpoch: number, mediaRoom: string, mediaState: MediaState, members: Array<CallMember>, };
