// Generated by `ash-app-server-protocol generate_protocol`. Do not edit.
import type { AgentInteractionCapability } from './AgentInteractionCapability.js';
import type { AppToolsCapability } from './AppToolsCapability.js';
import type { BrowserCapability } from './BrowserCapability.js';
import type { DirPermissionsHostCapability } from './DirPermissionsHostCapability.js';
import type { TextDocumentsCapability } from './TextDocumentsCapability.js';

export type ClientCapabilities = { appTools?: AppToolsCapability | null, notifications?: boolean, agentInteractions?: AgentInteractionCapability | null, browser?: BrowserCapability | null, dirPermissionsHost?: DirPermissionsHostCapability | null, textDocuments?: TextDocumentsCapability | null, };
