// Generated by `ash-app-server-protocol generate_protocol`. Do not edit.
import type { ContentDigest } from './ContentDigest.js';

export type CodeSnapshot = { head: string, tree: string, prerequisite: string | null,
/**
 * Base64 Git pack. Transport size is bounded before decoding.
 */
pack: string, packDigest: ContentDigest, };
