// Generated by `ash-app-server-protocol generate_protocol`. Do not edit.
export type CommandSource = { sessionId: string, threadId: string, turnId: string, sequence: number, recordedAtUnixMs: number, };
