// Generated by `ash-app-server-protocol generate_protocol`. Do not edit.
export type ContextToolDefinition = { name: string, description: string, parameters: unknown, strict: boolean, tokens: number, };
