// Generated by `ash-app-server-protocol generate_protocol`. Do not edit.
export type ContentSearchIndexStats = {
/**
 * Engine diagnostic text; callers must not parse it as a stable query language.
 */
queryPlan: string, rawCandidates: number, candidates: number, totalFiles: number, };
