// Generated by `ash-app-server-protocol generate_protocol`. Do not edit.
import type { DictationModelOperation } from './DictationModelOperation.js';

export type DictationModelStartParams = { resourceId: string, modelId: string, operation: DictationModelOperation, };
