// Generated by `ash-app-server-protocol generate_protocol`. Do not edit.
export type DictationModelStage = { "type": "checking" } | { "type": "downloading", file: string, downloadedBytes: number, } | { "type": "loading" } | { "type": "ready" } | { "type": "cancelled" } | { "type": "failed", error: string, };
