// Generated by `ash-app-server-protocol generate_protocol`. Do not edit.
import type { DictationModelStage } from './DictationModelStage.js';

export type DictationModelProgress = { resourceId: string, modelId: string, stage: DictationModelStage, };
