// Generated by `ash-app-server-protocol generate_protocol`. Do not edit.
import type { EntryKind } from './EntryKind.js';

export type EntryInput = { id: string, kind: EntryKind, title: string, content: string,
/**
 * None creates a user-authored entry. Clients cannot supply source labels or revisions.
 */
sourceId?: string | null, };
