// Generated by `ash-app-server-protocol generate_protocol`. Do not edit.
import type { EnvironmentEntry } from './EnvironmentEntry.js';

export type EnvironmentDraft = { id: string, baseRevision: number, entries: Array<EnvironmentEntry>, };
