// Generated by `ash-app-server-protocol generate_protocol`. Do not edit.
import type { EnvironmentEntry } from './EnvironmentEntry.js';

export type EnvironmentProfile = { revision: number, entries: Array<EnvironmentEntry>,
/**
 * Latest bounded project observations. They never inherit user acceptance or target trust.
 */
observations: Array<EnvironmentEntry>, };
