// Generated by `ash-app-server-protocol generate_protocol`. Do not edit.
import type { ExtensionDiagnostic } from './ExtensionDiagnostic.js';

export type ExtensionDiagnosticEntry = { uri: string, version: number | null, diagnostics: Array<ExtensionDiagnostic>, };
