// Generated by `ash-app-server-protocol generate_protocol`. Do not edit.
import type { ExtensionClientOperation } from './ExtensionClientOperation.js';

export type ExtensionClientRequestParams = { extensionId: string, activationGeneration: number, incarnation: number, operation: ExtensionClientOperation, };
