// Generated by `ash-app-server-protocol generate_protocol`. Do not edit.
import type { ExtensionDocumentSnapshot } from './ExtensionDocumentSnapshot.js';
import type { JsonValue } from './JsonValue.js';

export type ExtensionClientResult = { "result": "command", value: JsonValue, } | { "result": "document", document: ExtensionDocumentSnapshot, } | { "result": "file", text: string, } | { "result": "documents", documents: Array<ExtensionDocumentSnapshot>, } | { "result": "applied", applied: boolean, } | { "result": "configuration", value: JsonValue, } | { "result": "selection", index: number | null, } | { "result": "done" };
