// Generated by `ash-app-server-protocol generate_protocol`. Do not edit.
import type { SessionDirSelector } from './SessionDirSelector.js';

export type FsCopyParams = { sourceDirId?: string, source: string, targetDirId?: string, target: string, sessionDirectory?: SessionDirSelector, };
