// Generated by `ash-app-server-protocol generate_protocol`. Do not edit.
import type { GitAutoFetchModeDto } from './GitAutoFetchModeDto.js';

export type GitConfigDto = { autofetch: GitAutoFetchModeDto, autofetchPeriod: number, };
