// Generated by `ash-app-server-protocol generate_protocol`. Do not edit.
import type { GitCommitStatisticsDto } from './GitCommitStatisticsDto.js';

export type GitCommitDetailsResult = { authorName: string, authorEmail: string, timestampSeconds: number, message: string, statistics: GitCommitStatisticsDto, };
