// Generated by `ash-app-server-protocol generate_protocol`. Do not edit.
import type { GitCommitFileContentDto } from './GitCommitFileContentDto.js';

export type GitConflictFileResult = { stageIds: [string | null, string | null, string | null], resultObjectId: string | null, base: GitCommitFileContentDto, current: GitCommitFileContentDto, incoming: GitCommitFileContentDto, result: GitCommitFileContentDto, };
