// Generated by `ash-app-server-protocol generate_protocol`. Do not edit.
import type { GitCommitChangeDto } from './GitCommitChangeDto.js';

export type GitCompareChangesResult = { baseObjectId: string, changes: Array<GitCommitChangeDto>, };
