// Generated by `ash-app-server-protocol generate_protocol`. Do not edit.
import type { GitCheckIgnoreCancelStatusDto } from './GitCheckIgnoreCancelStatusDto.js';

export type GitCheckIgnoreCancelResult = { status: GitCheckIgnoreCancelStatusDto, };
