// Generated by `ash-app-server-protocol generate_protocol`. Do not edit.
import type { GitHubCheckRun } from './GitHubCheckRun.js';
import type { GitHubCommitStatus } from './GitHubCommitStatus.js';

export type GitHubChecksResult = { state: string, statuses: Array<GitHubCommitStatus>, checks: Array<GitHubCheckRun>, nextPage: number | null, };
