// Generated by `ash-app-server-protocol generate_protocol`. Do not edit.
import type { IssueRepository } from './IssueRepository.js';

export type GitHubNotification = { id: string, title: string, subjectType: string, reason: string, unread: boolean, updatedAt: string, repository: IssueRepository, url: string, };
