// Generated by `ash-app-server-protocol generate_protocol`. Do not edit.
import type { GitHubPullRequestReview } from './GitHubPullRequestReview.js';

export type GitHubPullRequestReviewsResult = { reviews: Array<GitHubPullRequestReview>, nextPage: number | null, };
