// Generated by `ash-app-server-protocol generate_protocol`. Do not edit.
export type GitHubCheckRun = { id: number, name: string, status: string, conclusion: string | null, detailsUrl: string | null, };
