// Generated by `ash-app-server-protocol generate_protocol`. Do not edit.
import type { GitHubAccount } from './GitHubAccount.js';

export type GitHubAccountsResult = { accounts: Array<GitHubAccount>, };
