// Generated by `ash-app-server-protocol generate_protocol`. Do not edit.
import type { IssueRepository } from './IssueRepository.js';

export type GitHubReviewCommentDeleteParams = { operationId: string, accountId?: string, repository: IssueRepository, number: number, commentId: string, };
