// Generated by `ash-app-server-protocol generate_protocol`. Do not edit.
import type { GitHubNotificationFilter } from './GitHubNotificationFilter.js';

export type GitHubNotificationsParams = { operationId: string, accountId: string, filter: GitHubNotificationFilter, page: number, };
