// Generated by `ash-app-server-protocol generate_protocol`. Do not edit.
import type { GitHubPullRequestFile } from './GitHubPullRequestFile.js';

export type GitHubPullRequestFilesResult = { files: Array<GitHubPullRequestFile>, nextPage: number | null, limitReached: boolean, };
