// Generated by `ash-app-server-protocol generate_protocol`. Do not edit.
import type { IssueRepository } from './IssueRepository.js';

export type GitHubReviewThreadsParams = { operationId: string, accountId?: string, repository: IssueRepository, number: number, cursor: string | null, };
