// Generated by `ash-app-server-protocol generate_protocol`. Do not edit.
import type { GitHubPullRequestFilesResult } from './GitHubPullRequestFilesResult.js';

export type GitHubReviewDiffResult = { baseCommit: string, files: GitHubPullRequestFilesResult, };
