// Generated by `ash-app-server-protocol generate_protocol`. Do not edit.
import type { GitHubReviewThreadState } from './GitHubReviewThreadState.js';
import type { IssueRepository } from './IssueRepository.js';

export type GitHubReviewThreadResolveParams = { operationId: string, accountId?: string, repository: IssueRepository, number: number, threadId: string, state: GitHubReviewThreadState, };
