// Generated by `ash-app-server-protocol generate_protocol`. Do not edit.
export type GitHubReviewComment = { id: string, body: string, url: string, author: string | null, canUpdate: boolean, canDelete: boolean, };
