// Generated by `ash-app-server-protocol generate_protocol`. Do not edit.
import type { GitHubPullRequest } from './GitHubPullRequest.js';

export type GitHubPullRequestListResult = { pullRequests: Array<GitHubPullRequest>, nextPage: number | null, };
