// Generated by `ash-app-server-protocol generate_protocol`. Do not edit.
import type { IssueRepository } from './IssueRepository.js';

export type GitHubPullRequestCreateParams = { operationId: string, accountId?: string, repository: IssueRepository, title: string, body: string, head: string, base: string, draft: boolean, };
