// Generated by `ash-app-server-protocol generate_protocol`. Do not edit.
export type GitHubPullRequestFile = { filename: string, status: string, additions: number, deletions: number, changes: number, patch: string | null, previousFilename: string | null, };
