// Generated by `ash-app-server-protocol generate_protocol`. Do not edit.
import type { AccountStatusDto } from './AccountStatusDto.js';

export type GitHubAccount = { id: string, host: string, login: string, status: AccountStatusDto, credentialRevision: string, };
