// Generated by `ash-app-server-protocol generate_protocol`. Do not edit.
import type { IssueRepository } from './IssueRepository.js';

export type GitHubIssueCreateParams = { operationId: string, accountId?: string, repository: IssueRepository, title: string, body: string, labels: Array<string>, assignees: Array<string>, };
