// Generated by `ash-app-server-protocol generate_protocol`. Do not edit.
import type { GitHubReviewerChange } from './GitHubReviewerChange.js';
import type { IssueRepository } from './IssueRepository.js';

export type GitHubReviewersChangeParams = { operationId: string, accountId?: string, repository: IssueRepository, number: number, change: GitHubReviewerChange, users: Array<string>, teams: Array<string>, };
