// Generated by `ash-app-server-protocol generate_protocol`. Do not edit.
import type { GitIndexHunkDto } from './GitIndexHunkDto.js';

export type GitIndexDiffResult = { original: string | null, modified: string | null, hunks: Array<GitIndexHunkDto>, };
