// Generated by `ash-app-server-protocol generate_protocol`. Do not edit.
export type GitIndexHunkDto = { index: number, oldStart: number, oldCount: number, newStart: number, newCount: number, preview: string, };
