// Generated by `ash-app-server-protocol generate_protocol`. Do not edit.
import type { CommandId } from './CommandId.js';
import type { GitWorktreeDeleteMode } from './GitWorktreeDeleteMode.js';

export type GitWorktreeDeleteParams = { commandId: CommandId, repositoryId?: string, checkoutRoot: string, mode: GitWorktreeDeleteMode, };
