// Generated by `ash-app-server-protocol generate_protocol`. Do not edit.
import type { GitWorktreeStateDto } from './GitWorktreeStateDto.js';

export type GitWorktreeDto = { checkoutRoot: string, path: string, branch: string | null, head: string, current: boolean, state: GitWorktreeStateDto, };
