// Generated by `ash-app-server-protocol generate_protocol`. Do not edit.
import type { GitWorktreeDto } from './GitWorktreeDto.js';

export type GitWorktreeListResult = { worktrees: Array<GitWorktreeDto>, };
