// Generated by `ash-app-server-protocol generate_protocol`. Do not edit.
export type HistoryScanOptions = { sessions: number, commandsPerSession: number,
/**
 * None selects by recency without excluding infrequently used projects by age.
 */
days: number | null, };
