// Generated by `ash-app-server-protocol generate_protocol`. Do not edit.
import type { InstructionImportItem } from './InstructionImportItem.js';

export type InstructionImportResult = { items: Array<InstructionImportItem>, };
