// Generated by `ash-app-server-protocol generate_protocol`. Do not edit.
import type { InstructionDiagnosticDto } from './InstructionDiagnosticDto.js';
import type { InstructionDto } from './InstructionDto.js';

export type InstructionListResult = { instructions: Array<InstructionDto>, diagnostics: Array<InstructionDiagnosticDto>, };
