// Generated by `ash-app-server-protocol generate_protocol`. Do not edit.
import type { IssueReporterIssue } from './IssueReporterIssue.js';

export type IssueReporterSearchResult = { issues: Array<IssueReporterIssue>, };
