// Generated by `ash-app-server-protocol generate_protocol`. Do not edit.
import type { LanguageServerDescriptorDto } from './LanguageServerDescriptorDto.js';

export type LanguageServersResult = { servers: Array<LanguageServerDescriptorDto>, };
