// Generated by `ash-app-server-protocol generate_protocol`. Do not edit.
import type { MarketplaceEditorExtensionPolicyDto } from './MarketplaceEditorExtensionPolicyDto.js';

export type MarketplaceEditorExtensionsResult = { revision: number, extensions: Array<MarketplaceEditorExtensionPolicyDto>, };
