// Generated by `ash-app-server-protocol generate_protocol`. Do not edit.
import type { MarketplaceEditorExtensionPolicyActionDto } from './MarketplaceEditorExtensionPolicyActionDto.js';

export type MarketplaceEditorExtensionPolicyParams = { installationId: string, packageDigest: string, expectedRevision: number, action: MarketplaceEditorExtensionPolicyActionDto, };
