// Generated by `ash-app-server-protocol generate_protocol`. Do not edit.
import type { McpServerRuntimeStateDto } from './McpServerRuntimeStateDto.js';

export type McpServerStatusDto = { id: string, displayName: string,
/**
 * Scheme, host, and port only; absent for stdio servers.
 */
httpOrigin: string | null, state: McpServerRuntimeStateDto, catalogGeneration: number, connectionGeneration: number | null, toolCount: number, };
