// Generated by `ash-app-server-protocol generate_protocol`. Do not edit.
export type ModelContextConfigDto = { contextWindow?: number | null,
/**
 * Select the model default (false) or its current connection maximum (true).
 */
longContext?: boolean | null, autoCompactTokenLimit?: number | null, };
