// Generated by `ash-app-server-protocol generate_protocol`. Do not edit.
import type { CommandId } from './CommandId.js';
import type { ModelRef } from './ModelRef.js';

export type ModelPreferencesUpdateParams = { command_id: CommandId, expected_revision: number, model: ModelRef, acceleration?: string | null, long_context?: boolean | null, };
