// Generated by `ash-app-server-protocol generate_protocol`. Do not edit.
import type { CapabilitySupport } from './CapabilitySupport.js';
import type { ModelSettings } from './ModelSettings.js';

export type ModelCapabilities = { tools: CapabilitySupport, reasoning: CapabilitySupport, parallel_tool_calls: CapabilitySupport, personality: CapabilitySupport, image_detail_original: CapabilitySupport,
/**
 * Whether acceleration is supported; [`crate::ModelSettings::acceleration`] declares its mechanism.
 */
fast_mode: CapabilitySupport, };
