// Generated by `ash-app-server-protocol generate_protocol`. Do not edit.
import type { ModelAccelerationOption } from './ModelAccelerationOption.js';
import type { ModelCapabilities } from './ModelCapabilities.js';
import type { ModelReasoningEffortOption } from './ModelReasoningEffortOption.js';
import type { ModelRef } from './ModelRef.js';
import type { ModelRetirement } from './ModelRetirement.js';
import type { ModelSettings } from './ModelSettings.js';
import type { Personality } from './Personality.js';
import type { ReasoningEffort } from './ReasoningEffort.js';

export type ModelCatalogEntry = { model: ModelRef, display_name: string, description: string | null,
/**
 * Retirement evidence for this catalog row, without inferring availability from its date.
 */
retirement?: ModelRetirement | null,
/**
 * True only when this ID belongs to the last successful endpoint observation.
 */
discovered?: boolean | null, context_window: number | null,
/**
 * Context budget without a per-model preference, distinct from the effective budget and ceiling.
 */
default_context_window: number | null,
/**
 * Long context selection on the active connection; null means no larger budget is available.
 */
long_context: boolean | null,
/**
 * Current preference on the active connection; capability support is reported separately.
 */
selected_acceleration: string | null,
/**
 * Effective choices after connection restrictions and per-option denials.
 */
acceleration_options: Array<ModelAccelerationOption>,
/**
 * Model or custom connection ceiling before applying its context budget preference.
 */
maximum_context_window: number | null, auto_compact_token_limit: number | null, available_context_window?: number | null, capabilities: ModelCapabilities, supported_reasoning_efforts: Array<ModelReasoningEffortOption>,
/**
 * Catalog default, used when no reasoning effort is selected for the invocation.
 */
default_reasoning_effort: ReasoningEffort | null, default_personality: Personality | null, settings: ModelSettings, };
