// Generated by `ash-app-server-protocol generate_protocol`. Do not edit.
import type { ReasoningEffort } from './ReasoningEffort.js';

export type ModelReasoningEffortOption = { effort: ReasoningEffort, description: string | null, };
