// Generated by `ash-app-server-protocol generate_protocol`. Do not edit.
import type { ModelContextCategory } from './ModelContextCategory.js';
import type { ModelContextSourceUsage } from './ModelContextSourceUsage.js';

export type ModelContextCategoryUsage = { category: ModelContextCategory, tokens: number, sources: Array<ModelContextSourceUsage>, };
