// Generated by `ash-app-server-protocol generate_protocol`. Do not edit.
import type { CollaborationMode } from './CollaborationMode.js';
import type { InstructionText } from './InstructionText.js';
import type { ToolName } from './ToolName.js';

export type ModelInstructionMessages = { tools: { [key in ToolName]: InstructionText }, collaborationModes: { [key in CollaborationMode]?: InstructionText }, root: InstructionText | null, subagent: InstructionText | null, };
