// Generated by `ash-app-server-protocol generate_protocol`. Do not edit.
export type NetworkRouteDto = { "type": "direct" } | { "type": "proxy", host: string, port: number, } | { "type": "blocked" };
