// Generated by `ash-app-server-protocol generate_protocol`. Do not edit.
export type NetworkFailureDto = "dns" | "proxy" | "tls" | "certificateConfiguration" | "connect" | "timeout" | "policy" | "configuration" | "request" | "authentication" | "accountChanged" | "accountOperation";
