// Generated by `ash-app-server-protocol generate_protocol`. Do not edit.
import type { HttpCompatibilityModeDto } from './HttpCompatibilityModeDto.js';
import type { NetworkTargetDto } from './NetworkTargetDto.js';

export type NetworkReadResult = { revision: number, httpMode: HttpCompatibilityModeDto, targets: Array<NetworkTargetDto>, };
