// Generated by `ash-app-server-protocol generate_protocol`. Do not edit.
import type { NetworkPurposeDto } from './NetworkPurposeDto.js';
import type { NetworkRouteDto } from './NetworkRouteDto.js';

export type NetworkTargetDto = { id: string, connection: string, displayName: string, host: string, port: number, purpose: NetworkPurposeDto, route: NetworkRouteDto, };
