// Generated by `ash-app-server-protocol generate_protocol`. Do not edit.
import type { DirId } from './DirId.js';
import type { EnvId } from './EnvId.js';
import type { PathUri } from './PathUri.js';

export type ProjectRootDto = { environmentId: EnvId, dirId: DirId,
/**
 * Absolute file location in the root's environment; this does not grant access.
 */
path: PathUri, name: string, purpose: string, };
