// Generated by `ash-app-server-protocol generate_protocol`. Do not edit.
import type { ProviderApiKeyDto } from './ProviderApiKeyDto.js';

export type ProviderApiKeySetParams = { connection: string, apiKey: ProviderApiKeyDto, };
