// Generated by `ash-app-server-protocol generate_protocol`. Do not edit.
import type { ProviderModelsListResult } from './ProviderModelsListResult.js';

export type ProviderModelsUpdated = { connection: string, accountId: string, organization: string | null, plan: string | null, result: ProviderModelsListResult, };
