// Generated by `ash-app-server-protocol generate_protocol`. Do not edit.
export type SandboxReadinessDto = { "type": "ready" } | { "type": "unsupported", reason: string, } | { "type": "unavailable", reason: string, };
