// Generated by `ash-app-server-protocol generate_protocol`. Do not edit.
import type { SandboxNetworkModeDto } from './SandboxNetworkModeDto.js';
import type { SandboxReadinessDto } from './SandboxReadinessDto.js';

export type SandboxDiagnosticDto = { backend: string, network: SandboxNetworkModeDto, readiness: SandboxReadinessDto, };
