// Generated by `ash-app-server-protocol generate_protocol`. Do not edit.
import type { HistoryScanOptions } from './HistoryScanOptions.js';

export type ScanOptions = { recentCommands: boolean, shellHistory: boolean, otherRepositories: boolean, summarizeWithModel: boolean, history: HistoryScanOptions, };
