// Generated by `ash-app-server-protocol generate_protocol`. Do not edit.
import type { SyntaxLanguageDto } from './SyntaxLanguageDto.js';

export type SyntaxOpenParams = { documentId: string, language: SyntaxLanguageDto, revision: number, text: string, };
