// Generated by `ash-app-server-protocol generate_protocol`. Do not edit.
import type { SyntaxEditDto } from './SyntaxEditDto.js';

export type SyntaxUpdateParams = { documentId: string, previousRevision: number, revision: number, edits: Array<SyntaxEditDto>, };
