// Generated by `ash-app-server-protocol generate_protocol`. Do not edit.
import type { ContentDigest } from './ContentDigest.js';
import type { SessionId } from './SessionId.js';
import type { SourceTask } from './SourceTask.js';
import type { ThreadId } from './ThreadId.js';

export type TaskReceipt = { deliveryId: ContentDigest, source: SourceTask, sessionId: SessionId, threadId: ThreadId, directory: string, head: string, tree: string, };
