// Generated by `ash-app-server-protocol generate_protocol`. Do not edit.
import type { CommandId } from './CommandId.js';
import type { SessionId } from './SessionId.js';
import type { TeamId } from './TeamId.js';
import type { TeamRunId } from './TeamRunId.js';
import type { ThreadId } from './ThreadId.js';

export type TeamRunAttachParams = { commandId: CommandId, runId: TeamRunId, teamId: TeamId, expectedTeamRevision: number, sessionId: SessionId, coordinatorThreadId: ThreadId, objective: string, };
