// Generated by `ash-app-server-protocol generate_protocol`. Do not edit.
import type { AgentId } from './AgentId.js';
import type { AgentMessageId } from './AgentMessageId.js';
import type { TeamId } from './TeamId.js';
import type { TeamRunId } from './TeamRunId.js';

export type TeamMessagePostParams = { messageId: AgentMessageId, teamId: TeamId, runId: TeamRunId | null, senderId: AgentId, receiverId: AgentId | null, text: string, };
