// Generated by `ash-app-server-protocol generate_protocol`. Do not edit.
import type { AgentId } from './AgentId.js';
import type { TeamId } from './TeamId.js';
import type { TeamMemberDto } from './TeamMemberDto.js';
import type { TeamStatusDto } from './TeamStatusDto.js';

export type TeamDto = { teamId: TeamId, revision: number, status: TeamStatusDto, name: string, description: string, coordinatorId: AgentId, members: Array<TeamMemberDto>, };
