// Generated by `ash-app-server-protocol generate_protocol`. Do not edit.
import type { CommandId } from './CommandId.js';
import type { TeamId } from './TeamId.js';
import type { TeamRunId } from './TeamRunId.js';

export type TeamRunStartParams = { commandId: CommandId, runId: TeamRunId, teamId: TeamId, expectedTeamRevision: number, objective: string, };
