// Generated by `ash-app-server-protocol generate_protocol`. Do not edit.
import type { TeamRunDto } from './TeamRunDto.js';

export type TeamRunStartResult = { run: TeamRunDto, replayed: boolean, };
