// Generated by `ash-app-server-protocol generate_protocol`. Do not edit.
import type { TeamMessageDto } from './TeamMessageDto.js';

export type TeamMessagePostResult = { message: TeamMessageDto, };
