// Generated by `ash-app-server-protocol generate_protocol`. Do not edit.
import type { AgentId } from './AgentId.js';
import type { AgentRoleSelection } from './AgentRoleSelection.js';

export type TeamMemberDto = { agentId: AgentId, name: string, responsibility: string, role: AgentRoleSelection, };
