// Generated by `ash-app-server-protocol generate_protocol`. Do not edit.
import type { AgentId } from './AgentId.js';
import type { TeamMemberDto } from './TeamMemberDto.js';

export type TeamCommandDto = { "type": "create", name: string, description: string, coordinatorId: AgentId, members: Array<TeamMemberDto>, } | { "type": "updateDetails", name: string, description: string, } | { "type": "addMember", member: TeamMemberDto, } | { "type": "updateMember", member: TeamMemberDto, } | { "type": "removeMember", agentId: AgentId, } | { "type": "setCoordinator", agentId: AgentId, } | { "type": "archive" } | { "type": "restore" };
