// Generated by `ash-app-server-protocol generate_protocol`. Do not edit.
import type { TerminalSignal } from './TerminalSignal.js';

export type TerminalSendSignalParams = { dirId?: string, terminalId: string, signal: TerminalSignal, };
