// Generated by `ash-app-server-protocol generate_protocol`. Do not edit.
import type { TerminalProcessReady } from './TerminalProcessReady.js';
import type { TerminalProfile } from './TerminalProfile.js';
import type { TerminalReconnectLease } from './TerminalReconnectLease.js';

export type TerminalCreateResult = { ready: TerminalProcessReady, terminalId: string, profile: TerminalProfile, reconnect: TerminalReconnectLease | null, };
