// Generated by `ash-app-server-protocol generate_protocol`. Do not edit.
export type TestingDebugLaunch = { testId: string, program: string, arguments: Array<string>, directory: string, adapterProgram: string, };
