// Generated by `ash-app-server-protocol generate_protocol`. Do not edit.
import type { TestingDebugLaunch } from './TestingDebugLaunch.js';
import type { TestingItem } from './TestingItem.js';
import type { TestingOperationStatus } from './TestingOperationStatus.js';
import type { TestingResult } from './TestingResult.js';

export type TestingUpdate = { operationId: string, sequence: number, status: TestingOperationStatus, tests: Array<TestingItem> | null, result: TestingResult | null, error: string | null, launch: TestingDebugLaunch | null, };
