// Generated by `ash-app-server-protocol generate_protocol`. Do not edit.
import type { TextDocumentTurnOutcome } from './TextDocumentTurnOutcome.js';
import type { ThreadId } from './ThreadId.js';
import type { TurnId } from './TurnId.js';

export type TextDocumentTurnFinished = { threadId: ThreadId, turnId: TurnId, outcome: TextDocumentTurnOutcome, };
