// Generated by `ash-app-server-protocol generate_protocol`. Do not edit.
export type TextDocumentChangeDto = { "kind": "create", path: string, text: string, } | { "kind": "update", snapshot: string, text: string, } | { "kind": "delete", snapshot: string, } | { "kind": "move", snapshot: string, target: string, text: string, };
