// Generated by `ash-app-server-protocol generate_protocol`. Do not edit.
export type TextDocumentApplyResult = { "kind": "applied" } | { "kind": "conflict" } | { "kind": "cancelled" } | { "kind": "failed", message: string, } | { "kind": "outcomeUnknown", message: string, };
