// Generated by `ash-app-server-protocol generate_protocol`. Do not edit.
export type TextDocumentReadResult = { "kind": "document", snapshot: string, text: string, } | { "kind": "notFound" } | { "kind": "failed", message: string, };
