// Generated by `ash-app-server-protocol generate_protocol`. Do not edit.
export type TextDocumentContentDto = {
/**
 * Path relative to the requested root, using forward slashes. The root's
 * filesystem identity belongs to the server, not the editor's URI spelling.
 */
relativePath: string, text: string, };
