// Generated by `ash-app-server-protocol generate_protocol`. Do not edit.
export type ToolAuthorityDto = "directoryRead" | "directoryWrite" | "processExecution" | "productService" | "providerDefined";
