// Generated by `ash-app-server-protocol generate_protocol`. Do not edit.
import type { ToolActivity } from './ToolActivity.js';
import type { ToolCallCaller } from './ToolCallCaller.js';
import type { ToolSourceProvenance } from './ToolSourceProvenance.js';

export type ToolCallBinding = { registryIncarnation?: string | null, registryGeneration: number, definitionDigest: string, sourceChain: Array<ToolSourceProvenance>, activity?: ToolActivity | null, caller: ToolCallCaller, };
