// Generated by `ash-app-server-protocol generate_protocol`. Do not edit.
import type { ChangeSetId } from './ChangeSetId.js';

export type TurnChangeSelectionDto = { changeSetId: ChangeSetId, expectedRevision: number, paths: Array<string>, };
