// Generated by `ash-app-server-protocol generate_protocol`. Do not edit.
import type { TurnChangeFileDto } from './TurnChangeFileDto.js';

export type TurnChangesPrepareCommitResult = { commitId: string, targetBranch: string, message: string, files: Array<TurnChangeFileDto>, warnings: Array<string>, };
