// Generated by `ash-app-server-protocol generate_protocol`. Do not edit.
import type { SessionId } from './SessionId.js';
import type { ThreadId } from './ThreadId.js';

export type TurnChangesReadCommitFileParams = { sessionId: SessionId, threadId: ThreadId, commitId: string, path: string, };
