load("//:defs.bzl", "ash_rust_binary", "ash_rust_crate")

ash_rust_crate(
    name = "voice-host",
    crate_name = "voice_host",
)

ash_rust_crate(
    name = "voice-host-enabled",
    crate_name = "voice_host",
    crate_features = ["host"],
    extra_deps = [
        "//crates/process-hardening:process-hardening",
        "//crates/package-store:package-store",
        "@crates//:cpal",
        "@crates//:crossbeam-queue",
        "@crates//:rubato",
        "@crates//:sonora",
    ],
)

ash_rust_binary(
    name = "ash-voice-host",
    crate_name = "ash_voice_host",
    crate_root = "src/main.rs",
    deps = [":voice-host-enabled", "//crates/process-hardening:process-hardening", "//crates/package-store:package-store"],
    extra_aliases = {"//crates/process-hardening": "process_hardening"},
)
