[package]
name = "ash-realtime-webrtc"
version.workspace = true
edition.workspace = true
license-file.workspace = true
publish.workspace = true

[lib]
name = "realtime_webrtc"

[lints]
workspace = true

[dependencies]
webrtc = { workspace = true }
rtc = { workspace = true }
opus = { workspace = true }
rand = { workspace = true }
futures = { workspace = true }
tokio = { workspace = true, features = ["rt", "sync", "time", "macros"] }
thiserror = { workspace = true }

[dev-dependencies]
tokio = { workspace = true, features = ["rt-multi-thread"] }
