// Generated from resources/icons by build/resources/icons/generate-to-rs.ts.
// Do not edit this file directly.

use crate::Icon;
use crate::IconDefinition;
use crate::IconId;

#[rustfmt::skip]
mod artwork {
    use super::IconDefinition;
    pub(crate) const ACCOUNT: IconDefinition = IconDefinition::symbolic(include_bytes!("../../../resources/icons/account.svg"));
    pub(crate) const ADD: IconDefinition = IconDefinition::symbolic(include_bytes!("../../../resources/icons/add.svg"));
    pub(crate) const ADD_SMALL: IconDefinition = IconDefinition::symbolic(include_bytes!("../../../resources/icons/add-small.svg"));
    pub(crate) const AGENT: IconDefinition = IconDefinition::symbolic(include_bytes!("../../../resources/icons/agent.svg"));
    pub(crate) const AGENT_FILLED: IconDefinition = IconDefinition::symbolic(include_bytes!("../../../resources/icons/agent-filled.svg"));
    pub(crate) const ALIGN_CENTER: IconDefinition = IconDefinition::symbolic(include_bytes!("../../../resources/icons/align-center.svg"));
    pub(crate) const ALIGN_JUSTIFIED: IconDefinition = IconDefinition::symbolic(include_bytes!("../../../resources/icons/align-justified.svg"));
    pub(crate) const ALIGN_LEFT: IconDefinition = IconDefinition::symbolic(include_bytes!("../../../resources/icons/align-left.svg"));
    pub(crate) const ALIGN_RIGHT: IconDefinition = IconDefinition::symbolic(include_bytes!("../../../resources/icons/align-right.svg"));
    pub(crate) const APPEARANCE: IconDefinition = IconDefinition::symbolic(include_bytes!("../../../resources/icons/appearance.svg"));
    pub(crate) const ARCHIVE: IconDefinition = IconDefinition::symbolic(include_bytes!("../../../resources/icons/archive.svg"));
    pub(crate) const ARROW_DOWN: IconDefinition = IconDefinition::symbolic(include_bytes!("../../../resources/icons/arrow-down.svg"));
    pub(crate) const ARROW_LEFT: IconDefinition = IconDefinition::symbolic(include_bytes!("../../../resources/icons/arrow-left.svg"));
    pub(crate) const ARROW_RIGHT: IconDefinition = IconDefinition::symbolic(include_bytes!("../../../resources/icons/arrow-right.svg"));
    pub(crate) const ARROW_UP: IconDefinition = IconDefinition::symbolic(include_bytes!("../../../resources/icons/arrow-up.svg"));
    pub(crate) const ASK: IconDefinition = IconDefinition::symbolic(include_bytes!("../../../resources/icons/ask.svg"));
    pub(crate) const BELL: IconDefinition = IconDefinition::symbolic(include_bytes!("../../../resources/icons/bell.svg"));
    pub(crate) const BELL_DOT: IconDefinition = IconDefinition::multicolor(include_bytes!("../../../resources/icons/bell-dot.svg"));
    pub(crate) const BELL_SLASH: IconDefinition = IconDefinition::symbolic(include_bytes!("../../../resources/icons/bell-slash.svg"));
    pub(crate) const BOLD: IconDefinition = IconDefinition::symbolic(include_bytes!("../../../resources/icons/bold.svg"));
    pub(crate) const BOOK: IconDefinition = IconDefinition::symbolic(include_bytes!("../../../resources/icons/book.svg"));
    pub(crate) const BOOKS: IconDefinition = IconDefinition::symbolic(include_bytes!("../../../resources/icons/books.svg"));
    pub(crate) const BRIEFCASE: IconDefinition = IconDefinition::symbolic(include_bytes!("../../../resources/icons/briefcase.svg"));
    pub(crate) const BRIEFCASE_FILLED: IconDefinition = IconDefinition::symbolic(include_bytes!("../../../resources/icons/briefcase-filled.svg"));
    pub(crate) const BROWSER_EXPLORE: IconDefinition = IconDefinition::symbolic(include_bytes!("../../../resources/icons/browser-explore.svg"));
    pub(crate) const BROWSER_WEB: IconDefinition = IconDefinition::symbolic(include_bytes!("../../../resources/icons/browser-web.svg"));
    pub(crate) const CALENDAR: IconDefinition = IconDefinition::symbolic(include_bytes!("../../../resources/icons/calendar.svg"));
    pub(crate) const CHART: IconDefinition = IconDefinition::symbolic(include_bytes!("../../../resources/icons/chart.svg"));
    pub(crate) const CHAT_1: IconDefinition = IconDefinition::symbolic(include_bytes!("../../../resources/icons/chat-1.svg"));
    pub(crate) const CHAT_1_FILLED: IconDefinition = IconDefinition::symbolic(include_bytes!("../../../resources/icons/chat-1-filled.svg"));
    pub(crate) const CHAT_2: IconDefinition = IconDefinition::symbolic(include_bytes!("../../../resources/icons/chat-2.svg"));
    pub(crate) const CHAT_2_FILLED: IconDefinition = IconDefinition::symbolic(include_bytes!("../../../resources/icons/chat-2-filled.svg"));
    pub(crate) const CHAT_3: IconDefinition = IconDefinition::symbolic(include_bytes!("../../../resources/icons/chat-3.svg"));
    pub(crate) const CHAT_3_FILLED: IconDefinition = IconDefinition::symbolic(include_bytes!("../../../resources/icons/chat-3-filled.svg"));
    pub(crate) const CHAT_4: IconDefinition = IconDefinition::symbolic(include_bytes!("../../../resources/icons/chat-4.svg"));
    pub(crate) const CHAT_4_FILLED: IconDefinition = IconDefinition::symbolic(include_bytes!("../../../resources/icons/chat-4-filled.svg"));
    pub(crate) const CHECK: IconDefinition = IconDefinition::symbolic(include_bytes!("../../../resources/icons/check.svg"));
    pub(crate) const CHEVRON_DOWN: IconDefinition = IconDefinition::symbolic(include_bytes!("../../../resources/icons/chevron-down.svg"));
    pub(crate) const CHEVRON_LEFT: IconDefinition = IconDefinition::symbolic(include_bytes!("../../../resources/icons/chevron-left.svg"));
    pub(crate) const CHEVRON_RIGHT: IconDefinition = IconDefinition::symbolic(include_bytes!("../../../resources/icons/chevron-right.svg"));
    pub(crate) const CHEVRON_UP: IconDefinition = IconDefinition::symbolic(include_bytes!("../../../resources/icons/chevron-up.svg"));
    pub(crate) const CIRCLE_LARGE: IconDefinition = IconDefinition::symbolic(include_bytes!("../../../resources/icons/circle-large.svg"));
    pub(crate) const CIRCLE_LARGE_FILLED: IconDefinition = IconDefinition::symbolic(include_bytes!("../../../resources/icons/circle-large-filled.svg"));
    pub(crate) const CIRCLE_SMALL: IconDefinition = IconDefinition::symbolic(include_bytes!("../../../resources/icons/circle-small.svg"));
    pub(crate) const CIRCLE_SMALL_FILLED: IconDefinition = IconDefinition::symbolic(include_bytes!("../../../resources/icons/circle-small-filled.svg"));
    pub(crate) const CLAUDE: IconDefinition = IconDefinition::multicolor(include_bytes!("../../../resources/icons/claude.svg"));
    pub(crate) const CLOSE: IconDefinition = IconDefinition::symbolic(include_bytes!("../../../resources/icons/close.svg"));
    pub(crate) const CLOUD: IconDefinition = IconDefinition::symbolic(include_bytes!("../../../resources/icons/cloud.svg"));
    pub(crate) const CODE: IconDefinition = IconDefinition::symbolic(include_bytes!("../../../resources/icons/code.svg"));
    pub(crate) const CODE_REVIEW: IconDefinition = IconDefinition::symbolic(include_bytes!("../../../resources/icons/code-review.svg"));
    pub(crate) const COLAB: IconDefinition = IconDefinition::symbolic(include_bytes!("../../../resources/icons/colab.svg"));
    pub(crate) const COLAB_FILLED: IconDefinition = IconDefinition::symbolic(include_bytes!("../../../resources/icons/colab-filled.svg"));
    pub(crate) const COMMAND: IconDefinition = IconDefinition::symbolic(include_bytes!("../../../resources/icons/command.svg"));
    pub(crate) const CONNECTORS: IconDefinition = IconDefinition::symbolic(include_bytes!("../../../resources/icons/connectors.svg"));
    pub(crate) const COPY: IconDefinition = IconDefinition::symbolic(include_bytes!("../../../resources/icons/copy.svg"));
    pub(crate) const COPY_CODE: IconDefinition = IconDefinition::symbolic(include_bytes!("../../../resources/icons/copy-code.svg"));
    pub(crate) const COWORK: IconDefinition = IconDefinition::symbolic(include_bytes!("../../../resources/icons/cowork.svg"));
    pub(crate) const CSV: IconDefinition = IconDefinition::symbolic(include_bytes!("../../../resources/icons/csv.svg"));
    pub(crate) const CSV_FILLED: IconDefinition = IconDefinition::symbolic(include_bytes!("../../../resources/icons/csv-filled.svg"));
    pub(crate) const CSV_GREEN: IconDefinition = IconDefinition::multicolor(include_bytes!("../../../resources/icons/csv-green.svg"));
    pub(crate) const CSV_LETTER: IconDefinition = IconDefinition::symbolic(include_bytes!("../../../resources/icons/csv-letter.svg"));
    pub(crate) const CSV_LETTER_FILLED: IconDefinition = IconDefinition::symbolic(include_bytes!("../../../resources/icons/csv-letter-filled.svg"));
    pub(crate) const CURSOR: IconDefinition = IconDefinition::symbolic(include_bytes!("../../../resources/icons/cursor.svg"));
    pub(crate) const CURSOR_2: IconDefinition = IconDefinition::symbolic(include_bytes!("../../../resources/icons/cursor-2.svg"));
    pub(crate) const CURSOR_FILLED: IconDefinition = IconDefinition::symbolic(include_bytes!("../../../resources/icons/cursor-filled.svg"));
    pub(crate) const DATABASE: IconDefinition = IconDefinition::symbolic(include_bytes!("../../../resources/icons/database.svg"));
    pub(crate) const DATABASE_FLAT: IconDefinition = IconDefinition::symbolic(include_bytes!("../../../resources/icons/database-flat.svg"));
    pub(crate) const DEBUG: IconDefinition = IconDefinition::symbolic(include_bytes!("../../../resources/icons/debug.svg"));
    pub(crate) const DEBUG_ALT: IconDefinition = IconDefinition::symbolic(include_bytes!("../../../resources/icons/debug-alt.svg"));
    pub(crate) const DESIGN: IconDefinition = IconDefinition::symbolic(include_bytes!("../../../resources/icons/design.svg"));
    pub(crate) const DEVICE_MOBILE: IconDefinition = IconDefinition::symbolic(include_bytes!("../../../resources/icons/device-mobile.svg"));
    pub(crate) const DIAGNOSTICS: IconDefinition = IconDefinition::symbolic(include_bytes!("../../../resources/icons/diagnostics.svg"));
    pub(crate) const DIFF: IconDefinition = IconDefinition::symbolic(include_bytes!("../../../resources/icons/diff.svg"));
    pub(crate) const DIFF_MULTIPLE_1: IconDefinition = IconDefinition::symbolic(include_bytes!("../../../resources/icons/diff-multiple-1.svg"));
    pub(crate) const DIFF_MULTIPLE_2: IconDefinition = IconDefinition::symbolic(include_bytes!("../../../resources/icons/diff-multiple-2.svg"));
    pub(crate) const DISCARD: IconDefinition = IconDefinition::symbolic(include_bytes!("../../../resources/icons/discard.svg"));
    pub(crate) const DOCX: IconDefinition = IconDefinition::symbolic(include_bytes!("../../../resources/icons/docx.svg"));
    pub(crate) const DOCX_BLUE: IconDefinition = IconDefinition::multicolor(include_bytes!("../../../resources/icons/docx-blue.svg"));
    pub(crate) const DOCX_FILLED: IconDefinition = IconDefinition::symbolic(include_bytes!("../../../resources/icons/docx-filled.svg"));
    pub(crate) const DOWNLOAD: IconDefinition = IconDefinition::symbolic(include_bytes!("../../../resources/icons/download.svg"));
    pub(crate) const DOWNLOAD_BOX: IconDefinition = IconDefinition::symbolic(include_bytes!("../../../resources/icons/download-box.svg"));
    pub(crate) const DOWNLOAD_TRAY: IconDefinition = IconDefinition::symbolic(include_bytes!("../../../resources/icons/download-tray.svg"));
    pub(crate) const EDIT: IconDefinition = IconDefinition::symbolic(include_bytes!("../../../resources/icons/edit.svg"));
    pub(crate) const EDIT_1: IconDefinition = IconDefinition::symbolic(include_bytes!("../../../resources/icons/edit-1.svg"));
    pub(crate) const EDIT_2: IconDefinition = IconDefinition::symbolic(include_bytes!("../../../resources/icons/edit-2.svg"));
    pub(crate) const EDIT_WRITE: IconDefinition = IconDefinition::symbolic(include_bytes!("../../../resources/icons/edit-write.svg"));
    pub(crate) const ELLIPSIS: IconDefinition = IconDefinition::symbolic(include_bytes!("../../../resources/icons/ellipsis.svg"));
    pub(crate) const ENTER: IconDefinition = IconDefinition::symbolic(include_bytes!("../../../resources/icons/enter.svg"));
    pub(crate) const ERASER: IconDefinition = IconDefinition::symbolic(include_bytes!("../../../resources/icons/eraser.svg"));
    pub(crate) const ERROR: IconDefinition = IconDefinition::symbolic(include_bytes!("../../../resources/icons/error.svg"));
    pub(crate) const EXPORT: IconDefinition = IconDefinition::symbolic(include_bytes!("../../../resources/icons/export.svg"));
    pub(crate) const EXPORT_TRAY: IconDefinition = IconDefinition::symbolic(include_bytes!("../../../resources/icons/export-tray.svg"));
    pub(crate) const EXTENSIONS: IconDefinition = IconDefinition::symbolic(include_bytes!("../../../resources/icons/extensions.svg"));
    pub(crate) const EYE: IconDefinition = IconDefinition::symbolic(include_bytes!("../../../resources/icons/eye.svg"));
    pub(crate) const EYE_FILLED: IconDefinition = IconDefinition::symbolic(include_bytes!("../../../resources/icons/eye-filled.svg"));
    pub(crate) const FILE: IconDefinition = IconDefinition::symbolic(include_bytes!("../../../resources/icons/file.svg"));
    pub(crate) const FILE_CODE: IconDefinition = IconDefinition::symbolic(include_bytes!("../../../resources/icons/file-code.svg"));
    pub(crate) const FILE_DOWNLOADED: IconDefinition = IconDefinition::symbolic(include_bytes!("../../../resources/icons/file-downloaded.svg"));
    pub(crate) const FILE_TEXT: IconDefinition = IconDefinition::symbolic(include_bytes!("../../../resources/icons/file-text.svg"));
    pub(crate) const FILES: IconDefinition = IconDefinition::symbolic(include_bytes!("../../../resources/icons/files.svg"));
    pub(crate) const FILTER: IconDefinition = IconDefinition::symbolic(include_bytes!("../../../resources/icons/filter.svg"));
    pub(crate) const FOLD: IconDefinition = IconDefinition::symbolic(include_bytes!("../../../resources/icons/fold.svg"));
    pub(crate) const FOLDER_DOWNLOADED: IconDefinition = IconDefinition::symbolic(include_bytes!("../../../resources/icons/folder-downloaded.svg"));
    pub(crate) const FOLDERS: IconDefinition = IconDefinition::symbolic(include_bytes!("../../../resources/icons/folders.svg"));
    pub(crate) const FORK: IconDefinition = IconDefinition::symbolic(include_bytes!("../../../resources/icons/fork.svg"));
    pub(crate) const GEAR: IconDefinition = IconDefinition::symbolic(include_bytes!("../../../resources/icons/gear.svg"));
    pub(crate) const GIT: IconDefinition = IconDefinition::symbolic(include_bytes!("../../../resources/icons/git.svg"));
    pub(crate) const GIT_BRANCH: IconDefinition = IconDefinition::symbolic(include_bytes!("../../../resources/icons/git-branch.svg"));
    pub(crate) const GIT_COMMIT: IconDefinition = IconDefinition::symbolic(include_bytes!("../../../resources/icons/git-commit.svg"));
    pub(crate) const GIT_PULL_REQUEST: IconDefinition = IconDefinition::symbolic(include_bytes!("../../../resources/icons/git-pull-request.svg"));
    pub(crate) const GIT_PULL_REQUEST_CLOSED: IconDefinition = IconDefinition::symbolic(include_bytes!("../../../resources/icons/git-pull-request-closed.svg"));
    pub(crate) const GIT_PULL_REQUEST_COMMENT: IconDefinition = IconDefinition::symbolic(include_bytes!("../../../resources/icons/git-pull-request-comment.svg"));
    pub(crate) const GIT_PULL_REQUEST_DONE: IconDefinition = IconDefinition::symbolic(include_bytes!("../../../resources/icons/git-pull-request-done.svg"));
    pub(crate) const GIT_PULL_REQUEST_DRAFT: IconDefinition = IconDefinition::symbolic(include_bytes!("../../../resources/icons/git-pull-request-draft.svg"));
    pub(crate) const GIT_PULL_REQUEST_ERROR: IconDefinition = IconDefinition::symbolic(include_bytes!("../../../resources/icons/git-pull-request-error.svg"));
    pub(crate) const GITHUB: IconDefinition = IconDefinition::symbolic(include_bytes!("../../../resources/icons/github.svg"));
    pub(crate) const GO_TO_FILE: IconDefinition = IconDefinition::symbolic(include_bytes!("../../../resources/icons/go-to-file.svg"));
    pub(crate) const H1: IconDefinition = IconDefinition::symbolic(include_bytes!("../../../resources/icons/h1.svg"));
    pub(crate) const H2: IconDefinition = IconDefinition::symbolic(include_bytes!("../../../resources/icons/h2.svg"));
    pub(crate) const H3: IconDefinition = IconDefinition::symbolic(include_bytes!("../../../resources/icons/h3.svg"));
    pub(crate) const H4: IconDefinition = IconDefinition::symbolic(include_bytes!("../../../resources/icons/h4.svg"));
    pub(crate) const H5: IconDefinition = IconDefinition::symbolic(include_bytes!("../../../resources/icons/h5.svg"));
    pub(crate) const HAND: IconDefinition = IconDefinition::symbolic(include_bytes!("../../../resources/icons/hand.svg"));
    pub(crate) const HISTORY: IconDefinition = IconDefinition::symbolic(include_bytes!("../../../resources/icons/history.svg"));
    pub(crate) const HOME: IconDefinition = IconDefinition::symbolic(include_bytes!("../../../resources/icons/home.svg"));
    pub(crate) const HOME_FILLED: IconDefinition = IconDefinition::symbolic(include_bytes!("../../../resources/icons/home-filled.svg"));
    pub(crate) const IMAGE: IconDefinition = IconDefinition::symbolic(include_bytes!("../../../resources/icons/image.svg"));
    pub(crate) const IMAGE_FILLED: IconDefinition = IconDefinition::symbolic(include_bytes!("../../../resources/icons/image-filled.svg"));
    pub(crate) const INFO: IconDefinition = IconDefinition::symbolic(include_bytes!("../../../resources/icons/info.svg"));
    pub(crate) const ITALICS: IconDefinition = IconDefinition::symbolic(include_bytes!("../../../resources/icons/italics.svg"));
    pub(crate) const KEBAB_VERTICAL: IconDefinition = IconDefinition::symbolic(include_bytes!("../../../resources/icons/kebab-vertical.svg"));
    pub(crate) const KEYBOARD_TAB: IconDefinition = IconDefinition::symbolic(include_bytes!("../../../resources/icons/keyboard-tab.svg"));
    pub(crate) const LAYOUT: IconDefinition = IconDefinition::symbolic(include_bytes!("../../../resources/icons/layout.svg"));
    pub(crate) const LAYOUT_PANEL_1: IconDefinition = IconDefinition::symbolic(include_bytes!("../../../resources/icons/layout-panel-1.svg"));
    pub(crate) const LAYOUT_PANEL_OFF_1: IconDefinition = IconDefinition::multicolor(include_bytes!("../../../resources/icons/layout-panel-off-1.svg"));
    pub(crate) const LAYOUT_SIDEBAR_LEFT_1: IconDefinition = IconDefinition::symbolic(include_bytes!("../../../resources/icons/layout-sidebar-left-1.svg"));
    pub(crate) const LAYOUT_SIDEBAR_LEFT_2: IconDefinition = IconDefinition::symbolic(include_bytes!("../../../resources/icons/layout-sidebar-left-2.svg"));
    pub(crate) const LAYOUT_SIDEBAR_LEFT_OFF_1: IconDefinition = IconDefinition::multicolor(include_bytes!("../../../resources/icons/layout-sidebar-left-off-1.svg"));
    pub(crate) const LAYOUT_SIDEBAR_LEFT_OFF_2: IconDefinition = IconDefinition::symbolic(include_bytes!("../../../resources/icons/layout-sidebar-left-off-2.svg"));
    pub(crate) const LAYOUT_SIDEBAR_RIGHT_1: IconDefinition = IconDefinition::symbolic(include_bytes!("../../../resources/icons/layout-sidebar-right-1.svg"));
    pub(crate) const LAYOUT_SIDEBAR_RIGHT_2: IconDefinition = IconDefinition::symbolic(include_bytes!("../../../resources/icons/layout-sidebar-right-2.svg"));
    pub(crate) const LAYOUT_SIDEBAR_RIGHT_OFF_1: IconDefinition = IconDefinition::multicolor(include_bytes!("../../../resources/icons/layout-sidebar-right-off-1.svg"));
    pub(crate) const LAYOUT_SIDEBAR_RIGHT_OFF_2: IconDefinition = IconDefinition::symbolic(include_bytes!("../../../resources/icons/layout-sidebar-right-off-2.svg"));
    pub(crate) const LEGEND: IconDefinition = IconDefinition::symbolic(include_bytes!("../../../resources/icons/legend.svg"));
    pub(crate) const LETTER_B: IconDefinition = IconDefinition::symbolic(include_bytes!("../../../resources/icons/letter-b.svg"));
    pub(crate) const LETTER_H: IconDefinition = IconDefinition::symbolic(include_bytes!("../../../resources/icons/letter-h.svg"));
    pub(crate) const LETTER_T: IconDefinition = IconDefinition::symbolic(include_bytes!("../../../resources/icons/letter-t.svg"));
    pub(crate) const LIBRARY: IconDefinition = IconDefinition::symbolic(include_bytes!("../../../resources/icons/library.svg"));
    pub(crate) const LIBRARY_FILLED: IconDefinition = IconDefinition::symbolic(include_bytes!("../../../resources/icons/library-filled.svg"));
    pub(crate) const LIGHTING_FILLED: IconDefinition = IconDefinition::symbolic(include_bytes!("../../../resources/icons/lighting-filled.svg"));
    pub(crate) const LIGHTNING: IconDefinition = IconDefinition::symbolic(include_bytes!("../../../resources/icons/lightning.svg"));
    pub(crate) const LIGHTNING_FILLED: IconDefinition = IconDefinition::symbolic(include_bytes!("../../../resources/icons/lightning-filled.svg"));
    pub(crate) const LINK_EXTERNAL: IconDefinition = IconDefinition::symbolic(include_bytes!("../../../resources/icons/link-external.svg"));
    pub(crate) const LIST_FILTER: IconDefinition = IconDefinition::symbolic(include_bytes!("../../../resources/icons/list-filter.svg"));
    pub(crate) const LIST_UNORDERED: IconDefinition = IconDefinition::symbolic(include_bytes!("../../../resources/icons/list-unordered.svg"));
    pub(crate) const MAP: IconDefinition = IconDefinition::symbolic(include_bytes!("../../../resources/icons/map.svg"));
    pub(crate) const MAP_FILLED: IconDefinition = IconDefinition::symbolic(include_bytes!("../../../resources/icons/map-filled.svg"));
    pub(crate) const MAP_VERTICAL: IconDefinition = IconDefinition::symbolic(include_bytes!("../../../resources/icons/map-vertical.svg"));
    pub(crate) const MAP_VERTICAL_FILLED: IconDefinition = IconDefinition::symbolic(include_bytes!("../../../resources/icons/map-vertical-filled.svg"));
    pub(crate) const MENU: IconDefinition = IconDefinition::symbolic(include_bytes!("../../../resources/icons/menu.svg"));
    pub(crate) const MIC: IconDefinition = IconDefinition::symbolic(include_bytes!("../../../resources/icons/mic.svg"));
    pub(crate) const MIC_FILLED: IconDefinition = IconDefinition::symbolic(include_bytes!("../../../resources/icons/mic-filled.svg"));
    pub(crate) const MODEL: IconDefinition = IconDefinition::symbolic(include_bytes!("../../../resources/icons/model.svg"));
    pub(crate) const MODEL_FILLED: IconDefinition = IconDefinition::symbolic(include_bytes!("../../../resources/icons/model-filled.svg"));
    pub(crate) const MOTION: IconDefinition = IconDefinition::symbolic(include_bytes!("../../../resources/icons/motion.svg"));
    pub(crate) const MULTITASK: IconDefinition = IconDefinition::symbolic(include_bytes!("../../../resources/icons/multitask.svg"));
    pub(crate) const NEW_FILE: IconDefinition = IconDefinition::symbolic(include_bytes!("../../../resources/icons/new-file.svg"));
    pub(crate) const NEW_FOLDER: IconDefinition = IconDefinition::symbolic(include_bytes!("../../../resources/icons/new-folder.svg"));
    pub(crate) const OPEN_PREVIEW: IconDefinition = IconDefinition::symbolic(include_bytes!("../../../resources/icons/open-preview.svg"));
    pub(crate) const OPENAI: IconDefinition = IconDefinition::symbolic(include_bytes!("../../../resources/icons/openai.svg"));
    pub(crate) const ORIGIN: IconDefinition = IconDefinition::symbolic(include_bytes!("../../../resources/icons/origin.svg"));
    pub(crate) const PAPERCLIP: IconDefinition = IconDefinition::symbolic(include_bytes!("../../../resources/icons/paperclip.svg"));
    pub(crate) const PARAMETERS: IconDefinition = IconDefinition::symbolic(include_bytes!("../../../resources/icons/parameters.svg"));
    pub(crate) const PASS: IconDefinition = IconDefinition::symbolic(include_bytes!("../../../resources/icons/pass.svg"));
    pub(crate) const PASS_FILLED: IconDefinition = IconDefinition::symbolic(include_bytes!("../../../resources/icons/pass-filled.svg"));
    pub(crate) const PAUSE: IconDefinition = IconDefinition::symbolic(include_bytes!("../../../resources/icons/pause.svg"));
    pub(crate) const PDF: IconDefinition = IconDefinition::symbolic(include_bytes!("../../../resources/icons/pdf.svg"));
    pub(crate) const PDF_FILLED: IconDefinition = IconDefinition::multicolor(include_bytes!("../../../resources/icons/pdf-filled.svg"));
    pub(crate) const PDF_RED: IconDefinition = IconDefinition::multicolor(include_bytes!("../../../resources/icons/pdf-red.svg"));
    pub(crate) const PEN: IconDefinition = IconDefinition::symbolic(include_bytes!("../../../resources/icons/pen.svg"));
    pub(crate) const PINNED: IconDefinition = IconDefinition::symbolic(include_bytes!("../../../resources/icons/pinned.svg"));
    pub(crate) const PLAN: IconDefinition = IconDefinition::symbolic(include_bytes!("../../../resources/icons/plan.svg"));
    pub(crate) const PREVIEW: IconDefinition = IconDefinition::symbolic(include_bytes!("../../../resources/icons/preview.svg"));
    pub(crate) const PRIMITIVE_SQUARE: IconDefinition = IconDefinition::symbolic(include_bytes!("../../../resources/icons/primitive-square.svg"));
    pub(crate) const PROJECTS: IconDefinition = IconDefinition::symbolic(include_bytes!("../../../resources/icons/projects.svg"));
    pub(crate) const PROJECTS_FILLED: IconDefinition = IconDefinition::symbolic(include_bytes!("../../../resources/icons/projects-filled.svg"));
    pub(crate) const QUESTION: IconDefinition = IconDefinition::symbolic(include_bytes!("../../../resources/icons/question.svg"));
    pub(crate) const QUOTE: IconDefinition = IconDefinition::symbolic(include_bytes!("../../../resources/icons/quote.svg"));
    pub(crate) const QUOTES: IconDefinition = IconDefinition::symbolic(include_bytes!("../../../resources/icons/quotes.svg"));
    pub(crate) const REFRESH: IconDefinition = IconDefinition::symbolic(include_bytes!("../../../resources/icons/refresh.svg"));
    pub(crate) const REMOTE: IconDefinition = IconDefinition::symbolic(include_bytes!("../../../resources/icons/remote.svg"));
    pub(crate) const REMOVE: IconDefinition = IconDefinition::symbolic(include_bytes!("../../../resources/icons/remove.svg"));
    pub(crate) const REMOVE_SMALL: IconDefinition = IconDefinition::symbolic(include_bytes!("../../../resources/icons/remove-small.svg"));
    pub(crate) const REPO_FETCH: IconDefinition = IconDefinition::symbolic(include_bytes!("../../../resources/icons/repo-fetch.svg"));
    pub(crate) const REPO_PULL: IconDefinition = IconDefinition::symbolic(include_bytes!("../../../resources/icons/repo-pull.svg"));
    pub(crate) const REPO_PUSH: IconDefinition = IconDefinition::symbolic(include_bytes!("../../../resources/icons/repo-push.svg"));
    pub(crate) const RSS: IconDefinition = IconDefinition::symbolic(include_bytes!("../../../resources/icons/rss.svg"));
    pub(crate) const SANDBOX: IconDefinition = IconDefinition::symbolic(include_bytes!("../../../resources/icons/sandbox.svg"));
    pub(crate) const SAVE: IconDefinition = IconDefinition::symbolic(include_bytes!("../../../resources/icons/save.svg"));
    pub(crate) const SCREEN_FULL: IconDefinition = IconDefinition::symbolic(include_bytes!("../../../resources/icons/screen-full.svg"));
    pub(crate) const SCREEN_NORMAL: IconDefinition = IconDefinition::symbolic(include_bytes!("../../../resources/icons/screen-normal.svg"));
    pub(crate) const SEARCH: IconDefinition = IconDefinition::symbolic(include_bytes!("../../../resources/icons/search.svg"));
    pub(crate) const SETTINGS: IconDefinition = IconDefinition::symbolic(include_bytes!("../../../resources/icons/settings.svg"));
    pub(crate) const SKILL: IconDefinition = IconDefinition::symbolic(include_bytes!("../../../resources/icons/skill.svg"));
    pub(crate) const SPARKLE: IconDefinition = IconDefinition::symbolic(include_bytes!("../../../resources/icons/sparkle.svg"));
    pub(crate) const SPARKLE_FILLED: IconDefinition = IconDefinition::symbolic(include_bytes!("../../../resources/icons/sparkle-filled.svg"));
    pub(crate) const SPLIT_HORIZONTAL: IconDefinition = IconDefinition::symbolic(include_bytes!("../../../resources/icons/split-horizontal.svg"));
    pub(crate) const SPLIT_PAGE: IconDefinition = IconDefinition::symbolic(include_bytes!("../../../resources/icons/split-page.svg"));
    pub(crate) const SPLIT_VERTICAL: IconDefinition = IconDefinition::symbolic(include_bytes!("../../../resources/icons/split-vertical.svg"));
    pub(crate) const SQUARE: IconDefinition = IconDefinition::symbolic(include_bytes!("../../../resources/icons/square.svg"));
    pub(crate) const STAR: IconDefinition = IconDefinition::symbolic(include_bytes!("../../../resources/icons/star.svg"));
    pub(crate) const STAR_FILLED: IconDefinition = IconDefinition::symbolic(include_bytes!("../../../resources/icons/star-filled.svg"));
    pub(crate) const START: IconDefinition = IconDefinition::symbolic(include_bytes!("../../../resources/icons/start.svg"));
    pub(crate) const STRAW: IconDefinition = IconDefinition::symbolic(include_bytes!("../../../resources/icons/straw.svg"));
    pub(crate) const SUMMARY: IconDefinition = IconDefinition::symbolic(include_bytes!("../../../resources/icons/summary.svg"));
    pub(crate) const SYMBOL_COLOR: IconDefinition = IconDefinition::symbolic(include_bytes!("../../../resources/icons/symbol-color.svg"));
    pub(crate) const SYMBOL_COLOR_FILLED: IconDefinition = IconDefinition::symbolic(include_bytes!("../../../resources/icons/symbol-color-filled.svg"));
    pub(crate) const SYNC: IconDefinition = IconDefinition::symbolic(include_bytes!("../../../resources/icons/sync.svg"));
    pub(crate) const TABLE: IconDefinition = IconDefinition::symbolic(include_bytes!("../../../resources/icons/table.svg"));
    pub(crate) const TAG: IconDefinition = IconDefinition::symbolic(include_bytes!("../../../resources/icons/tag.svg"));
    pub(crate) const TARGET: IconDefinition = IconDefinition::symbolic(include_bytes!("../../../resources/icons/target.svg"));
    pub(crate) const TERMINAL: IconDefinition = IconDefinition::symbolic(include_bytes!("../../../resources/icons/terminal.svg"));
    pub(crate) const TERMINAL_CMD: IconDefinition = IconDefinition::symbolic(include_bytes!("../../../resources/icons/terminal-cmd.svg"));
    pub(crate) const TERMINAL_GIT_BASH: IconDefinition = IconDefinition::symbolic(include_bytes!("../../../resources/icons/terminal-git-bash.svg"));
    pub(crate) const TEXT: IconDefinition = IconDefinition::symbolic(include_bytes!("../../../resources/icons/text.svg"));
    pub(crate) const TEXT_2: IconDefinition = IconDefinition::symbolic(include_bytes!("../../../resources/icons/text-2.svg"));
    pub(crate) const TRANSLATE: IconDefinition = IconDefinition::symbolic(include_bytes!("../../../resources/icons/translate.svg"));
    pub(crate) const TRASH: IconDefinition = IconDefinition::symbolic(include_bytes!("../../../resources/icons/trash.svg"));
    pub(crate) const TRASH_FLAT: IconDefinition = IconDefinition::symbolic(include_bytes!("../../../resources/icons/trash-flat.svg"));
    pub(crate) const TXT_LETTER: IconDefinition = IconDefinition::symbolic(include_bytes!("../../../resources/icons/txt-letter.svg"));
    pub(crate) const TXT_LETTER_FILLED: IconDefinition = IconDefinition::symbolic(include_bytes!("../../../resources/icons/txt-letter-filled.svg"));
    pub(crate) const TYPOGRAPHY: IconDefinition = IconDefinition::symbolic(include_bytes!("../../../resources/icons/typography.svg"));
    pub(crate) const UNDERLINE: IconDefinition = IconDefinition::symbolic(include_bytes!("../../../resources/icons/underline.svg"));
    pub(crate) const UNFOLD: IconDefinition = IconDefinition::symbolic(include_bytes!("../../../resources/icons/unfold.svg"));
    pub(crate) const UNLIMITED: IconDefinition = IconDefinition::symbolic(include_bytes!("../../../resources/icons/unlimited.svg"));
    pub(crate) const UNPIN: IconDefinition = IconDefinition::symbolic(include_bytes!("../../../resources/icons/unpin.svg"));
    pub(crate) const VOICE_MODE: IconDefinition = IconDefinition::symbolic(include_bytes!("../../../resources/icons/voice-mode.svg"));
    pub(crate) const WARNING: IconDefinition = IconDefinition::symbolic(include_bytes!("../../../resources/icons/warning.svg"));
    pub(crate) const WEBSITE: IconDefinition = IconDefinition::symbolic(include_bytes!("../../../resources/icons/website.svg"));
    pub(crate) const WORKTREE: IconDefinition = IconDefinition::symbolic(include_bytes!("../../../resources/icons/worktree.svg"));
    pub(crate) const WRITE: IconDefinition = IconDefinition::symbolic(include_bytes!("../../../resources/icons/write.svg"));
    pub(crate) const XLS_GREEN: IconDefinition = IconDefinition::multicolor(include_bytes!("../../../resources/icons/xls-green.svg"));
    pub(crate) const XLS_LETTER: IconDefinition = IconDefinition::symbolic(include_bytes!("../../../resources/icons/xls-letter.svg"));
    pub(crate) const XLS_LETTER_FILLED: IconDefinition = IconDefinition::symbolic(include_bytes!("../../../resources/icons/xls-letter-filled.svg"));
    pub(crate) const ZOOM_IN: IconDefinition = IconDefinition::symbolic(include_bytes!("../../../resources/icons/zoom-in.svg"));
    pub(crate) const ZOOM_OUT: IconDefinition = IconDefinition::symbolic(include_bytes!("../../../resources/icons/zoom-out.svg"));
}

#[rustfmt::skip]
pub mod icons {
    use super::Icon;
    use super::IconId;
    use super::artwork;

    pub const ACCOUNT: Icon = Icon::new(IconId::new("account"), artwork::ACCOUNT);
    pub const ADD: Icon = Icon::new(IconId::new("add"), artwork::ADD);
    pub const ADD_SMALL: Icon = Icon::new(IconId::new("add-small"), artwork::ADD_SMALL);
    pub const AGENT: Icon = Icon::new(IconId::new("agent"), artwork::AGENT);
    pub const AGENT_FILLED: Icon = Icon::new(IconId::new("agent-filled"), artwork::AGENT_FILLED);
    pub const ALIGN_CENTER: Icon = Icon::new(IconId::new("align-center"), artwork::ALIGN_CENTER);
    pub const ALIGN_JUSTIFIED: Icon = Icon::new(IconId::new("align-justified"), artwork::ALIGN_JUSTIFIED);
    pub const ALIGN_LEFT: Icon = Icon::new(IconId::new("align-left"), artwork::ALIGN_LEFT);
    pub const ALIGN_RIGHT: Icon = Icon::new(IconId::new("align-right"), artwork::ALIGN_RIGHT);
    pub const APPEARANCE: Icon = Icon::new(IconId::new("appearance"), artwork::APPEARANCE);
    pub const ARCHIVE: Icon = Icon::new(IconId::new("archive"), artwork::ARCHIVE);
    pub const ARROW_DOWN: Icon = Icon::new(IconId::new("arrow-down"), artwork::ARROW_DOWN);
    pub const ARROW_LEFT: Icon = Icon::new(IconId::new("arrow-left"), artwork::ARROW_LEFT);
    pub const ARROW_RIGHT: Icon = Icon::new(IconId::new("arrow-right"), artwork::ARROW_RIGHT);
    pub const ARROW_UP: Icon = Icon::new(IconId::new("arrow-up"), artwork::ARROW_UP);
    pub const ASK: Icon = Icon::new(IconId::new("ask"), artwork::ASK);
    pub const BELL: Icon = Icon::new(IconId::new("bell"), artwork::BELL);
    pub const BELL_DOT: Icon = Icon::new(IconId::new("bell-dot"), artwork::BELL_DOT);
    pub const BELL_SLASH: Icon = Icon::new(IconId::new("bell-slash"), artwork::BELL_SLASH);
    pub const BOLD: Icon = Icon::new(IconId::new("bold"), artwork::BOLD);
    pub const BOOK: Icon = Icon::new(IconId::new("book"), artwork::BOOK);
    pub const BOOKS: Icon = Icon::new(IconId::new("books"), artwork::BOOKS);
    pub const BRIEFCASE: Icon = Icon::new(IconId::new("briefcase"), artwork::BRIEFCASE);
    pub const BRIEFCASE_FILLED: Icon = Icon::new(IconId::new("briefcase-filled"), artwork::BRIEFCASE_FILLED);
    pub const BROWSER_EXPLORE: Icon = Icon::new(IconId::new("browser-explore"), artwork::BROWSER_EXPLORE);
    pub const BROWSER_WEB: Icon = Icon::new(IconId::new("browser-web"), artwork::BROWSER_WEB);
    pub const CALENDAR: Icon = Icon::new(IconId::new("calendar"), artwork::CALENDAR);
    pub const CHART: Icon = Icon::new(IconId::new("chart"), artwork::CHART);
    pub const CHAT_1: Icon = Icon::new(IconId::new("chat-1"), artwork::CHAT_1);
    pub const CHAT_1_FILLED: Icon = Icon::new(IconId::new("chat-1-filled"), artwork::CHAT_1_FILLED);
    pub const CHAT_2: Icon = Icon::new(IconId::new("chat-2"), artwork::CHAT_2);
    pub const CHAT_2_FILLED: Icon = Icon::new(IconId::new("chat-2-filled"), artwork::CHAT_2_FILLED);
    pub const CHAT_3: Icon = Icon::new(IconId::new("chat-3"), artwork::CHAT_3);
    pub const CHAT_3_FILLED: Icon = Icon::new(IconId::new("chat-3-filled"), artwork::CHAT_3_FILLED);
    pub const CHAT_4: Icon = Icon::new(IconId::new("chat-4"), artwork::CHAT_4);
    pub const CHAT_4_FILLED: Icon = Icon::new(IconId::new("chat-4-filled"), artwork::CHAT_4_FILLED);
    pub const CHECK: Icon = Icon::new(IconId::new("check"), artwork::CHECK);
    pub const CHEVRON_DOWN: Icon = Icon::new(IconId::new("chevron-down"), artwork::CHEVRON_DOWN);
    pub const CHEVRON_LEFT: Icon = Icon::new(IconId::new("chevron-left"), artwork::CHEVRON_LEFT);
    pub const CHEVRON_RIGHT: Icon = Icon::new(IconId::new("chevron-right"), artwork::CHEVRON_RIGHT);
    pub const CHEVRON_UP: Icon = Icon::new(IconId::new("chevron-up"), artwork::CHEVRON_UP);
    pub const CIRCLE_LARGE: Icon = Icon::new(IconId::new("circle-large"), artwork::CIRCLE_LARGE);
    pub const CIRCLE_LARGE_FILLED: Icon = Icon::new(IconId::new("circle-large-filled"), artwork::CIRCLE_LARGE_FILLED);
    pub const CIRCLE_SMALL: Icon = Icon::new(IconId::new("circle-small"), artwork::CIRCLE_SMALL);
    pub const CIRCLE_SMALL_FILLED: Icon = Icon::new(IconId::new("circle-small-filled"), artwork::CIRCLE_SMALL_FILLED);
    pub const CLAUDE: Icon = Icon::new(IconId::new("claude"), artwork::CLAUDE);
    pub const CLOSE: Icon = Icon::new(IconId::new("close"), artwork::CLOSE);
    pub const CLOUD: Icon = Icon::new(IconId::new("cloud"), artwork::CLOUD);
    pub const CODE: Icon = Icon::new(IconId::new("code"), artwork::CODE);
    pub const CODE_REVIEW: Icon = Icon::new(IconId::new("code-review"), artwork::CODE_REVIEW);
    pub const COLAB: Icon = Icon::new(IconId::new("colab"), artwork::COLAB);
    pub const COLAB_FILLED: Icon = Icon::new(IconId::new("colab-filled"), artwork::COLAB_FILLED);
    pub const COMMAND: Icon = Icon::new(IconId::new("command"), artwork::COMMAND);
    pub const CONNECTORS: Icon = Icon::new(IconId::new("connectors"), artwork::CONNECTORS);
    pub const COPY: Icon = Icon::new(IconId::new("copy"), artwork::COPY);
    pub const COPY_CODE: Icon = Icon::new(IconId::new("copy-code"), artwork::COPY_CODE);
    pub const COWORK: Icon = Icon::new(IconId::new("cowork"), artwork::COWORK);
    pub const CSV: Icon = Icon::new(IconId::new("csv"), artwork::CSV);
    pub const CSV_FILLED: Icon = Icon::new(IconId::new("csv-filled"), artwork::CSV_FILLED);
    pub const CSV_GREEN: Icon = Icon::new(IconId::new("csv-green"), artwork::CSV_GREEN);
    pub const CSV_LETTER: Icon = Icon::new(IconId::new("csv-letter"), artwork::CSV_LETTER);
    pub const CSV_LETTER_FILLED: Icon = Icon::new(IconId::new("csv-letter-filled"), artwork::CSV_LETTER_FILLED);
    pub const CURSOR: Icon = Icon::new(IconId::new("cursor"), artwork::CURSOR);
    pub const CURSOR_2: Icon = Icon::new(IconId::new("cursor-2"), artwork::CURSOR_2);
    pub const CURSOR_FILLED: Icon = Icon::new(IconId::new("cursor-filled"), artwork::CURSOR_FILLED);
    pub const DATABASE: Icon = Icon::new(IconId::new("database"), artwork::DATABASE);
    pub const DATABASE_FLAT: Icon = Icon::new(IconId::new("database-flat"), artwork::DATABASE_FLAT);
    pub const DEBUG: Icon = Icon::new(IconId::new("debug"), artwork::DEBUG);
    pub const DEBUG_ALT: Icon = Icon::new(IconId::new("debug-alt"), artwork::DEBUG_ALT);
    pub const DESIGN: Icon = Icon::new(IconId::new("design"), artwork::DESIGN);
    pub const DEVICE_MOBILE: Icon = Icon::new(IconId::new("device-mobile"), artwork::DEVICE_MOBILE);
    pub const DIAGNOSTICS: Icon = Icon::new(IconId::new("diagnostics"), artwork::DIAGNOSTICS);
    pub const DIFF: Icon = Icon::new(IconId::new("diff"), artwork::DIFF);
    pub const DIFF_MULTIPLE_1: Icon = Icon::new(IconId::new("diff-multiple-1"), artwork::DIFF_MULTIPLE_1);
    pub const DIFF_MULTIPLE_2: Icon = Icon::new(IconId::new("diff-multiple-2"), artwork::DIFF_MULTIPLE_2);
    pub const DISCARD: Icon = Icon::new(IconId::new("discard"), artwork::DISCARD);
    pub const DOCX: Icon = Icon::new(IconId::new("docx"), artwork::DOCX);
    pub const DOCX_BLUE: Icon = Icon::new(IconId::new("docx-blue"), artwork::DOCX_BLUE);
    pub const DOCX_FILLED: Icon = Icon::new(IconId::new("docx-filled"), artwork::DOCX_FILLED);
    pub const DOWNLOAD: Icon = Icon::new(IconId::new("download"), artwork::DOWNLOAD);
    pub const DOWNLOAD_BOX: Icon = Icon::new(IconId::new("download-box"), artwork::DOWNLOAD_BOX);
    pub const DOWNLOAD_TRAY: Icon = Icon::new(IconId::new("download-tray"), artwork::DOWNLOAD_TRAY);
    pub const EDIT: Icon = Icon::new(IconId::new("edit"), artwork::EDIT);
    pub const EDIT_1: Icon = Icon::new(IconId::new("edit-1"), artwork::EDIT_1);
    pub const EDIT_2: Icon = Icon::new(IconId::new("edit-2"), artwork::EDIT_2);
    pub const EDIT_WRITE: Icon = Icon::new(IconId::new("edit-write"), artwork::EDIT_WRITE);
    pub const ELLIPSIS: Icon = Icon::new(IconId::new("ellipsis"), artwork::ELLIPSIS);
    pub const ENTER: Icon = Icon::new(IconId::new("enter"), artwork::ENTER);
    pub const ERASER: Icon = Icon::new(IconId::new("eraser"), artwork::ERASER);
    pub const ERROR: Icon = Icon::new(IconId::new("error"), artwork::ERROR);
    pub const EXPORT: Icon = Icon::new(IconId::new("export"), artwork::EXPORT);
    pub const EXPORT_TRAY: Icon = Icon::new(IconId::new("export-tray"), artwork::EXPORT_TRAY);
    pub const EXTENSIONS: Icon = Icon::new(IconId::new("extensions"), artwork::EXTENSIONS);
    pub const EYE: Icon = Icon::new(IconId::new("eye"), artwork::EYE);
    pub const EYE_FILLED: Icon = Icon::new(IconId::new("eye-filled"), artwork::EYE_FILLED);
    pub const FILE: Icon = Icon::new(IconId::new("file"), artwork::FILE);
    pub const FILE_CODE: Icon = Icon::new(IconId::new("file-code"), artwork::FILE_CODE);
    pub const FILE_DOWNLOADED: Icon = Icon::new(IconId::new("file-downloaded"), artwork::FILE_DOWNLOADED);
    pub const FILE_TEXT: Icon = Icon::new(IconId::new("file-text"), artwork::FILE_TEXT);
    pub const FILES: Icon = Icon::new(IconId::new("files"), artwork::FILES);
    pub const FILTER: Icon = Icon::new(IconId::new("filter"), artwork::FILTER);
    pub const FOLD: Icon = Icon::new(IconId::new("fold"), artwork::FOLD);
    pub const FOLDER_DOWNLOADED: Icon = Icon::new(IconId::new("folder-downloaded"), artwork::FOLDER_DOWNLOADED);
    pub const FOLDERS: Icon = Icon::new(IconId::new("folders"), artwork::FOLDERS);
    pub const FORK: Icon = Icon::new(IconId::new("fork"), artwork::FORK);
    pub const GEAR: Icon = Icon::new(IconId::new("gear"), artwork::GEAR);
    pub const GIT: Icon = Icon::new(IconId::new("git"), artwork::GIT);
    pub const GIT_BRANCH: Icon = Icon::new(IconId::new("git-branch"), artwork::GIT_BRANCH);
    pub const GIT_COMMIT: Icon = Icon::new(IconId::new("git-commit"), artwork::GIT_COMMIT);
    pub const GIT_PULL_REQUEST: Icon = Icon::new(IconId::new("git-pull-request"), artwork::GIT_PULL_REQUEST);
    pub const GIT_PULL_REQUEST_CLOSED: Icon = Icon::new(IconId::new("git-pull-request-closed"), artwork::GIT_PULL_REQUEST_CLOSED);
    pub const GIT_PULL_REQUEST_COMMENT: Icon = Icon::new(IconId::new("git-pull-request-comment"), artwork::GIT_PULL_REQUEST_COMMENT);
    pub const GIT_PULL_REQUEST_DONE: Icon = Icon::new(IconId::new("git-pull-request-done"), artwork::GIT_PULL_REQUEST_DONE);
    pub const GIT_PULL_REQUEST_DRAFT: Icon = Icon::new(IconId::new("git-pull-request-draft"), artwork::GIT_PULL_REQUEST_DRAFT);
    pub const GIT_PULL_REQUEST_ERROR: Icon = Icon::new(IconId::new("git-pull-request-error"), artwork::GIT_PULL_REQUEST_ERROR);
    pub const GITHUB: Icon = Icon::new(IconId::new("github"), artwork::GITHUB);
    pub const GO_TO_FILE: Icon = Icon::new(IconId::new("go-to-file"), artwork::GO_TO_FILE);
    pub const H1: Icon = Icon::new(IconId::new("h1"), artwork::H1);
    pub const H2: Icon = Icon::new(IconId::new("h2"), artwork::H2);
    pub const H3: Icon = Icon::new(IconId::new("h3"), artwork::H3);
    pub const H4: Icon = Icon::new(IconId::new("h4"), artwork::H4);
    pub const H5: Icon = Icon::new(IconId::new("h5"), artwork::H5);
    pub const HAND: Icon = Icon::new(IconId::new("hand"), artwork::HAND);
    pub const HISTORY: Icon = Icon::new(IconId::new("history"), artwork::HISTORY);
    pub const HOME: Icon = Icon::new(IconId::new("home"), artwork::HOME);
    pub const HOME_FILLED: Icon = Icon::new(IconId::new("home-filled"), artwork::HOME_FILLED);
    pub const IMAGE: Icon = Icon::new(IconId::new("image"), artwork::IMAGE);
    pub const IMAGE_FILLED: Icon = Icon::new(IconId::new("image-filled"), artwork::IMAGE_FILLED);
    pub const INFO: Icon = Icon::new(IconId::new("info"), artwork::INFO);
    pub const ITALICS: Icon = Icon::new(IconId::new("italics"), artwork::ITALICS);
    pub const KEBAB_VERTICAL: Icon = Icon::new(IconId::new("kebab-vertical"), artwork::KEBAB_VERTICAL);
    pub const KEYBOARD_TAB: Icon = Icon::new(IconId::new("keyboard-tab"), artwork::KEYBOARD_TAB);
    pub const LAYOUT: Icon = Icon::new(IconId::new("layout"), artwork::LAYOUT);
    pub const LAYOUT_PANEL_1: Icon = Icon::new(IconId::new("layout-panel-1"), artwork::LAYOUT_PANEL_1);
    pub const LAYOUT_PANEL_OFF_1: Icon = Icon::new(IconId::new("layout-panel-off-1"), artwork::LAYOUT_PANEL_OFF_1);
    pub const LAYOUT_SIDEBAR_LEFT_1: Icon = Icon::new(IconId::new("layout-sidebar-left-1"), artwork::LAYOUT_SIDEBAR_LEFT_1);
    pub const LAYOUT_SIDEBAR_LEFT_2: Icon = Icon::new(IconId::new("layout-sidebar-left-2"), artwork::LAYOUT_SIDEBAR_LEFT_2);
    pub const LAYOUT_SIDEBAR_LEFT_OFF_1: Icon = Icon::new(IconId::new("layout-sidebar-left-off-1"), artwork::LAYOUT_SIDEBAR_LEFT_OFF_1);
    pub const LAYOUT_SIDEBAR_LEFT_OFF_2: Icon = Icon::new(IconId::new("layout-sidebar-left-off-2"), artwork::LAYOUT_SIDEBAR_LEFT_OFF_2);
    pub const LAYOUT_SIDEBAR_RIGHT_1: Icon = Icon::new(IconId::new("layout-sidebar-right-1"), artwork::LAYOUT_SIDEBAR_RIGHT_1);
    pub const LAYOUT_SIDEBAR_RIGHT_2: Icon = Icon::new(IconId::new("layout-sidebar-right-2"), artwork::LAYOUT_SIDEBAR_RIGHT_2);
    pub const LAYOUT_SIDEBAR_RIGHT_OFF_1: Icon = Icon::new(IconId::new("layout-sidebar-right-off-1"), artwork::LAYOUT_SIDEBAR_RIGHT_OFF_1);
    pub const LAYOUT_SIDEBAR_RIGHT_OFF_2: Icon = Icon::new(IconId::new("layout-sidebar-right-off-2"), artwork::LAYOUT_SIDEBAR_RIGHT_OFF_2);
    pub const LEGEND: Icon = Icon::new(IconId::new("legend"), artwork::LEGEND);
    pub const LETTER_B: Icon = Icon::new(IconId::new("letter-b"), artwork::LETTER_B);
    pub const LETTER_H: Icon = Icon::new(IconId::new("letter-h"), artwork::LETTER_H);
    pub const LETTER_T: Icon = Icon::new(IconId::new("letter-t"), artwork::LETTER_T);
    pub const LIBRARY: Icon = Icon::new(IconId::new("library"), artwork::LIBRARY);
    pub const LIBRARY_FILLED: Icon = Icon::new(IconId::new("library-filled"), artwork::LIBRARY_FILLED);
    pub const LIGHTING_FILLED: Icon = Icon::new(IconId::new("lighting-filled"), artwork::LIGHTING_FILLED);
    pub const LIGHTNING: Icon = Icon::new(IconId::new("lightning"), artwork::LIGHTNING);
    pub const LIGHTNING_FILLED: Icon = Icon::new(IconId::new("lightning-filled"), artwork::LIGHTNING_FILLED);
    pub const LINK_EXTERNAL: Icon = Icon::new(IconId::new("link-external"), artwork::LINK_EXTERNAL);
    pub const LIST_FILTER: Icon = Icon::new(IconId::new("list-filter"), artwork::LIST_FILTER);
    pub const LIST_UNORDERED: Icon = Icon::new(IconId::new("list-unordered"), artwork::LIST_UNORDERED);
    pub const MAP: Icon = Icon::new(IconId::new("map"), artwork::MAP);
    pub const MAP_FILLED: Icon = Icon::new(IconId::new("map-filled"), artwork::MAP_FILLED);
    pub const MAP_VERTICAL: Icon = Icon::new(IconId::new("map-vertical"), artwork::MAP_VERTICAL);
    pub const MAP_VERTICAL_FILLED: Icon = Icon::new(IconId::new("map-vertical-filled"), artwork::MAP_VERTICAL_FILLED);
    pub const MENU: Icon = Icon::new(IconId::new("menu"), artwork::MENU);
    pub const MIC: Icon = Icon::new(IconId::new("mic"), artwork::MIC);
    pub const MIC_FILLED: Icon = Icon::new(IconId::new("mic-filled"), artwork::MIC_FILLED);
    pub const MODEL: Icon = Icon::new(IconId::new("model"), artwork::MODEL);
    pub const MODEL_FILLED: Icon = Icon::new(IconId::new("model-filled"), artwork::MODEL_FILLED);
    pub const MOTION: Icon = Icon::new(IconId::new("motion"), artwork::MOTION);
    pub const MULTITASK: Icon = Icon::new(IconId::new("multitask"), artwork::MULTITASK);
    pub const NEW_FILE: Icon = Icon::new(IconId::new("new-file"), artwork::NEW_FILE);
    pub const NEW_FOLDER: Icon = Icon::new(IconId::new("new-folder"), artwork::NEW_FOLDER);
    pub const OPEN_PREVIEW: Icon = Icon::new(IconId::new("open-preview"), artwork::OPEN_PREVIEW);
    pub const OPENAI: Icon = Icon::new(IconId::new("openai"), artwork::OPENAI);
    pub const ORIGIN: Icon = Icon::new(IconId::new("origin"), artwork::ORIGIN);
    pub const PAPERCLIP: Icon = Icon::new(IconId::new("paperclip"), artwork::PAPERCLIP);
    pub const PARAMETERS: Icon = Icon::new(IconId::new("parameters"), artwork::PARAMETERS);
    pub const PASS: Icon = Icon::new(IconId::new("pass"), artwork::PASS);
    pub const PASS_FILLED: Icon = Icon::new(IconId::new("pass-filled"), artwork::PASS_FILLED);
    pub const PAUSE: Icon = Icon::new(IconId::new("pause"), artwork::PAUSE);
    pub const PDF: Icon = Icon::new(IconId::new("pdf"), artwork::PDF);
    pub const PDF_FILLED: Icon = Icon::new(IconId::new("pdf-filled"), artwork::PDF_FILLED);
    pub const PDF_RED: Icon = Icon::new(IconId::new("pdf-red"), artwork::PDF_RED);
    pub const PEN: Icon = Icon::new(IconId::new("pen"), artwork::PEN);
    pub const PINNED: Icon = Icon::new(IconId::new("pinned"), artwork::PINNED);
    pub const PLAN: Icon = Icon::new(IconId::new("plan"), artwork::PLAN);
    pub const PREVIEW: Icon = Icon::new(IconId::new("preview"), artwork::PREVIEW);
    pub const PRIMITIVE_SQUARE: Icon = Icon::new(IconId::new("primitive-square"), artwork::PRIMITIVE_SQUARE);
    pub const PROJECTS: Icon = Icon::new(IconId::new("projects"), artwork::PROJECTS);
    pub const PROJECTS_FILLED: Icon = Icon::new(IconId::new("projects-filled"), artwork::PROJECTS_FILLED);
    pub const QUESTION: Icon = Icon::new(IconId::new("question"), artwork::QUESTION);
    pub const QUOTE: Icon = Icon::new(IconId::new("quote"), artwork::QUOTE);
    pub const QUOTES: Icon = Icon::new(IconId::new("quotes"), artwork::QUOTES);
    pub const REFRESH: Icon = Icon::new(IconId::new("refresh"), artwork::REFRESH);
    pub const REMOTE: Icon = Icon::new(IconId::new("remote"), artwork::REMOTE);
    pub const REMOVE: Icon = Icon::new(IconId::new("remove"), artwork::REMOVE);
    pub const REMOVE_SMALL: Icon = Icon::new(IconId::new("remove-small"), artwork::REMOVE_SMALL);
    pub const REPO_FETCH: Icon = Icon::new(IconId::new("repo-fetch"), artwork::REPO_FETCH);
    pub const REPO_PULL: Icon = Icon::new(IconId::new("repo-pull"), artwork::REPO_PULL);
    pub const REPO_PUSH: Icon = Icon::new(IconId::new("repo-push"), artwork::REPO_PUSH);
    pub const RSS: Icon = Icon::new(IconId::new("rss"), artwork::RSS);
    pub const SANDBOX: Icon = Icon::new(IconId::new("sandbox"), artwork::SANDBOX);
    pub const SAVE: Icon = Icon::new(IconId::new("save"), artwork::SAVE);
    pub const SCREEN_FULL: Icon = Icon::new(IconId::new("screen-full"), artwork::SCREEN_FULL);
    pub const SCREEN_NORMAL: Icon = Icon::new(IconId::new("screen-normal"), artwork::SCREEN_NORMAL);
    pub const SEARCH: Icon = Icon::new(IconId::new("search"), artwork::SEARCH);
    pub const SETTINGS: Icon = Icon::new(IconId::new("settings"), artwork::SETTINGS);
    pub const SKILL: Icon = Icon::new(IconId::new("skill"), artwork::SKILL);
    pub const SPARKLE: Icon = Icon::new(IconId::new("sparkle"), artwork::SPARKLE);
    pub const SPARKLE_FILLED: Icon = Icon::new(IconId::new("sparkle-filled"), artwork::SPARKLE_FILLED);
    pub const SPLIT_HORIZONTAL: Icon = Icon::new(IconId::new("split-horizontal"), artwork::SPLIT_HORIZONTAL);
    pub const SPLIT_PAGE: Icon = Icon::new(IconId::new("split-page"), artwork::SPLIT_PAGE);
    pub const SPLIT_VERTICAL: Icon = Icon::new(IconId::new("split-vertical"), artwork::SPLIT_VERTICAL);
    pub const SQUARE: Icon = Icon::new(IconId::new("square"), artwork::SQUARE);
    pub const STAR: Icon = Icon::new(IconId::new("star"), artwork::STAR);
    pub const STAR_FILLED: Icon = Icon::new(IconId::new("star-filled"), artwork::STAR_FILLED);
    pub const START: Icon = Icon::new(IconId::new("start"), artwork::START);
    pub const STRAW: Icon = Icon::new(IconId::new("straw"), artwork::STRAW);
    pub const SUMMARY: Icon = Icon::new(IconId::new("summary"), artwork::SUMMARY);
    pub const SYMBOL_COLOR: Icon = Icon::new(IconId::new("symbol-color"), artwork::SYMBOL_COLOR);
    pub const SYMBOL_COLOR_FILLED: Icon = Icon::new(IconId::new("symbol-color-filled"), artwork::SYMBOL_COLOR_FILLED);
    pub const SYNC: Icon = Icon::new(IconId::new("sync"), artwork::SYNC);
    pub const TABLE: Icon = Icon::new(IconId::new("table"), artwork::TABLE);
    pub const TAG: Icon = Icon::new(IconId::new("tag"), artwork::TAG);
    pub const TARGET: Icon = Icon::new(IconId::new("target"), artwork::TARGET);
    pub const TERMINAL: Icon = Icon::new(IconId::new("terminal"), artwork::TERMINAL);
    pub const TERMINAL_CMD: Icon = Icon::new(IconId::new("terminal-cmd"), artwork::TERMINAL_CMD);
    pub const TERMINAL_GIT_BASH: Icon = Icon::new(IconId::new("terminal-git-bash"), artwork::TERMINAL_GIT_BASH);
    pub const TEXT: Icon = Icon::new(IconId::new("text"), artwork::TEXT);
    pub const TEXT_2: Icon = Icon::new(IconId::new("text-2"), artwork::TEXT_2);
    pub const TRANSLATE: Icon = Icon::new(IconId::new("translate"), artwork::TRANSLATE);
    pub const TRASH: Icon = Icon::new(IconId::new("trash"), artwork::TRASH);
    pub const TRASH_FLAT: Icon = Icon::new(IconId::new("trash-flat"), artwork::TRASH_FLAT);
    pub const TXT_LETTER: Icon = Icon::new(IconId::new("txt-letter"), artwork::TXT_LETTER);
    pub const TXT_LETTER_FILLED: Icon = Icon::new(IconId::new("txt-letter-filled"), artwork::TXT_LETTER_FILLED);
    pub const TYPOGRAPHY: Icon = Icon::new(IconId::new("typography"), artwork::TYPOGRAPHY);
    pub const UNDERLINE: Icon = Icon::new(IconId::new("underline"), artwork::UNDERLINE);
    pub const UNFOLD: Icon = Icon::new(IconId::new("unfold"), artwork::UNFOLD);
    pub const UNLIMITED: Icon = Icon::new(IconId::new("unlimited"), artwork::UNLIMITED);
    pub const UNPIN: Icon = Icon::new(IconId::new("unpin"), artwork::UNPIN);
    pub const VOICE_MODE: Icon = Icon::new(IconId::new("voice-mode"), artwork::VOICE_MODE);
    pub const WARNING: Icon = Icon::new(IconId::new("warning"), artwork::WARNING);
    pub const WEBSITE: Icon = Icon::new(IconId::new("website"), artwork::WEBSITE);
    pub const WORKTREE: Icon = Icon::new(IconId::new("worktree"), artwork::WORKTREE);
    pub const WRITE: Icon = Icon::new(IconId::new("write"), artwork::WRITE);
    pub const XLS_GREEN: Icon = Icon::new(IconId::new("xls-green"), artwork::XLS_GREEN);
    pub const XLS_LETTER: Icon = Icon::new(IconId::new("xls-letter"), artwork::XLS_LETTER);
    pub const XLS_LETTER_FILLED: Icon = Icon::new(IconId::new("xls-letter-filled"), artwork::XLS_LETTER_FILLED);
    pub const ZOOM_IN: Icon = Icon::new(IconId::new("zoom-in"), artwork::ZOOM_IN);
    pub const ZOOM_OUT: Icon = Icon::new(IconId::new("zoom-out"), artwork::ZOOM_OUT);
}

#[rustfmt::skip]
pub const ALL_ICONS: &[Icon] = &[
    icons::ACCOUNT,
    icons::ADD,
    icons::ADD_SMALL,
    icons::AGENT,
    icons::AGENT_FILLED,
    icons::ALIGN_CENTER,
    icons::ALIGN_JUSTIFIED,
    icons::ALIGN_LEFT,
    icons::ALIGN_RIGHT,
    icons::APPEARANCE,
    icons::ARCHIVE,
    icons::ARROW_DOWN,
    icons::ARROW_LEFT,
    icons::ARROW_RIGHT,
    icons::ARROW_UP,
    icons::ASK,
    icons::BELL,
    icons::BELL_DOT,
    icons::BELL_SLASH,
    icons::BOLD,
    icons::BOOK,
    icons::BOOKS,
    icons::BRIEFCASE,
    icons::BRIEFCASE_FILLED,
    icons::BROWSER_EXPLORE,
    icons::BROWSER_WEB,
    icons::CALENDAR,
    icons::CHART,
    icons::CHAT_1,
    icons::CHAT_1_FILLED,
    icons::CHAT_2,
    icons::CHAT_2_FILLED,
    icons::CHAT_3,
    icons::CHAT_3_FILLED,
    icons::CHAT_4,
    icons::CHAT_4_FILLED,
    icons::CHECK,
    icons::CHEVRON_DOWN,
    icons::CHEVRON_LEFT,
    icons::CHEVRON_RIGHT,
    icons::CHEVRON_UP,
    icons::CIRCLE_LARGE,
    icons::CIRCLE_LARGE_FILLED,
    icons::CIRCLE_SMALL,
    icons::CIRCLE_SMALL_FILLED,
    icons::CLAUDE,
    icons::CLOSE,
    icons::CLOUD,
    icons::CODE,
    icons::CODE_REVIEW,
    icons::COLAB,
    icons::COLAB_FILLED,
    icons::COMMAND,
    icons::CONNECTORS,
    icons::COPY,
    icons::COPY_CODE,
    icons::COWORK,
    icons::CSV,
    icons::CSV_FILLED,
    icons::CSV_GREEN,
    icons::CSV_LETTER,
    icons::CSV_LETTER_FILLED,
    icons::CURSOR,
    icons::CURSOR_2,
    icons::CURSOR_FILLED,
    icons::DATABASE,
    icons::DATABASE_FLAT,
    icons::DEBUG,
    icons::DEBUG_ALT,
    icons::DESIGN,
    icons::DEVICE_MOBILE,
    icons::DIAGNOSTICS,
    icons::DIFF,
    icons::DIFF_MULTIPLE_1,
    icons::DIFF_MULTIPLE_2,
    icons::DISCARD,
    icons::DOCX,
    icons::DOCX_BLUE,
    icons::DOCX_FILLED,
    icons::DOWNLOAD,
    icons::DOWNLOAD_BOX,
    icons::DOWNLOAD_TRAY,
    icons::EDIT,
    icons::EDIT_1,
    icons::EDIT_2,
    icons::EDIT_WRITE,
    icons::ELLIPSIS,
    icons::ENTER,
    icons::ERASER,
    icons::ERROR,
    icons::EXPORT,
    icons::EXPORT_TRAY,
    icons::EXTENSIONS,
    icons::EYE,
    icons::EYE_FILLED,
    icons::FILE,
    icons::FILE_CODE,
    icons::FILE_DOWNLOADED,
    icons::FILE_TEXT,
    icons::FILES,
    icons::FILTER,
    icons::FOLD,
    icons::FOLDER_DOWNLOADED,
    icons::FOLDERS,
    icons::FORK,
    icons::GEAR,
    icons::GIT,
    icons::GIT_BRANCH,
    icons::GIT_COMMIT,
    icons::GIT_PULL_REQUEST,
    icons::GIT_PULL_REQUEST_CLOSED,
    icons::GIT_PULL_REQUEST_COMMENT,
    icons::GIT_PULL_REQUEST_DONE,
    icons::GIT_PULL_REQUEST_DRAFT,
    icons::GIT_PULL_REQUEST_ERROR,
    icons::GITHUB,
    icons::GO_TO_FILE,
    icons::H1,
    icons::H2,
    icons::H3,
    icons::H4,
    icons::H5,
    icons::HAND,
    icons::HISTORY,
    icons::HOME,
    icons::HOME_FILLED,
    icons::IMAGE,
    icons::IMAGE_FILLED,
    icons::INFO,
    icons::ITALICS,
    icons::KEBAB_VERTICAL,
    icons::KEYBOARD_TAB,
    icons::LAYOUT,
    icons::LAYOUT_PANEL_1,
    icons::LAYOUT_PANEL_OFF_1,
    icons::LAYOUT_SIDEBAR_LEFT_1,
    icons::LAYOUT_SIDEBAR_LEFT_2,
    icons::LAYOUT_SIDEBAR_LEFT_OFF_1,
    icons::LAYOUT_SIDEBAR_LEFT_OFF_2,
    icons::LAYOUT_SIDEBAR_RIGHT_1,
    icons::LAYOUT_SIDEBAR_RIGHT_2,
    icons::LAYOUT_SIDEBAR_RIGHT_OFF_1,
    icons::LAYOUT_SIDEBAR_RIGHT_OFF_2,
    icons::LEGEND,
    icons::LETTER_B,
    icons::LETTER_H,
    icons::LETTER_T,
    icons::LIBRARY,
    icons::LIBRARY_FILLED,
    icons::LIGHTING_FILLED,
    icons::LIGHTNING,
    icons::LIGHTNING_FILLED,
    icons::LINK_EXTERNAL,
    icons::LIST_FILTER,
    icons::LIST_UNORDERED,
    icons::MAP,
    icons::MAP_FILLED,
    icons::MAP_VERTICAL,
    icons::MAP_VERTICAL_FILLED,
    icons::MENU,
    icons::MIC,
    icons::MIC_FILLED,
    icons::MODEL,
    icons::MODEL_FILLED,
    icons::MOTION,
    icons::MULTITASK,
    icons::NEW_FILE,
    icons::NEW_FOLDER,
    icons::OPEN_PREVIEW,
    icons::OPENAI,
    icons::ORIGIN,
    icons::PAPERCLIP,
    icons::PARAMETERS,
    icons::PASS,
    icons::PASS_FILLED,
    icons::PAUSE,
    icons::PDF,
    icons::PDF_FILLED,
    icons::PDF_RED,
    icons::PEN,
    icons::PINNED,
    icons::PLAN,
    icons::PREVIEW,
    icons::PRIMITIVE_SQUARE,
    icons::PROJECTS,
    icons::PROJECTS_FILLED,
    icons::QUESTION,
    icons::QUOTE,
    icons::QUOTES,
    icons::REFRESH,
    icons::REMOTE,
    icons::REMOVE,
    icons::REMOVE_SMALL,
    icons::REPO_FETCH,
    icons::REPO_PULL,
    icons::REPO_PUSH,
    icons::RSS,
    icons::SANDBOX,
    icons::SAVE,
    icons::SCREEN_FULL,
    icons::SCREEN_NORMAL,
    icons::SEARCH,
    icons::SETTINGS,
    icons::SKILL,
    icons::SPARKLE,
    icons::SPARKLE_FILLED,
    icons::SPLIT_HORIZONTAL,
    icons::SPLIT_PAGE,
    icons::SPLIT_VERTICAL,
    icons::SQUARE,
    icons::STAR,
    icons::STAR_FILLED,
    icons::START,
    icons::STRAW,
    icons::SUMMARY,
    icons::SYMBOL_COLOR,
    icons::SYMBOL_COLOR_FILLED,
    icons::SYNC,
    icons::TABLE,
    icons::TAG,
    icons::TARGET,
    icons::TERMINAL,
    icons::TERMINAL_CMD,
    icons::TERMINAL_GIT_BASH,
    icons::TEXT,
    icons::TEXT_2,
    icons::TRANSLATE,
    icons::TRASH,
    icons::TRASH_FLAT,
    icons::TXT_LETTER,
    icons::TXT_LETTER_FILLED,
    icons::TYPOGRAPHY,
    icons::UNDERLINE,
    icons::UNFOLD,
    icons::UNLIMITED,
    icons::UNPIN,
    icons::VOICE_MODE,
    icons::WARNING,
    icons::WEBSITE,
    icons::WORKTREE,
    icons::WRITE,
    icons::XLS_GREEN,
    icons::XLS_LETTER,
    icons::XLS_LETTER_FILLED,
    icons::ZOOM_IN,
    icons::ZOOM_OUT,
];

#[cfg(test)]
#[rustfmt::skip]
pub(crate) const ALL_ARTWORK: &[(&str, IconDefinition)] = &[
    ("account", artwork::ACCOUNT),
    ("add", artwork::ADD),
    ("add-small", artwork::ADD_SMALL),
    ("agent", artwork::AGENT),
    ("agent-filled", artwork::AGENT_FILLED),
    ("align-center", artwork::ALIGN_CENTER),
    ("align-justified", artwork::ALIGN_JUSTIFIED),
    ("align-left", artwork::ALIGN_LEFT),
    ("align-right", artwork::ALIGN_RIGHT),
    ("appearance", artwork::APPEARANCE),
    ("archive", artwork::ARCHIVE),
    ("arrow-down", artwork::ARROW_DOWN),
    ("arrow-left", artwork::ARROW_LEFT),
    ("arrow-right", artwork::ARROW_RIGHT),
    ("arrow-up", artwork::ARROW_UP),
    ("ask", artwork::ASK),
    ("bell", artwork::BELL),
    ("bell-dot", artwork::BELL_DOT),
    ("bell-slash", artwork::BELL_SLASH),
    ("bold", artwork::BOLD),
    ("book", artwork::BOOK),
    ("books", artwork::BOOKS),
    ("briefcase", artwork::BRIEFCASE),
    ("briefcase-filled", artwork::BRIEFCASE_FILLED),
    ("browser-explore", artwork::BROWSER_EXPLORE),
    ("browser-web", artwork::BROWSER_WEB),
    ("calendar", artwork::CALENDAR),
    ("chart", artwork::CHART),
    ("chat-1", artwork::CHAT_1),
    ("chat-1-filled", artwork::CHAT_1_FILLED),
    ("chat-2", artwork::CHAT_2),
    ("chat-2-filled", artwork::CHAT_2_FILLED),
    ("chat-3", artwork::CHAT_3),
    ("chat-3-filled", artwork::CHAT_3_FILLED),
    ("chat-4", artwork::CHAT_4),
    ("chat-4-filled", artwork::CHAT_4_FILLED),
    ("check", artwork::CHECK),
    ("chevron-down", artwork::CHEVRON_DOWN),
    ("chevron-left", artwork::CHEVRON_LEFT),
    ("chevron-right", artwork::CHEVRON_RIGHT),
    ("chevron-up", artwork::CHEVRON_UP),
    ("circle-large", artwork::CIRCLE_LARGE),
    ("circle-large-filled", artwork::CIRCLE_LARGE_FILLED),
    ("circle-small", artwork::CIRCLE_SMALL),
    ("circle-small-filled", artwork::CIRCLE_SMALL_FILLED),
    ("claude", artwork::CLAUDE),
    ("close", artwork::CLOSE),
    ("cloud", artwork::CLOUD),
    ("code", artwork::CODE),
    ("code-review", artwork::CODE_REVIEW),
    ("colab", artwork::COLAB),
    ("colab-filled", artwork::COLAB_FILLED),
    ("command", artwork::COMMAND),
    ("connectors", artwork::CONNECTORS),
    ("copy", artwork::COPY),
    ("copy-code", artwork::COPY_CODE),
    ("cowork", artwork::COWORK),
    ("csv", artwork::CSV),
    ("csv-filled", artwork::CSV_FILLED),
    ("csv-green", artwork::CSV_GREEN),
    ("csv-letter", artwork::CSV_LETTER),
    ("csv-letter-filled", artwork::CSV_LETTER_FILLED),
    ("cursor", artwork::CURSOR),
    ("cursor-2", artwork::CURSOR_2),
    ("cursor-filled", artwork::CURSOR_FILLED),
    ("database", artwork::DATABASE),
    ("database-flat", artwork::DATABASE_FLAT),
    ("debug", artwork::DEBUG),
    ("debug-alt", artwork::DEBUG_ALT),
    ("design", artwork::DESIGN),
    ("device-mobile", artwork::DEVICE_MOBILE),
    ("diagnostics", artwork::DIAGNOSTICS),
    ("diff", artwork::DIFF),
    ("diff-multiple-1", artwork::DIFF_MULTIPLE_1),
    ("diff-multiple-2", artwork::DIFF_MULTIPLE_2),
    ("discard", artwork::DISCARD),
    ("docx", artwork::DOCX),
    ("docx-blue", artwork::DOCX_BLUE),
    ("docx-filled", artwork::DOCX_FILLED),
    ("download", artwork::DOWNLOAD),
    ("download-box", artwork::DOWNLOAD_BOX),
    ("download-tray", artwork::DOWNLOAD_TRAY),
    ("edit", artwork::EDIT),
    ("edit-1", artwork::EDIT_1),
    ("edit-2", artwork::EDIT_2),
    ("edit-write", artwork::EDIT_WRITE),
    ("ellipsis", artwork::ELLIPSIS),
    ("enter", artwork::ENTER),
    ("eraser", artwork::ERASER),
    ("error", artwork::ERROR),
    ("export", artwork::EXPORT),
    ("export-tray", artwork::EXPORT_TRAY),
    ("extensions", artwork::EXTENSIONS),
    ("eye", artwork::EYE),
    ("eye-filled", artwork::EYE_FILLED),
    ("file", artwork::FILE),
    ("file-code", artwork::FILE_CODE),
    ("file-downloaded", artwork::FILE_DOWNLOADED),
    ("file-text", artwork::FILE_TEXT),
    ("files", artwork::FILES),
    ("filter", artwork::FILTER),
    ("fold", artwork::FOLD),
    ("folder-downloaded", artwork::FOLDER_DOWNLOADED),
    ("folders", artwork::FOLDERS),
    ("fork", artwork::FORK),
    ("gear", artwork::GEAR),
    ("git", artwork::GIT),
    ("git-branch", artwork::GIT_BRANCH),
    ("git-commit", artwork::GIT_COMMIT),
    ("git-pull-request", artwork::GIT_PULL_REQUEST),
    ("git-pull-request-closed", artwork::GIT_PULL_REQUEST_CLOSED),
    ("git-pull-request-comment", artwork::GIT_PULL_REQUEST_COMMENT),
    ("git-pull-request-done", artwork::GIT_PULL_REQUEST_DONE),
    ("git-pull-request-draft", artwork::GIT_PULL_REQUEST_DRAFT),
    ("git-pull-request-error", artwork::GIT_PULL_REQUEST_ERROR),
    ("github", artwork::GITHUB),
    ("go-to-file", artwork::GO_TO_FILE),
    ("h1", artwork::H1),
    ("h2", artwork::H2),
    ("h3", artwork::H3),
    ("h4", artwork::H4),
    ("h5", artwork::H5),
    ("hand", artwork::HAND),
    ("history", artwork::HISTORY),
    ("home", artwork::HOME),
    ("home-filled", artwork::HOME_FILLED),
    ("image", artwork::IMAGE),
    ("image-filled", artwork::IMAGE_FILLED),
    ("info", artwork::INFO),
    ("italics", artwork::ITALICS),
    ("kebab-vertical", artwork::KEBAB_VERTICAL),
    ("keyboard-tab", artwork::KEYBOARD_TAB),
    ("layout", artwork::LAYOUT),
    ("layout-panel-1", artwork::LAYOUT_PANEL_1),
    ("layout-panel-off-1", artwork::LAYOUT_PANEL_OFF_1),
    ("layout-sidebar-left-1", artwork::LAYOUT_SIDEBAR_LEFT_1),
    ("layout-sidebar-left-2", artwork::LAYOUT_SIDEBAR_LEFT_2),
    ("layout-sidebar-left-off-1", artwork::LAYOUT_SIDEBAR_LEFT_OFF_1),
    ("layout-sidebar-left-off-2", artwork::LAYOUT_SIDEBAR_LEFT_OFF_2),
    ("layout-sidebar-right-1", artwork::LAYOUT_SIDEBAR_RIGHT_1),
    ("layout-sidebar-right-2", artwork::LAYOUT_SIDEBAR_RIGHT_2),
    ("layout-sidebar-right-off-1", artwork::LAYOUT_SIDEBAR_RIGHT_OFF_1),
    ("layout-sidebar-right-off-2", artwork::LAYOUT_SIDEBAR_RIGHT_OFF_2),
    ("legend", artwork::LEGEND),
    ("letter-b", artwork::LETTER_B),
    ("letter-h", artwork::LETTER_H),
    ("letter-t", artwork::LETTER_T),
    ("library", artwork::LIBRARY),
    ("library-filled", artwork::LIBRARY_FILLED),
    ("lighting-filled", artwork::LIGHTING_FILLED),
    ("lightning", artwork::LIGHTNING),
    ("lightning-filled", artwork::LIGHTNING_FILLED),
    ("link-external", artwork::LINK_EXTERNAL),
    ("list-filter", artwork::LIST_FILTER),
    ("list-unordered", artwork::LIST_UNORDERED),
    ("map", artwork::MAP),
    ("map-filled", artwork::MAP_FILLED),
    ("map-vertical", artwork::MAP_VERTICAL),
    ("map-vertical-filled", artwork::MAP_VERTICAL_FILLED),
    ("menu", artwork::MENU),
    ("mic", artwork::MIC),
    ("mic-filled", artwork::MIC_FILLED),
    ("model", artwork::MODEL),
    ("model-filled", artwork::MODEL_FILLED),
    ("motion", artwork::MOTION),
    ("multitask", artwork::MULTITASK),
    ("new-file", artwork::NEW_FILE),
    ("new-folder", artwork::NEW_FOLDER),
    ("open-preview", artwork::OPEN_PREVIEW),
    ("openai", artwork::OPENAI),
    ("origin", artwork::ORIGIN),
    ("paperclip", artwork::PAPERCLIP),
    ("parameters", artwork::PARAMETERS),
    ("pass", artwork::PASS),
    ("pass-filled", artwork::PASS_FILLED),
    ("pause", artwork::PAUSE),
    ("pdf", artwork::PDF),
    ("pdf-filled", artwork::PDF_FILLED),
    ("pdf-red", artwork::PDF_RED),
    ("pen", artwork::PEN),
    ("pinned", artwork::PINNED),
    ("plan", artwork::PLAN),
    ("preview", artwork::PREVIEW),
    ("primitive-square", artwork::PRIMITIVE_SQUARE),
    ("projects", artwork::PROJECTS),
    ("projects-filled", artwork::PROJECTS_FILLED),
    ("question", artwork::QUESTION),
    ("quote", artwork::QUOTE),
    ("quotes", artwork::QUOTES),
    ("refresh", artwork::REFRESH),
    ("remote", artwork::REMOTE),
    ("remove", artwork::REMOVE),
    ("remove-small", artwork::REMOVE_SMALL),
    ("repo-fetch", artwork::REPO_FETCH),
    ("repo-pull", artwork::REPO_PULL),
    ("repo-push", artwork::REPO_PUSH),
    ("rss", artwork::RSS),
    ("sandbox", artwork::SANDBOX),
    ("save", artwork::SAVE),
    ("screen-full", artwork::SCREEN_FULL),
    ("screen-normal", artwork::SCREEN_NORMAL),
    ("search", artwork::SEARCH),
    ("settings", artwork::SETTINGS),
    ("skill", artwork::SKILL),
    ("sparkle", artwork::SPARKLE),
    ("sparkle-filled", artwork::SPARKLE_FILLED),
    ("split-horizontal", artwork::SPLIT_HORIZONTAL),
    ("split-page", artwork::SPLIT_PAGE),
    ("split-vertical", artwork::SPLIT_VERTICAL),
    ("square", artwork::SQUARE),
    ("star", artwork::STAR),
    ("star-filled", artwork::STAR_FILLED),
    ("start", artwork::START),
    ("straw", artwork::STRAW),
    ("summary", artwork::SUMMARY),
    ("symbol-color", artwork::SYMBOL_COLOR),
    ("symbol-color-filled", artwork::SYMBOL_COLOR_FILLED),
    ("sync", artwork::SYNC),
    ("table", artwork::TABLE),
    ("tag", artwork::TAG),
    ("target", artwork::TARGET),
    ("terminal", artwork::TERMINAL),
    ("terminal-cmd", artwork::TERMINAL_CMD),
    ("terminal-git-bash", artwork::TERMINAL_GIT_BASH),
    ("text", artwork::TEXT),
    ("text-2", artwork::TEXT_2),
    ("translate", artwork::TRANSLATE),
    ("trash", artwork::TRASH),
    ("trash-flat", artwork::TRASH_FLAT),
    ("txt-letter", artwork::TXT_LETTER),
    ("txt-letter-filled", artwork::TXT_LETTER_FILLED),
    ("typography", artwork::TYPOGRAPHY),
    ("underline", artwork::UNDERLINE),
    ("unfold", artwork::UNFOLD),
    ("unlimited", artwork::UNLIMITED),
    ("unpin", artwork::UNPIN),
    ("voice-mode", artwork::VOICE_MODE),
    ("warning", artwork::WARNING),
    ("website", artwork::WEBSITE),
    ("worktree", artwork::WORKTREE),
    ("write", artwork::WRITE),
    ("xls-green", artwork::XLS_GREEN),
    ("xls-letter", artwork::XLS_LETTER),
    ("xls-letter-filled", artwork::XLS_LETTER_FILLED),
    ("zoom-in", artwork::ZOOM_IN),
    ("zoom-out", artwork::ZOOM_OUT),
];
