import { expect, test } from '@playwright/test';

test('four GitHub resources resolve through the protocol and expose safe keyboard-accessible cards', async ({ page }) => {
	const errors: string[] = [];
	page.on('pageerror', error => { errors.push(error.message); console.error(error.message); });
	await page.goto('/github.html');
	const repository = page.locator('main a[href="https://github.com/team/repo"]');
	const issue = page.locator('main a[href="https://github.com/team/repo/issues/7"]');
	const pr = page.locator('main a[href="https://github.com/team/repo/pull/8"]');
	const commit = page.locator('main a[href*="/commit/"]');
	await expect(repository).toHaveText('team/repo');
	await expect(issue).toHaveText('<img src=x onerror=alert(1)> · #7 · team/repo · Open');
	await expect(issue.locator('img')).toHaveCount(0);
	await expect(commit).toHaveText('Improve links · abcdef0 · team/repo · +12 −3');
	await expect(issue).toHaveAccessibleDescription(/Press F2/);
	await page.evaluate(() => window.ashGitHubIntegration.setVerbosity(false));
	await expect(issue).not.toHaveAttribute('aria-description');
	await page.evaluate(() => window.ashGitHubIntegration.setVerbosity(true));
	await expect(issue).toHaveAccessibleDescription(/Press F2/);
	await issue.focus();
	await page.keyboard.press('F2');
	const card = page.locator('.ash-github-resource-hover');
	await expect(card).toBeVisible();
	await expect(card.getByRole('link', { name: 'team/repo', exact: true })).toBeFocused();
	await expect(card.locator('.ash-github-hover-description')).toHaveText(/^Issue details .*…$/);
	await expect(card).toHaveAttribute('data-github-content', /Long description Long description/);
	expect(await page.evaluate(() => window.ashGitHubIntegration.accessibleContent('view' as import('../../../src/ash/platform/accessibility/browser/accessibleView.js').AccessibleViewType))).toContain('Long description '.repeat(30).trim());
	expect(await page.evaluate(() => window.ashGitHubIntegration.accessibleContent('help' as import('../../../src/ash/platform/accessibility/browser/accessibleView.js').AccessibleViewType))).toContain('Escape closes the card');
	await page.keyboard.press('Escape');
	await expect(issue).toBeFocused();
	await page.keyboard.press('Enter');
	await expect.poll(() => page.evaluate(() => window.ashGitHubIntegration.opened)).toEqual(['https://github.com/team/repo/issues/7']);
	await expect(pr).toHaveText('Fix GitHub links · #8 · team/repo · Draft');
	expect(await page.evaluate(() => window.ashGitHubIntegration.requests.filter(request => request.method === 'github/checks').length)).toBe(0);
	await pr.focus();
	await page.keyboard.press('F2');
	await page.keyboard.press('Tab');
	await page.keyboard.press('Tab');
	await expect(card.getByRole('link', { name: 'main', exact: true })).toBeFocused();
	await page.evaluate(() => window.ashGitHubIntegration.releaseChecks());
	await expect(pr).toContainText('Checks passed');
	await expect(card).toHaveAttribute('data-github-content', /main ← feature\/links\nChecks passed/);
	await expect(card.getByRole('link', { name: 'main', exact: true })).toBeFocused();
	await page.keyboard.press('Tab');
	await page.keyboard.press('Enter');
	await expect.poll(() => page.evaluate(() => window.ashGitHubIntegration.opened.at(-1))).toBe('https://github.com/contributor/fork/tree/feature%2Flinks');
	await page.keyboard.press('Escape');
	await commit.focus();
	await page.keyboard.press('F2');
	await expect(card).toContainText('Alex');
	await expect(card).toContainText('Commit description');
	await page.evaluate(() => window.ashGitHubIntegration.theme('highContrast'));
	await expect(card.getByRole('link', { name: 'team/repo', exact: true })).toBeFocused();
	expect(await card.getByRole('link', { name: 'team/repo', exact: true }).evaluate(element => getComputedStyle(element).outlineStyle)).not.toBe('none');
	await page.keyboard.press('Escape');
	await repository.focus();
	await page.keyboard.press('F2');
	await expect(card).toContainText('Default branch: main');
	await page.evaluate(() => window.ashGitHubIntegration.dispose());
	await expect(card).toHaveCount(0);
	expect(errors).toEqual([]);
});

test('a deleted fork leaves its branch as text while preserving the PR and target branch links', async ({ page }) => {
	await page.goto('/github.html?deletedSource');
	const pr = page.locator('main a[href="https://github.com/team/repo/pull/8"]');
	await expect(pr).toContainText('Draft');
	await pr.focus();
	await page.keyboard.press('F2');
	const card = page.locator('.ash-github-resource-hover');
	await expect(card).toBeVisible();
	await expect(card.getByRole('link', { name: 'feature/links', exact: true })).toHaveCount(0);
	await expect(card.locator('.ash-github-hover-branches')).toHaveText('main←feature/links');
	await expect(card.getByRole('link', { name: 'main', exact: true })).toHaveAttribute('href', 'https://github.com/team/repo/tree/main');
});

test('rerendering duplicate cached links and retiring requests preserves data ownership', async ({ page }) => {
	const errors: string[] = [];
	page.on('pageerror', error => { errors.push(error.message); console.error(error.message); });
	await page.goto('/github.html');
	const issue = page.locator('main a[href="https://github.com/team/repo/issues/7"]');
	await expect(issue).toContainText('Open');
	await page.evaluate(() => window.ashGitHubIntegration.render('[One](https://github.com/team/repo/issues/7) [Two](https://github.com/team/repo/issues/7) [Held](https://github.com/team/repo/issues/9)'));
	await expect(issue).toHaveCount(2);
	await expect(issue.nth(0)).toContainText('Open');
	await expect(issue.nth(1)).toContainText('Open');
	await expect.poll(() => page.evaluate(() => window.ashGitHubIntegration.requests.filter(request => request.method === 'github/issue/read' && request.params.number === 9).length)).toBe(1);
	await page.evaluate(() => window.ashGitHubIntegration.render('[Remaining](https://example.org/)'));
	await expect.poll(() => page.evaluate(() => window.ashGitHubIntegration.requests.filter(request => request.method === 'github/cancel').length)).toBeGreaterThan(0);
	await page.evaluate(() => window.ashGitHubIntegration.releaseIssue());
	await expect(page.locator('main')).not.toContainText('Old private issue');
	await expect(page.getByRole('link', { name: 'Remaining' })).toBeVisible();
	expect(errors).toEqual([]);
});
