import assert from 'node:assert/strict';
import { test } from 'mocha';
import { MenuId } from '../../../../../platform/actions/common/actions.js';
import { MenuService } from '../../../../../platform/actions/common/menuService.js';
import { IConfigurationService } from '../../../../../platform/configuration/common/configuration.js';
import { InMemoryConfigurationService } from '../../../../../platform/configuration/common/inMemoryConfigurationService.js';
import { ContextKeyService } from '../../../../../platform/contextkey/browser/contextKeyService.js';
import { InstantiationService } from '../../../../../platform/instantiation/common/instantiationService.js';
import { ActivityBarPosition, WorkbenchConfiguration } from '../../../../common/configuration.js';
import { CommandService } from '../../../../services/commands/common/commandService.js';
import { ActivityBarContextMenu, LayoutActionsContext } from '../../layoutActions.js';

test('layout commands and menus follow configuration changes in their own window', async () => {
	using configuration = new InMemoryConfigurationService();
	using context = new ContextKeyService();
	using contribution = new LayoutActionsContext(configuration, context);
	using otherConfiguration = new InMemoryConfigurationService();
	using otherContext = new ContextKeyService();
	using otherContribution = new LayoutActionsContext(otherConfiguration, otherContext);
	using services = new InstantiationService();
	services.registerInstance(IConfigurationService, configuration);
	using commands = new CommandService(services);
	const menus = new MenuService(commands, context);
	const positions = () => menus.getMenuActions(MenuId.ActivityBarPositionMenu).flatMap(([, actions]) => actions);
	const root = () => menus.getMenuActions(ActivityBarContextMenu).flatMap(([, actions]) => actions);
	assert.deepEqual(positions().map(action => [action.label, action.checked]), [['Default', true], ['Top', false], ['Bottom', false], ['Hidden', false]]);
	await positions().find(action => action.label === 'Top')!.run();
	assert.equal(configuration.getValue(WorkbenchConfiguration.activityBarLocation), ActivityBarPosition.TOP);
	assert.equal(otherConfiguration.getValue(WorkbenchConfiguration.activityBarLocation), ActivityBarPosition.DEFAULT);
	assert.equal(root().some(action => action.label === 'Activity Bar Size'), false);
	await commands.executeCommand('workbench.action.activityBarLocation.default');
	await commands.executeCommand('workbench.action.activityBar.size.compact');
	assert.equal(configuration.getValue(WorkbenchConfiguration.activityBarCompact), true);
	await root().find(action => action.label === 'Move Primary Side Bar Right')!.run();
	assert.equal(configuration.getValue(WorkbenchConfiguration.sideBarLocation), 'right');
	assert.equal(root().some(action => action.label === 'Move Primary Side Bar Left'), true);
	await commands.executeCommand('workbench.action.toggleSidebarPosition');
	assert.equal(configuration.getValue(WorkbenchConfiguration.sideBarLocation), 'left');
	await configuration.updateValue(WorkbenchConfiguration.activityBarLocation, ActivityBarPosition.HIDDEN);
	assert.equal(positions().find(action => action.label === 'Hidden')!.checked, true);
	context.setContext('isSessionsWindow', true);
	assert.equal(menus.getMenuActions(MenuId.CommandPalette).flatMap(([, actions]) => actions).some(action => action.id === 'workbench.action.activityBarLocation.top'), false);
	contribution.dispose();
	assert.equal(context.getValue('config.workbench.activityBar.location'), undefined);
	assert.equal(otherContext.getValue('config.workbench.activityBar.location'), ActivityBarPosition.DEFAULT);
});
