[package]
name = "ash-http-client"
version.workspace = true
edition.workspace = true
license-file.workspace = true
publish.workspace = true

[lib]
doctest = false
name = "ash_http_client"
path = "src/lib.rs"

[dependencies]
ash-async-utils = { workspace = true }
futures = { workspace = true }
httpdate = { workspace = true }
reqwest = { workspace = true, features = ["http2"] }
rustls = { workspace = true }
rustls-platform-verifier = { workspace = true }
tokio = { workspace = true, features = ["io-util", "sync", "macros", "rt-multi-thread"] }
tokio-rustls = { workspace = true }
ureq = { workspace = true }
url = { workspace = true }
zeroize = { workspace = true }

[target.'cfg(target_os = "android")'.dependencies]
rustls-native-certs = { workspace = true }

[dev-dependencies]
http-test-support = { package = "ash-http-test-support", path = "../http-test-support" }

[lints]
workspace = true
