import { expect, test } from '../../../automation/test.js';

test('Markdown extension owns preview commands and shares unsaved text across editor views', async ({ workbench, application }) => {
	const page = workbench.page;
	await workbench.quickaccess.runCommand('workbench.action.closeAllEditors');
	await page.keyboard.press('ControlOrMeta+N');
	const source = workbench.editors.groupAt(0);
	await source.editor.waitForEditorFocus();
	const transfer = await page.evaluateHandle(() => {
		const transfer = new DataTransfer();
		transfer.items.add(new File(['# Shared draft\n\nOriginal body'], 'draft.md', { type: 'text/markdown' }));
		return transfer;
	});
	// Exercise the public file-drop path, including in the disconnected Electron UI.
	await source.title.locator('.ash-tab-list:visible [role="tablist"]').dispatchEvent('drop', { dataTransfer: transfer });
	await transfer.dispose();
	await source.editor.waitForEditorContents(text => text.includes('# Shared draft'));
	await source.editor.waitForEditorFocus();
	const breadcrumb = source.title.getByRole('button', { name: 'Select editor: Text Editor', exact: true });
	await expect(breadcrumb).toBeVisible();
	const previewSide = source.title.locator('[data-action-id="markdown.showPreviewToSide"] button');
	await expect(previewSide).toHaveAttribute('aria-label', 'Open Preview to the Side');
	const split = source.title.locator('[data-action-id="workbench.action.splitEditor"] button');
	await expect(split).toHaveAttribute('aria-label', 'Split Right');
	await expect(split.locator('[data-ash-icon-id="split-horizontal"]')).toBeVisible();
	await source.title.locator('[data-action-id="markdown.reopenAsPreview"] button').click();
	const frame = source.content.frameLocator('iframe.ash-webview:visible');
	await expect(frame.getByRole('heading', { name: 'Shared draft', exact: true })).toBeVisible();
	await expect(source.tabs).toHaveCount(2);
	for (const theme of ['Ash High Contrast Dark', 'Ash High Contrast Light']) {
		await workbench.quickaccess.runCommand('workbench.action.selectTheme');
		await workbench.quickaccess.search(theme);
		await workbench.quickaccess.input.press('Enter');
		await expect(workbench.quickaccess.element).toHaveCount(0);
		const palette = await workbench.element.evaluate(element => {
			const style = getComputedStyle(element);
			return { foreground: style.getPropertyValue('--ash-editor-foreground').trim(), background: style.getPropertyValue('--ash-editor-background').trim() };
		});
		await expect(frame.locator('html')).toHaveCSS('--ash-editor-foreground', palette.foreground);
		await expect(frame.locator('html')).toHaveCSS('--ash-editor-background', palette.background);
		await expect(frame.locator('html')).not.toHaveCSS('background-color', 'rgba(0, 0, 0, 0)');
		await expect(frame.locator('html')).not.toHaveCSS('color', 'rgba(0, 0, 0, 0)');
		const selector = source.title.getByRole('button', { name: 'Select editor: Markdown Preview', exact: true });
		await selector.focus();
		await expect(selector).toHaveCSS('outline-style', 'solid');
		await expect(selector).not.toHaveCSS('outline-width', '0px');
	}
	await source.content.locator('iframe.ash-webview:visible').focus();
	await page.keyboard.press('Alt+F1');
	await expect(page.locator('.ash-accessible-view-content')).toHaveValue(/document preview[\s\S]*editor selector/u);
	await page.keyboard.press('Escape');
	await expect(source.content.locator('iframe.ash-webview:visible')).toBeFocused();
	await page.keyboard.press('Alt+F2');
	await expect(page.locator('.ash-accessible-view-content')).toHaveValue('# Shared draft\n\nOriginal body');
	await page.keyboard.press('Escape');
	const previewBreadcrumb = source.title.getByRole('button', { name: 'Select editor: Markdown Preview', exact: true });
	await previewBreadcrumb.focus();
	const editors = await workbench.menus.inspect(application, () => previewBreadcrumb.press('Enter'));
	expect(editors).toContainEqual(expect.objectContaining({ label: 'Markdown Preview', checked: true }));
	await workbench.menus.select(application, () => previewBreadcrumb.press('Enter'), ['Text Editor']);
	await source.editor.waitForEditorFocus();
	await source.editor.waitForEditorContents(text => text.includes('# Shared draft'));
	await page.keyboard.press('ControlOrMeta+End');
	await page.keyboard.insertText(' changed');
	await workbench.quickaccess.runCommand('markdown.showPreview');
	await expect(source.tabs).toHaveCount(3);
	await expect(frame.getByText('Original body changed', { exact: true })).toBeVisible();
	await workbench.quickaccess.runCommand('markdown.showSource');
	await expect(source.tabs).toHaveCount(3);
	await source.editor.waitForEditorFocus();
	await page.keyboard.press('ControlOrMeta+End');
	await page.keyboard.insertText(' live');
	await source.tabs.nth(2).click();
	await expect(frame.getByText('Original body changed live', { exact: true })).toBeVisible();
	await workbench.quickaccess.runCommand('markdown.showSource');
	await previewSide.click();
	await expect(workbench.editors.groups).toHaveCount(2);
	const side = workbench.editors.groupAt(1);
	await expect(side.content.frameLocator('iframe.ash-webview').getByRole('heading', { name: 'Shared draft', exact: true })).toBeVisible();
	const boxes = await workbench.editors.groups.evaluateAll(groups => groups.map(group => {
		const box = group.getBoundingClientRect();
		return { x: box.x, y: box.y, width: box.width };
	}));
	expect(boxes[1]!.x).toBeGreaterThanOrEqual(boxes[0]!.x + boxes[0]!.width);
	expect(Math.abs(boxes[1]!.y - boxes[0]!.y)).toBeLessThan(2);
	await side.title.locator('[data-action-id="workbench.action.splitEditor"] button').click();
	await expect(workbench.editors.groups).toHaveCount(3);
	await expect(workbench.editors.groupAt(2).content.frameLocator('iframe.ash-webview').getByRole('heading', { name: 'Shared draft', exact: true })).toBeVisible();
	const third = workbench.editors.groupAt(2);
	await page.keyboard.down('Alt');
	const splitDown = third.title.locator('[data-action-id="workbench.action.splitEditor"] button');
	await expect(splitDown).toHaveAttribute('aria-label', 'Split Down');
	await expect(splitDown.locator('[data-ash-icon-id="split-vertical"]')).toBeVisible();
	await splitDown.click();
	await page.keyboard.up('Alt');
	await expect(workbench.editors.groups).toHaveCount(4);
	const lower = workbench.editors.groupAt(3);
	await expect(lower.content.frameLocator('iframe.ash-webview').getByRole('heading', { name: 'Shared draft', exact: true })).toBeVisible();
	const thirdBox = await third.element.boundingBox();
	const lowerBox = await lower.element.boundingBox();
	expect(lowerBox!.y).toBeGreaterThanOrEqual(thirdBox!.y + thirdBox!.height);
	expect(Math.abs(lowerBox!.x - thirdBox!.x)).toBeLessThan(2);
});

test('Markdown tab menus reopen the clicked document while another tab is active', async ({ workbench, application }) => {
	const page = workbench.page;
	await workbench.quickaccess.runCommand('workbench.action.closeAllEditors');
	await page.keyboard.press('ControlOrMeta+N');
	const group = workbench.editors.groupAt(0);
	await group.editor.waitForEditorFocus();
	const transfer = await page.evaluateHandle(() => {
		const transfer = new DataTransfer();
		transfer.items.add(new File(['# First document'], 'first.md', { type: 'text/markdown' }));
		transfer.items.add(new File(['# Second document'], 'second.md', { type: 'text/markdown' }));
		return transfer;
	});
	await group.title.locator('.ash-tab-list:visible [role="tablist"]').dispatchEvent('drop', { dataTransfer: transfer });
	await transfer.dispose();
	await group.editor.waitForEditorContents(text => text.includes('# Second document'));
	await workbench.menus.select(application, () => group.tabs.filter({ hasText: 'first.md' }).click({ button: 'right' }), ['Open Preview']);
	const frame = group.content.frameLocator('iframe.ash-webview:visible');
	await expect(frame.getByRole('heading', { name: 'First document', exact: true })).toBeVisible();
	await expect(group.tabs).toHaveCount(4);
	await workbench.menus.select(application, () => group.tabs.filter({ hasText: 'second.md' }).click({ button: 'right' }), ['Reopen Editor With...']);
	await workbench.quickaccess.select('Markdown Preview');
	await expect(frame.getByRole('heading', { name: 'Second document', exact: true })).toBeVisible();
	await expect(group.tabs).toHaveCount(4);
	await workbench.menus.select(application, () => group.title.getByRole('button', { name: 'Select editor: Markdown Preview', exact: true }).click(), ['Text Editor']);
	await group.editor.waitForEditorContents(text => text.includes('# Second document'));
});
