import { runUnitTests } from './mocha.ts';

runUnitTests([
	'src/ash/base/test/common/event.test.js',
	'src/ash/editor/test/common/languageRegistry.test.js',
	'src/ash/platform/commands/test/common/commands.test.js',
	'src/ash/platform/extensions/test/**/*.test.js',
	'src/ash/platform/extensionHost/test/**/*.test.js',
	'src/ash/workbench/services/extensions/test/**/*.test.js',
	'src/ash/workbench/services/textMate/test/common/textMateGrammarService.test.js',
	'src/ash/workbench/services/textMate/test/common/textMateThemeProjection.test.js',
	'src/ash/workbench/contrib/codeEditor/test/browser/codeEditorPane.test.js',
	'src/ash/workbench/contrib/codeEditor/test/common/editorInput.test.js',
	'src/ash/workbench/contrib/preferences/test/browser/settings.test.js',
	'src/ash/workbench/services/debug/test/browser/debugService.test.js',
	'src/ash/workbench/services/debug/test/common/debugAdapterFactory.test.js',
	'src/ash/workbench/services/debug/test/common/launchConfiguration.test.js',
	'src/ash/workbench/services/extensionHost/test/**/*.test.js',
	'src/ash/workbench/services/language/test/common/languageFeaturesService.test.js',
	'src/ash/workbench/services/tasks/test/browser/taskService.test.js',
	'src/ash/workbench/services/testing/test/browser/testingService.test.js',
	'src/ash/workbench/services/untitled/test/common/browserUntitledTextEditorService.test.js',
	'src/ash/workbench/test/browser/appServerConnectionStateObserver.test.js',
	'src/ash/workbench/test/browser/workbench-theme.test.js',
	'src/ash/workbench/test/common/theme.test.js',
], false);
