load("//:defs.bzl", "ash_rust_binary", "ash_rust_crate")

ash_rust_crate(
    name = "app-server",
    crate_name = "ash_app_server",
    data = glob(["templates/**"]) + ["//crates/utils/audio:tests/fixtures/tone.wav", "//sdk/typescript:example/.ash-plugin/plugin.json", "//sdk/typescript:index.js", "//extensions:remote-ssh/src/extension.js", "//extensions:remote-ssh/package.json"],
    extra_aliases = {
        "//crates/collaboration-mode-templates": "collaboration_mode_templates",
        "//crates/screen-capture": "screen_capture",
    },
)

ash_rust_binary(
    name = "ash-app-server",
    crate_name = "ash_app_server",
    crate_root = "src/main.rs",
    deps = [":app-server"],
)
