import '../../../welcomeGettingStarted/browser/gettingStartedColors.js';
import '../../../../../sessions/contrib/creator/browser/widget/designToolsWidget.js';
import '../../../../../platform/theme/common/colors/baseColors.js';
import '../../../../../platform/theme/common/sizes/baseSizes.js';
import '../../../../../editor/common/core/editorColorRegistry.js';
import '../../../../../editor/browser/widget/multiDiffEditor/colors.js';
import '../../../../common/theme.js';
import '../../../chat/common/widget/chatColors.js';
import '../../../pdf/common/pdfColors.js';
import '../../../preferences/common/settingsEditorColorRegistry.js';
import '../../../terminal/common/terminalColorRegistry.js';
import '../../../../../sessions/common/theme.js';
import '../../../../../platform/theme/common/colors/chartsColors.js';
import '../../../../../platform/theme/common/colors/componentColors.js';
import '../../../../../platform/theme/common/colors/editorColors.js';
import '../../../../../platform/theme/common/colors/inputColors.js';
import '../../../../../platform/theme/common/colors/listColors.js';
import '../../../../../platform/theme/common/colors/menuColors.js';
import '../../../../../platform/theme/common/colors/minimapColors.js';
import '../../../../../platform/theme/common/colors/miscColors.js';
import '../../../../../platform/theme/common/colors/quickpickColors.js';
import '../../../../../platform/theme/common/colors/searchColors.js';
import { readFile, writeFile } from 'node:fs/promises';
import { resolve } from 'node:path';
import { test } from 'mocha';
import { Colors } from '../../../../../platform/theme/common/colorRegistry.js';
import { colorCssVariable } from '../../../../../platform/theme/common/colorUtils.js';
import { Sizes } from '../../../../../platform/theme/common/sizeRegistry.js';
import { asCssVariableName } from '../../../../../platform/theme/common/sizeUtils.js';

// Release tests run only through explicit selection, so ordinary validation never writes the manifest.
test('update the CSS variable manifest from registered colors and sizes', async () => {
	const path = resolve(process.cwd(), 'build/lib/stylelint/ash-known-variables.json');
	const variables = JSON.parse(await readFile(path, 'utf8'));
	variables.colors = Colors.getColors().map(({ id }) => colorCssVariable(id)).sort();
	variables.sizes = Sizes.getSizes().map(({ id }) => asCssVariableName(id)).sort();
	const registered = new Set([...variables.colors, ...variables.sizes]);
	variables.others = variables.others.filter((name: string) => !registered.has(name));
	await writeFile(path, `${JSON.stringify(variables, null, '\t')}\n`);
	console.log(`Updated ${variables.colors.length} colors and ${variables.sizes.length} sizes; review ${path}.`);
});
