[package]
name = "ash-collaboration-server"
version.workspace = true
edition.workspace = true
license-file.workspace = true
publish.workspace = true

[[bin]]
name = "ash-collaboration-server"
path = "src/main.rs"

[lib]
doctest = false
name = "ash_collaboration_server"
path = "src/lib.rs"

[dependencies]
process-hardening = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
ash-collaboration = { workspace = true }
call = { package = "ash-call", path = "../call" }
livekit-api = { package = "ash-livekit-api", path = "../livekit-api" }
ash-secrets = { workspace = true }
tokio = { workspace = true, features = ["rt-multi-thread", "time", "net"] }

[dev-dependencies]
tempfile = { workspace = true }

[lints]
workspace = true
