//! Model contracts grouped by identity, specification, message, invocation, and recorded facts.

mod accounting;
mod catalog;
mod context;
mod identity;
mod invocation;
mod message;
mod reasoning_effort;
mod settings;
mod usage;

pub use accounting::ModelBillingEvidence;
pub use accounting::ModelBillingRecord;
pub use accounting::ModelBillingScope;
pub use accounting::ModelCostLineItem;
pub use accounting::ModelInvocationOutcome;
pub use accounting::ModelInvocationRecord;
pub use accounting::ModelMoneyAmount;
pub use accounting::ModelReferenceCostReason;
pub use accounting::ModelReferenceCostRecord;
pub use accounting::ModelReferenceCostSummary;
pub use accounting::RatedModelCost;
pub use catalog::CapabilitySupport;
pub use catalog::ContextWindow;
pub use catalog::Model;
pub use catalog::ModelAccess;
pub use catalog::ModelAvailability;
pub use catalog::ModelCapabilities;
pub use catalog::ModelCatalogFreshness;
pub use catalog::ModelInfo;
pub use catalog::ModelLifecycle;
pub use catalog::ModelMetadataQuality;
pub use catalog::ModelPreset;
pub use context::ModelContextAllocation;
pub use context::ModelContextCategory;
pub use context::ModelContextCategoryUsage;
pub use context::ModelContextInspection;
pub use context::ModelContextSourceUsage;
pub use identity::InvalidModelIdentity;
pub use identity::ModelConnectionId;
pub use identity::ModelId;
pub use identity::ModelRef;
pub use identity::ProviderId;
pub use invocation::ModelOutputTransport;
pub use invocation::ModelRequest;
pub use invocation::ModelResponse;
pub use invocation::ModelResponseBilling;
pub use invocation::ModelSpeed;
pub use invocation::ModelStreamEvent;
pub use invocation::ReasoningConfig;
pub use invocation::ResponseItem;
pub use invocation::StopReason;
pub use message::ContentPart;
pub use message::ImageDetail;
pub use message::InputItem;
pub use message::Message;
pub use message::MessageRole;
pub use message::ReasoningState;
pub use message::ToolCall;
pub use message::ToolChoice;
pub use message::ToolDefinition;
pub use message::ToolResult;
pub use reasoning_effort::ModelReasoningEffortOption;
pub use reasoning_effort::ReasoningEffort;
pub use settings::ModelAcceleration;
pub use settings::ModelInputModality;
pub use settings::ModelReasoningSummary;
pub use settings::ModelServiceTier;
pub use settings::ModelSettings;
pub use settings::ModelToolOutputLimit;
pub use settings::ModelVerbosity;
pub use usage::ModelContextUsage;
pub use usage::ModelContextUsageSource;
pub use usage::ModelInputEstimate;
pub use usage::ModelUsage;
pub use usage::ModelUsageSummary;
pub use usage::ModelUsageTotal;
