[build]
target-dir = ".build/cargo"

[target.'cfg(all(windows, target_env = "msvc"))']
rustflags = ["-C", "link-arg=/STACK:8388608", "-C", "target-feature=+crt-static"]

# Cargo merges these flags with the MSVC flags above, which supply the stack size and static CRT.
# LLVM may emit code that triggers the Cortex-A53 erratum #843419 warning.
# Windows ARM64 does not support that processor, so suppress the warning.
[target.aarch64-pc-windows-msvc]
rustflags = ["-C", "link-arg=/arm64hazardfree"]

[target.'cfg(all(windows, target_env = "gnu"))']
rustflags = ["-C", "link-arg=-Wl,--stack,8388608"]

[env]
RUSTY_V8_MIRROR = { value = "third_party/.cache/v8", relative = true }
