import type { LanguagePackCatalog } from "../../../../platform/languagePacks/common/languagePacksService.js";
import { ASH_LOCALIZATION_CATALOG_VERSION } from "../../../../platform/languagePacks/common/languagePackContract.js";

const english: LanguagePackCatalog = {
	schemaVersion: 1,
	locale: "en",
	languageName: "English",
	localizedLanguageName: "English",
	catalogVersion: ASH_LOCALIZATION_CATALOG_VERSION,
	bundles: {
		ash: {
			'accessibility.helpTitle': 'Accessibility Help',
			'accessibility.viewTitle': 'Accessible View',
			'accessibility.close': 'Close',
			'accessibility.openHelpHint': 'Press Alt+F1 for accessibility help.',
			'accessibility.openHelp': 'Open Accessibility Help',
			'accessibility.openView': 'Open Accessible View',
			'accessibility.explorerVerbosityTitle': 'Explorer accessibility help',
			'accessibility.explorerVerbosityDescription': 'Announce how to open accessibility help when the file tree receives focus.',
			'accessibility.gettingStartedVerbosityTitle': 'Welcome accessibility help',
			'accessibility.gettingStartedVerbosityDescription': 'Announce how to open accessibility help when the Welcome page receives focus.',
			'accessibility.explorerTreeLabel': 'Workspace files',
			'accessibility.explorerVisibleFiles': 'Visible workspace files',
			'accessibility.explorerFolder': 'Folder',
			'accessibility.explorerFile': 'File',
			'accessibility.explorerHelp': 'Explorer\nUse the arrow keys to move through files and folders. Press Right Arrow to expand a folder and Left Arrow to collapse it. Press Enter to open a file. Press Ctrl+F to find loaded file names. Press Escape to close find. Press Alt+F2 to read the visible files.',
			'files.findInExplorer': 'Find files in Explorer',
			'accessibility.openEditorsVerbosityTitle': 'Open Editors accessibility help',
			'accessibility.openEditorsVerbosityDescription': 'Announce how to open accessibility help when the Open Editors list receives focus.',
			'files.openEditors.title': 'Open Editors',
			'files.openEditors.empty': 'No open editors',
			'files.openEditors.group': 'Group {0}',
			'files.openEditors.unsaved': 'Unsaved changes',
			'files.openEditors.close': 'Close {0}',
			'files.openEditors.focus': 'Focus Open Editors',
			'files.openEditors.help': 'Open Editors\nUse the arrow keys to move through open editors. Press Enter to activate an editor. Press Delete to close the focused editor. Press Alt+F2 to read the list.',
			'files.nesting.enabledTitle': 'File nesting',
			'files.nesting.enabledDescription': 'Group related files under a parent file in Explorer.',
			'files.nesting.patternsTitle': 'File nesting patterns',
			'files.nesting.patternsDescription': 'Match child files under a parent file. Use * and ${capture}; separate multiple child patterns with commas.',
			'files.nesting.parentPattern': 'Parent file pattern',
			'files.nesting.childPatterns': 'Child file patterns',
			'files.nesting.addPattern': 'Add pattern',
			'files.nesting.removePattern': 'Remove pattern',
			'files.nesting.incompletePattern': 'Enter both a parent and child pattern.',
			'files.nesting.duplicatePattern': 'Each parent pattern must be unique.',
			'files.revealInWindows': 'Reveal in File Explorer',
			'files.revealInMac': 'Reveal in Finder',
			'files.revealInLinux': 'Open Containing Folder',
			'files.dirtyOne': '1 unsaved file',
			'files.dirtyMany': '{0} unsaved files',
			'files.saveConflictTitle': 'File changed on disk',
			'files.saveConflictMessage': "Could not save '{0}' because the file changed on disk. Your unsaved changes are still open in the editor.",
			'files.saveFailedTitle': 'Could not save file',
			'files.saveFailedMessage': "Could not save '{0}': {1}. Your unsaved changes are still open in the editor.",
			'files.untitledFile': 'Untitled',
			'files.openBinaryAsText': 'Open as Read-Only Text',
			'files.binaryTextPreviewFailedTitle': 'Could not open text preview',
			'files.binaryTextPreviewFailed': 'Could not open a text preview of this file: {0}',
			'dialog.ok': 'OK',
			'dialog.confirm': 'Confirm',
			'dialog.cancel': 'Cancel',
			'workspaceTrust.question': 'Do you trust the files in this folder?',
			'workspaceTrust.detail': 'Folder: {0}\n\nTrusting this folder allows Ash to edit files, run commands, change the repository, and load project instructions and configuration. Read Only allows browsing, searching, and repository inspection.',
			'workspaceTrust.trust': 'Trust Folder & Enable Features',
			'workspaceTrust.readOnly': 'Open Read Only',
			'dialog.input': 'Input',
			'dialog.inputNumber': '{0}, field {1}',
			'dialog.saveFileTitle': 'Save File',
			'dialog.saveFileName': 'File name',
			'dialog.invalidFileName': 'Enter a file name without a path separator.',
			'dialog.openFileRequiresFolder': 'Open a folder to choose a file.',
			'dialog.chooseFile': 'Choose a file',
			'dialog.chooseFileType': 'Choose a file type',
			'dialog.openFolder': 'Open Folder',
			'dialog.select': 'Select',
			'dialog.deselect': 'Deselect',
			'dialog.finishSelection': 'Done',
			'dialog.addAnotherFolder': 'Add another folder?',
			'dialog.addFolder': 'Add Folder',
			'dialog.fileTypeMismatch': 'Choose a file name matching the selected file types.',
			'dialog.replaceExistingFile': 'Replace the existing file {0}?',
			'dialog.replaceFile': 'Replace',
			'dialog.saveTargetNotFile': 'Choose a file name, not a folder.',
			'workbench.folderOpenBlocked': 'Finish the active request before opening another folder.',
			'workbench.folderOpenBlockedDetail': 'The current Workspace was kept unchanged.',
			'dialog.warning': 'Warning',
			'dialog.error': 'Error',
			'dialog.information': 'Information',
			'collaboration.dialog.endpointTitle': 'Collaboration server',
			'collaboration.dialog.endpointMessage': "Enter a remote collaboration server URL, or leave it blank to use this Workbench's App Server.",
			'collaboration.dialog.tokenTitle': 'Collaboration token',
			'collaboration.dialog.tokenMessage': 'Enter the remote collaboration server bearer token.',
			'openAgentsWindow.systemWideFailed': 'Some system-wide shortcuts could not be registered ({0}); they may be used by another application.',
			'openAgentsWindow.systemWideWhenIgnored': 'The when condition is ignored for system-wide Open Agents Window shortcuts ({0}).',
			'releaseNotes.title': 'Release Notes',
			'releaseNotes.open': 'Show Release Notes',
			'releaseNotes.unavailable': '# Release notes unavailable\n\nThere are no release notes for this version.',
			'onboarding.commandCenter.tryoutTitle': 'Open Search commands',
			'onboarding.commandCenter.tryoutDescription': 'Open the command search. No command runs until you choose one.',
			'onboarding.stepProgress': 'Step {0} of {1}',
			'onboarding.dismiss': 'Dismiss',
			'onboarding.done': 'Done',
			'onboarding.next': 'Next',
			'onboarding.help': 'Use Tab to reach Next or Dismiss. Press Escape to close this guide.',
			'onboarding.tryoutUnavailable': 'This example is unavailable.',
			'onboarding.tryoutConfirm': 'Try it',
			'onboarding.tryout.run': 'Try Feature Example',
			'onboarding.enabled.title': 'Onboarding guides',
			'onboarding.enabled.description': 'Show eligible feature guides automatically. Manually started guides remain available.',
			'onboarding.run': 'Run Onboarding Guide',
			'onboarding.resetShownState': 'Reset Onboarding Shown State',
			"markdown.alert.note": "Note",
			"markdown.alert.tip": "Tip",
			"markdown.alert.important": "Important",
			"markdown.alert.warning": "Warning",
			"markdown.alert.caution": "Caution",
			"workbench.newUntitledFile": "New Untitled Text Editor",
			"workbench.openFile": "Open File...",
			"workbench.newFileFromTemplate": "New File from Template",
			"workbench.openFolder": "Open Folder...",
			"workbench.toggleDeveloperTools": "Developer: Toggle Developer Tools",
			'workbench.closeWindow': 'Close Window',
			'workbench.closeSaveFailed': 'The window could not close because its state was not saved.',
			'workbench.closeOtherWindows': 'Close Other Windows',
			'workbench.focusWindow': 'Focus Window',
			'workbench.zoomIn': 'Zoom In',
			'workbench.zoomOut': 'Zoom Out',
			'workbench.zoomReset': 'Reset Zoom',
			'workbench.switchWindow': 'Switch Window...',
			'workbench.quickSwitchWindow': 'Quick Switch Window',
			'workbench.toggleWindowAlwaysOnTop': 'Toggle Window Always on Top',
			'workbench.enableWindowAlwaysOnTop': 'Turn On Always on Top',
			'workbench.disableWindowAlwaysOnTop': 'Turn Off Always on Top',
			'workbench.toggleWindowTabsBar': 'Toggle Window Tabs Bar',
			'workbench.newWindowTab': 'New Window Tab',
			'workbench.showNextWindowTab': 'Show Next Window Tab',
			'workbench.showPreviousWindowTab': 'Show Previous Window Tab',
			'workbench.moveWindowTabToNewWindow': 'Move Window Tab to New Window',
			'workbench.mergeWindowTabs': 'Merge All Window Tabs',
			'workbench.zoomStatus': 'Zoom {0}; activate to reset',
			'workbench.zoomSettingTitle': 'Window zoom level',
			'workbench.zoomSettingDescription': 'Adjust the zoom level of desktop windows.',
			'settings.appearance.layout.description': 'Configure the Workbench layout and window zoom.',
			'workbench.untitledWindow': 'Untitled Window',
			'workbench.currentWindow': 'Current window',
			'workbench.switchWindowPlaceholder': 'Select a window',
			'workbench.installShellCommand': 'Install ash Command in PATH',
			'workbench.uninstallShellCommand': 'Uninstall ash Command from PATH',
			'workbench.shellCommandInstalled': 'The ash command is installed at {0}.',
			'workbench.shellCommandUninstalled': 'The ash command was removed from {0}.',
			'editorWelcome.openFolder': 'Open folder',
			'editorWelcome.cloneRepo': 'Clone repo',
			'editorWelcome.connectViaSsh': 'Connect via SSH',
			'editorWelcome.connectGitHub': 'Connect GitHub',
			'editorWelcome.actionUnavailable': '{0} is not available yet',
			'gettingStarted.title': 'Welcome',
			'gettingStarted.openWelcome': 'Welcome',
			'gettingStarted.recentProjects': 'Recent projects',
			'gettingStarted.accessibilityHelp': 'Welcome\nUse Tab and Shift+Tab to move between actions and recent projects. Press Enter to activate the focused item.',
			"workbench.browserFolderPermission": "Browser folder permission is required",
			"workbench.browserFolderFileExists": "File already exists",
			"workbench.browserFolderTargetExists": "Target file already exists",
			"workbench.serverFolderChoose": "Choose a server folder",
			"workbench.serverFolderSelect": "Select this folder",
			"workbench.serverFolderAuthorizeTitle": "Authorize Server Folder",
			"workbench.serverFolderAuthorizeMessage": "Allow this browser tab to open and change files in {0}?",
			"workbench.serverFolderAuthorizeDetail": "A folder outside the current permission scope also needs approval on the server computer.",
			"workbench.serverFolderAuthorizeButton": "Open Folder",
			"workbench.save": "Save",
			"workbench.newFile": "New File...",
			"workbench.newFileNoFolder": "Open a folder to create a file.",
			"workbench.newFileName": "New File Name",
			"workbench.newFileNamePlaceholder": "Enter a file name",
			"workbench.newFileInvalidName": "Enter a file name without path separators.",
			"workbench.newFileSelectFolder": "Select a folder for the new file",
			"workbench.explorerSymbolicLink": "Symbolic Link",
			"workbench.explorerUnknownFileType": "Unknown File Type",
			"workbench.explorerDecoratedFile": "{0}, {1}",
			"workbench.copyPath": "Copy Path",
			"workbench.downloadFile": "Download File...",
			"workbench.copyRelativePath": "Copy Relative Path",
			"workbench.copyPathNoFile": "Open a file to copy its path.",
			"workbench.copyPathUnsupported": "This editor does not have a file path.",
			"workbench.copyRelativePathOutsideWorkspace": "The file is outside the current workspace.",
			"workbench.closeEditor": "Close Editor",
			"workbench.closeOtherEditors": "Close Other Editors",
			"workbench.pinEditor": "Pin Editor",
			"workbench.unpinEditor": "Unpin Editor",
			"workbench.closeAllEditors": "Close All Editors",
			"workbench.navigateEditorBack": "Go Back",
			"workbench.navigateEditorForward": "Go Forward",
			"workbench.navigateBackInEditLocations": "Go Back in Edit Locations",
			"workbench.navigateForwardInEditLocations": "Go Forward in Edit Locations",
			"workbench.navigateBackInNavigationLocations": "Go Back in Navigation Locations",
			"workbench.navigateForwardInNavigationLocations": "Go Forward in Navigation Locations",
			"workbench.reopenClosedEditor": "Reopen Closed Editor",
			"workbench.nextRecentlyUsedEditor": "Open Next Recently Used Editor",
			"workbench.previousRecentlyUsedEditor": "Open Previous Recently Used Editor",
			"workbench.showAllEditors": "Show All Editors",
			"workbench.editorQuickAccessPlaceholder": "Select an open editor",
			"workbench.editorGroupNumber": "Group {0}",
			"workbench.editorPinnedTabHint": "Pinned tab. Double-click or press Alt+Enter to unpin.",
			"workbench.editorUnpinnedTabHint": "Double-click or press Alt+Enter to pin this tab.",
			"workbench.editorOpenRetry": "Retry",
			"workbench.editorOpenClose": "Close Editor",
			"workbench.editorOpenFailure": "Unable to open {0}",
			"workbench.editorOpenFailureGeneric": "Unable to open editor",
			"workbench.editorOpenUnknownError": "An unknown error occurred while opening this editor.",
			"workbench.editorOpenAsBinary": "Open as Binary",
			"workbench.editorTypePickerPlaceholder": "Select an editor",
			"workbench.reopenWithEditor": "Reopen Editor With...",
			"workbench.focusTerminal": "Focus Terminal",
			"workbench.settings": "Ash Settings",
			"workbench.openKeyboardShortcuts": "Preferences: Open Keyboard Shortcuts",
			"dropOrPaste.pasteAs": "Paste As...",
			"dropOrPaste.selectPasteAction": "Select Paste Action",
			"dropOrPaste.pasteOptions": "Paste options",
			"dropOrPaste.dropOptions": "Drop options",
			"dropOrPaste.selectorHelp": "Use arrow keys to choose an edit. Press Escape to return to the editor.",
			"dropOrPaste.plainText": "Insert Plain Text",
			"dropOrPaste.absolutePaths": "Insert Paths",
			"dropOrPaste.uris": "Insert URIs",
			"dropOrPaste.relativePaths": "Insert Relative Paths",
			"dropOrPaste.html": "Insert HTML",
			"dropOrPaste.richClipboardUnavailable": "Paste As requires clipboard read access.",
			"dropOrPaste.clipboardReadFailed": "Could not read the clipboard: {0}",
			"dropOrPaste.noPasteEdit": "No paste edit is available for this clipboard content.",
			"dropOrPaste.pasteFailed": "Could not paste: {0}",
			"dropOrPaste.dropFailed": "Could not drop content: {0}",
			"dropOrPaste.resolveFailed": "Could not resolve edit: {0}",
			"dropOrPaste.invalidEdit": "Could not prepare edit: {0}",
			"dropOrPaste.snippetUnavailable": "Snippet navigation is unavailable in this editor.",
			"dropOrPaste.applyFailed": "Could not apply edit: {0}",
			"dropOrPaste.switchFailed": "Could not change edit: {0}",
			"diffEditor.maxComputationTime.title": "Max computation time",
			"diffEditor.maxComputationTime.description": "Maximum time in milliseconds to compute a diff. Set to 0 for no time limit.",
			"diffEditor.incomplete": "Diff computation stopped after the time limit. Results may be incomplete.",
			"diffEditor.incompleteShort": "Diff may be incomplete",
			"diffEditor.original": "Original",
			"diffEditor.modified": "Modified",
			"diffEditor.ariaLabel": "Diff editor: {0} and {1}",
			"diffEditor.computing": "Computing differences",
			"diffEditor.error": "Could not compute differences: {0}",
			"diffEditor.noChanges": "No differences",
			"diffEditor.changeLocation": "Change {0} of {1}, {2}",
			"diffEditor.noOriginalLine": "no original line",
			"diffEditor.originalLine": "original line {0}",
			"diffEditor.noModifiedLine": "no modified line",
			"diffEditor.modifiedLine": "modified line {0}",
			"diffEditor.hiddenLines": "{0} hidden lines",
			"diffEditor.showMoreAbove": "Show {0} more lines above",
			"diffEditor.showMoreBelow": "Show {0} more lines below",
			"diffEditor.showAll": "Show all unchanged lines",
			"diffEditor.revealSymbol": "Go to {0}",
			"diffEditor.revealedLines": "Revealed {0} unchanged lines",
			"diffEditor.hideUnchanged.title": "Hide unchanged regions",
			"diffEditor.hideUnchanged.description": "Collapse long unchanged regions in a diff.",
			"diffEditor.hideUnchanged.contextTitle": "Context lines",
			"diffEditor.hideUnchanged.contextDescription": "Keep this many unchanged lines visible beside each change.",
			"diffEditor.hideUnchanged.minimumTitle": "Minimum hidden lines",
			"diffEditor.hideUnchanged.minimumDescription": "Only collapse a region when at least this many lines can be hidden.",
			"diffEditor.hideUnchanged.revealTitle": "Reveal lines",
			"diffEditor.hideUnchanged.revealDescription": "Show this many lines when expanding a collapsed region.",
			"multiDiffEditor.ariaLabel": "Multi-file diff editor with {0} files",
			"multiDiffEditor.changeLocation": "Change {0} of {1}, {2}",
			"multiDiffEditor.changeInFile": "Change in {0}",
			"multiDiffEditor.loadError": "Could not load {0}",
			"multiDiffEditor.loading": "Loading comparison",
			"multiDiffEditor.expandItem": "Expand {0}",
			"multiDiffEditor.collapseItem": "Collapse {0}",
			"trace.address": "Trace address",
			"trace.token": "Trace token",
			"trace.connect": "Connect",
			"trace.disconnect": "Disconnect",
			"trace.clear": "Clear",
			"trace.export": "Export filtered OTLP",
			"trace.help": "Help",
			"trace.filter": "Filter by name, outcome or trace ID",
			"trace.timeline": "Trace timeline",
			"trace.details": "Span details",
			"trace.hint": "Trace viewer. Press Alt+F1 for keyboard and connection help.",
			"trace.count": "{0} shown / {1} retained · {2} dropped",
			"trace.row": "{0} · {1} · +{2} ms · {3} ms",
			"trace.empty": "No spans. Connect, then perform an action in Ash.",
			"trace.helpTitle": "Trace viewer help",
			"trace.helpText": "Enable tracing before starting App Server: set ASH_TRACE_WEBSOCKET_ADDR to 127.0.0.1:4319 and ASH_TRACE_WEBSOCKET_TOKEN to a random 64-digit hexadecimal token. Enter that address and token here. Only new completed spans are received. Connect starts a new capture; Disconnect keeps the capture. Up to 2,000 spans and 8 MiB are retained; dropped spans are counted. Tab moves between controls. Arrow keys, Home and End select spans. The timeline gives each span’s name, result, relative start and duration as text; Span details contains selectable OTLP JSON with trace and parent IDs. Filtering also limits the OTLP export. Tokens and captures are kept only in this editor. Escape closes this help dialog.",
			"trace.succeeded": "Succeeded",
			"trace.failed": "Failed",
			"trace.cancelled": "Cancelled",
			"trace.disconnected": "Disconnected",
			"trace.connecting": "Connecting…",
			"trace.connected": "Connected · listening for completed spans",
			"trace.configurationError": "Use a loopback ws:// address with no query and a 64-digit hexadecimal token.",
			"trace.connectionError": "Connection failed. Check the running App Server, address and token.",
			"trace.protocolError": "Invalid trace stream. The connection was closed.",
			"trace.verbosity": "Trace viewer accessibility help",
			"trace.verbosityDescription": "Announce the keyboard help hint when the trace viewer receives focus.",
			"trace.title": "Trace viewer",
			"trace.open": "Developer: Open trace viewer",
			"quickInput.title": "Quick Pick",
			"quickInput.inputTitle": "Quick Input",
			"quickInput.results": "Quick Pick results",
			"quickInput.empty": "No matching results",
			"quickAccess.showAllCommands": "Show All Commands",
			"quickAccess.searchCommands": "Search commands (type >, @, or ? for modes)",
			"quickAccess.commands": "Commands",
			"quickAccess.commandPlaceholder": "Type the name of a command to run",
			"quickAccess.helpPlaceholder": "Select a search mode",
			"quickAccess.showModes": "Show Search Modes",
			"quickAccess.symbolPlaceholder": "Type the name of a symbol in the workspace",
			"quickAccess.workspaceSymbols": "Symbols in Workspace",
			"quickAccess.goToWorkspaceSymbol": "Go to Symbol in Workspace",
			"chat.settings.advisorAria": "Chat settings and advisor model",
			"chat.settings.advisorPlaceholder": "Choose an advisor model or open all settings",
			"chat.settings.advisorProviderRequired": "Configure a provider in Chat Settings to choose an advisor model",
			"chat.settings.openAll": "Open all settings",
			"chat.settings.advisorDisable": "Turn Advisor off",
			"chat.settings.advisorEnable": "Turn Advisor on",
			"chat.settings.advisorClear": "Clear saved Advisor model",
			"chat.settings.current": "Current",
			"chat.settings.advisorSaveFailed": "Could not save advisor model",
			"chat.settings.openCommand": "Open chat settings",
			"chat.providerKeys.manage": "Manage Model API Keys",
			"chat.providerKeys.aria": "Model provider API keys",
			"chat.providerKeys.select": "Choose a provider to enter or replace its API key",
			"chat.providerKeys.configured": "API key saved",
			"chat.providerKeys.missing": "API key required",
			"chat.providerKeys.optional": "No API key saved",
			"chat.providerKeys.inputTitle": "API key for {0}",
			"chat.providerKeys.inputPlaceholder": "Paste an API key",
			"chat.providerKeys.required": "Enter an API key",
			"chat.providerKeys.listFailed": "Could not load model providers",
			"chat.providerKeys.none": "No model providers accept API keys",
			"chat.providerKeys.saveFailed": "Could not save the API key",
			"chat.providerKeys.refreshFailed": "API key saved, but models could not be refreshed",
			"chat.providerKeys.saved": "API key saved for {0}",
			"chat.advisor.questionRequired": "Enter a question after /advisor",
			"chat.advisor.modelUnavailable": "Advisor model is unavailable: {0}",
			"chat.advisor.turnActive": "Wait for the active Turn to finish before starting a consultation",
			"chat.advisor.configure": "Configure an advisor model in Chat Settings before asking for a second opinion",
			"quickCommand.label": "Command Palette",
			"gotoSymbol.label": "Go to Symbol...",
			"gotoSymbol.dialog": "Go to Symbol",
			"gotoSymbol.placeholder": "Type a symbol name",
			"iPadShowKeyboard.label": "Show Keyboard",
			"gotoOffset": "Go to Offset...",
			"gotoOffset.dialog": "Go to Offset",
			"gotoOffset.input": "Character offset",
			"gotoOffset.placeholder": "Offset",
			"gotoLine": "Go to Line/Column...",
			"toggleMinimap": "Toggle Minimap",
			"context.minimap.enabled": "Minimap",
			"context.minimap.enabled.description": "Show a compact overview of the document.",
			"context.minimap.renderCharacters": "Render Characters",
			"context.minimap.renderCharacters.description": "Draw text characters in the minimap.",
			"context.minimap.size": "Vertical Size",
			"context.minimap.size.description": "Choose how the minimap uses the editor height.",
			"context.minimap.size.proportional": "Proportional",
			"context.minimap.size.fill": "Fill",
			"context.minimap.size.fit": "Fit",
			"context.minimap.slider": "Show Slider",
			"context.minimap.slider.description": "Choose when the minimap slider is visible.",
			"context.minimap.slider.mouseover": "Mouse Over",
			"context.minimap.slider.always": "Always",
			"context.minimap.side": "Side",
			"context.minimap.side.description": "Place the minimap on the left or right side of the editor.",
			"context.minimap.side.right": "Right",
			"context.minimap.side.left": "Left",
			"toggleRenderWhitespace": "Toggle Render Whitespace",
			"toggleRenderControlCharacters": "Toggle Control Characters",
			"toggle.wordwrap": "View: Toggle Word Wrap",
			"wordWrap.enabled": "Word wrap on",
			"wordWrap.disabled": "Word wrap off",
			"gotoLine.dialog": "Go to Line or Column",
			"gotoLine.input": "Line number and optional column",
			"gotoLine.placeholder": "Line[:Column]",
			"git.settings.group": "Source Control",
			"git.settings.groupDescription": "Configure Git fetching and Source Control diff decorations.",
			"git.autofetch.title": "Auto Fetch",
			"git.autofetch.description": "Periodically fetch updates for every open repository without changing local branches or files.",
			"git.autofetch.off": "Off",
			"git.autofetch.default": "Default remote",
			"git.autofetch.all": "All remotes",
			"git.autofetchPeriod.title": "Auto Fetch Period",
			"git.autofetchPeriod.description": "Seconds between automatic fetches for each repository.",
			"toggleHighContrast.label": "Toggle High Contrast Theme",
			"inspectTokens.label": "Developer: Inspect Tokens",
			"forceRetokenize": "Developer: Force Retokenize",
			"caret.moveLeft": "Move Selected Text Left",
			"caret.moveRight": "Move Selected Text Right",
			"insertFinalNewLine": "Insert Final New Line",
			"parameterHints.dialog": "Parameter hints",
			"parameterHints.navigation": "Use Up and Down to change the active signature. Press Escape to close.",
			"parameterHints.close": "Press Escape to close.",
			"inspectTokens.title": "Token details",
			"inspectTokens.language": "Language",
			"inspectTokens.scope": "Token type",
			"inspectTokens.modifiers": "Modifiers",
			"inspectTokens.foreground": "Foreground",
			"inspectTokens.analyzing": "Analyzing…",
			"inspectTokens.comment": "Comment",
			"inspectTokens.string": "String",
			"inspectTokens.regex": "Regular expression",
			"inspectTokens.other": "Other",
			"quickCommand.placeholder": "Type > for commands, ? for help, or @ for symbols",
			"quickHelp.dialog": "Quick Access Help",
			"quickHelp.placeholder": "Choose a command or type to filter",
			"folding.fold.description": "Collapse the selected folding ranges.",
			"folding.unfold.description": "Expand the selected folding ranges.",
			"folding.arguments": "Folding options",
			"folding.arguments.description": "levels sets the number of levels (default: 1). direction selects up or down. selectionLines supplies zero-based lines instead of the current selections. Fold without levels or direction finds the first expanded range at each line or above it.",
		},
		"ash.menu": {
			file: "File",
			edit: "Edit",
			selection: "Selection",
			view: "View",
			go: "Go",
			run: "Run",
			terminal: "Terminal",
			help: "Help",
		},
		"ash.actions": {
			openAgentsWindow: "Open Agents Window",
			openInAgents: "Open in Agents",
			openInAgentsWindow: "Open in Agents Window",
			showPrimarySidebar: "Show Primary Side Bar",
			hidePrimarySidebar: "Hide Primary Side Bar",
			showSecondarySidebar: "Show Secondary Side Bar",
			hideSecondarySidebar: "Hide Secondary Side Bar",
			showPanel: "Show Panel",
			hidePanel: "Hide Panel",
			maximizePanel: "Maximize Panel",
			restoreEditorArea: "Restore Editor Area",
			closePanel: "Close Panel",
		},
		"ash.views": {
			explorer: "Explorer",
			search: "Search",
			git: "Git",
			changes: "Changes",
			agentReview: "Agent Review",
			graph: "Graph",
			chat: "Chat",
			agent: "Agent",
			agentSessions: "Agent Sessions",
			problems: "Problems",
			output: "Output",
			terminal: "Terminal",
			testing: "Testing",
			tasks: "Tasks",
			runAndDebug: "Run and Debug",
			debugConsole: "Debug Console",
			ports: "Ports",
			refactorPreview: "Refactor Preview",
		},
		"ash.regions": {
			primarySidebar: "Primary sidebar",
			primarySidebarViews: "Primary side bar views",
			agentSidebar: "Agent sidebar",
			agentSidebarViews: "Agent sidebar views",
			auxiliarySidebar: "Auxiliary sidebar",
			auxiliarySidebarViews: "Auxiliary sidebar views",
			panel: "Panel",
			panelViews: "Panel views",
			additionalViews: "Additional views",
			applicationMenu: "Application menu",
			titleBarLeftActions: "Title bar left actions",
			searchCommands: "Search commands",
			editor: "Editor",
			editorActions: "Editor actions",
			openEditors: "Open editors",
			editorShortcuts: "Editor shortcuts",
		},
		"ash.marketplace": {
			searchMarketplace: "Search Marketplace",
			searchLanguageExtensions: "Search language extensions",
			searchPackages: "Search Plugins, Skills, MCPs…",
			browse: "Browse Marketplace",
			packageTypes: "Marketplace package types",
			filterAll: "All",
			filterPlugins: "Plugins",
			filterMcps: "MCPs",
			filterSkills: "Skills",
			filterLanguages: "Languages",
			filterLocalization: "Localization",
			filterThemes: "Themes",
			loading: "Loading Marketplace…",
			unavailable: "Marketplace unavailable.",
			noMatching: "No matching packages.",
			packageCount: "{count} package",
			packageCountPlural: "{count} packages",
			noTypeFound: "No {type} packages found",
			explore: "Explore Marketplace packages",
			tryDifferent: "Try a different search or clear the current filters.",
			installDescription: "Install Plugins, Skills, MCP servers, language support, and themes from the signed catalog.",
			clearFilters: "Clear filters",
			installed: "Installed · activation is separate",
			removalPending: "Removal pending",
			available: "Available",
			install: "Install",
			uninstall: "Uninstall",
			officialMcp: "Listed in the official MCP Registry · {name}@{version}",
			official: "Marketplace official package",
			thirdParty: "Third-party package",
			operationFailed: "Marketplace operation failed.",
		},
		"ash.settings": {
			"chrome.search": "Search settings",
			"chrome.categories": "Settings categories",
			"chrome.noResults": "No settings found.",
			"chrome.modalTitle": "Ash Settings",
			"displayLanguage.title": "Display Language",
			"displayLanguage.configure": "Configure Display Language",
			"displayLanguage.clearPreference": "Clear Display Language Preference",
			"displayLanguage.choose": "Select Display Language",
			"displayLanguage.current": "Current",
			"displayLanguage.installPack": "Install language pack",
			"displayLanguage.searchFailed": "Could not search language packs: {0}",
			"displayLanguage.noLocale": "The installed package contains no new display language.",
			"displayLanguage.changeFailed": "Could not change display language: {0}",
			"displayLanguage.description": "Choose the language used by the Ash interface.",
			"displayLanguage.restart": "Some interface areas update after reopening Settings.",
			"displayLanguage.builtin": "Built-in",
			"displayLanguage.marketplace": "Marketplace",
			"displayLanguage.installMore": "Install more languages from Marketplace",
			"displayLanguage.loading": "Loading available languages…",
			"displayLanguage.unavailable": "Marketplace language packs are unavailable.",
			"displayLanguage.install": "Install",
			"displayLanguage.installed": "Installed",
			"displayLanguage.select": "Interface language",
			"categories.general.label": "General",
			"categories.general.description": "Configure core application behavior and accessibility.",
			"categories.appearance.label": "Appearance",
			"categories.appearance.description": "Customize the visual appearance of Ash.",
			"categories.editor.label": "Editor",
			"categories.editor.description": "Configure text editing, fonts, search, and diff behavior.",
			"groups.agents.label": "Agents",
			"groups.agents.description": "Create agents and teams, then configure their shared capabilities.",
			"categories.agents.label": "My Agents",
			"categories.agents.description": "Manage reusable agents and their bounded subagent delegation.",
			"categories.teams.label": "Teams",
			"categories.teams.description": "Compose reusable multi-agent teams with explicit members, roles, and coordination.",
			"categories.agent-defaults.label": "Defaults",
			"categories.agent-defaults.description": "Choose the default agent and shared execution behavior.",
			"categories.models.label": "Models",
			"categories.models.description": "Choose models and configure model-specific behavior.",
			"categories.rules.label": "Rules",
			"categories.rules.description": "Configure the instructions and rules agents follow.",
			"categories.skills.label": "Skills",
			"categories.skills.description": "Manage reusable skills that agents can activate.",
			"categories.tools-and-mcps.label": "Tools & MCPs",
			"categories.tools-and-mcps.description": "Configure tools and Model Context Protocol connections.",
			"categories.hooks.label": "Hooks",
			"categories.hooks.description": "Configure automated actions around agent workflow events.",
		},
	},
};

const chinese: LanguagePackCatalog = {
	schemaVersion: 1,
	locale: "zh-CN",
	languageName: "Chinese (Simplified)",
	localizedLanguageName: "简体中文",
	catalogVersion: ASH_LOCALIZATION_CATALOG_VERSION,
	bundles: {
		ash: {
			'accessibility.helpTitle': '无障碍帮助',
			'accessibility.viewTitle': '无障碍视图',
			'accessibility.close': '关闭',
			'accessibility.openHelpHint': '按 Alt+F1 打开无障碍帮助。',
			'accessibility.openHelp': '打开无障碍帮助',
			'accessibility.openView': '打开无障碍视图',
			'accessibility.explorerVerbosityTitle': '资源管理器无障碍帮助',
			'accessibility.explorerVerbosityDescription': '文件树获得焦点时播报打开无障碍帮助的方法。',
			'accessibility.gettingStartedVerbosityTitle': '欢迎页无障碍帮助',
			'accessibility.gettingStartedVerbosityDescription': '欢迎页获得焦点时播报打开无障碍帮助的方法。',
			'accessibility.explorerTreeLabel': '工作区文件',
			'accessibility.explorerVisibleFiles': '可见的工作区文件',
			'accessibility.explorerFolder': '文件夹',
			'accessibility.explorerFile': '文件',
			'accessibility.explorerHelp': '资源管理器\n使用方向键浏览文件和文件夹。按右方向键展开文件夹，按左方向键折叠文件夹。按 Enter 打开文件。按 Ctrl+F 查找已加载的文件名。按 Escape 关闭查找。按 Alt+F2 阅读可见文件。',
			'files.findInExplorer': '在资源管理器中查找文件',
			'accessibility.openEditorsVerbosityTitle': '打开的编辑器无障碍帮助',
			'accessibility.openEditorsVerbosityDescription': '打开的编辑器列表获得焦点时播报打开无障碍帮助的方法。',
			'files.openEditors.title': '打开的编辑器',
			'files.openEditors.empty': '没有打开的编辑器',
			'files.openEditors.group': '第 {0} 组',
			'files.openEditors.unsaved': '未保存的更改',
			'files.openEditors.close': '关闭 {0}',
			'files.openEditors.focus': '聚焦打开的编辑器',
			'files.openEditors.help': '打开的编辑器\n使用方向键浏览编辑器。按 Enter 激活编辑器。按 Delete 关闭当前编辑器。按 Alt+F2 阅读列表。',
			'files.nesting.enabledTitle': '文件嵌套',
			'files.nesting.enabledDescription': '在资源管理器中把相关文件归入父文件。',
			'files.nesting.patternsTitle': '文件嵌套模式',
			'files.nesting.patternsDescription': '指定父文件和子文件的匹配模式。可使用 * 和 ${capture}；多个子文件模式用逗号分隔。',
			'files.nesting.parentPattern': '父文件模式',
			'files.nesting.childPatterns': '子文件模式',
			'files.nesting.addPattern': '添加模式',
			'files.nesting.removePattern': '删除模式',
			'files.nesting.incompletePattern': '请同时填写父文件模式和子文件模式。',
			'files.nesting.duplicatePattern': '父文件模式不能重复。',
			'files.revealInWindows': '在文件资源管理器中显示',
			'files.revealInMac': '在访达中显示',
			'files.revealInLinux': '打开所在文件夹',
			'files.dirtyOne': '1 个未保存的文件',
			'files.dirtyMany': '{0} 个未保存的文件',
			'files.saveConflictTitle': '磁盘上的文件已更改',
			'files.saveConflictMessage': '无法保存“{0}”，因为磁盘上的文件已更改。未保存的修改仍保留在编辑器中。',
			'files.saveFailedTitle': '无法保存文件',
			'files.saveFailedMessage': '无法保存“{0}”：{1}。未保存的修改仍保留在编辑器中。',
			'files.untitledFile': '未命名',
			'files.openBinaryAsText': '以只读文本打开',
			'files.binaryTextPreviewFailedTitle': '无法打开文本预览',
			'files.binaryTextPreviewFailed': '无法打开此文件的文本预览：{0}',
			'dialog.ok': '确定',
			'dialog.confirm': '确认',
			'dialog.cancel': '取消',
			'workspaceTrust.question': '是否信任此文件夹中的文件？',
			'workspaceTrust.detail': '文件夹：{0}\n\n信任此文件夹后，Ash 可以修改文件、运行命令、更改仓库，并加载项目提供的指令和配置。选择只读仍可浏览、搜索和查看仓库。',
			'workspaceTrust.trust': '信任文件夹并启用开发功能',
			'workspaceTrust.readOnly': '以只读模式打开',
			'dialog.input': '输入',
			'dialog.inputNumber': '{0}，第 {1} 个输入框',
			'dialog.saveFileTitle': '保存文件',
			'dialog.saveFileName': '文件名',
			'dialog.invalidFileName': '输入不含路径分隔符的文件名。',
			'dialog.openFileRequiresFolder': '打开文件夹后才能选择文件。',
			'dialog.chooseFile': '选择文件',
			'dialog.chooseFileType': '选择文件类型',
			'dialog.openFolder': '打开文件夹',
			'dialog.select': '选择',
			'dialog.deselect': '取消选择',
			'dialog.finishSelection': '完成',
			'dialog.addAnotherFolder': '继续添加文件夹？',
			'dialog.addFolder': '添加文件夹',
			'dialog.fileTypeMismatch': '文件名与所选文件类型不匹配。',
			'dialog.replaceExistingFile': '替换已有文件 {0}？',
			'dialog.replaceFile': '替换',
			'dialog.saveTargetNotFile': '请选择文件名，而不是文件夹。',
			'workbench.folderOpenBlocked': '完成当前请求后再打开其他文件夹。',
			'workbench.folderOpenBlockedDetail': '当前工作区未改变。',
			'dialog.warning': '警告',
			'dialog.error': '错误',
			'dialog.information': '信息',
			'collaboration.dialog.endpointTitle': '协作服务器',
			'collaboration.dialog.endpointMessage': '输入远程协作服务器 URL，或留空以使用此工作台的 App Server。',
			'collaboration.dialog.tokenTitle': '协作令牌',
			'collaboration.dialog.tokenMessage': '输入远程协作服务器的访问令牌。',
			'openAgentsWindow.systemWideFailed': '部分系统级快捷键无法注册（{0}）；它们可能已被其他应用占用。',
			'openAgentsWindow.systemWideWhenIgnored': '系统级“打开 Agents 窗口”快捷键会忽略 when 条件（{0}）。',
			'releaseNotes.title': '版本说明',
			'releaseNotes.open': '显示版本说明',
			'releaseNotes.unavailable': '# 暂无版本说明\n\n当前版本没有版本说明。',
			'onboarding.commandCenter.tryoutTitle': '打开搜索命令',
			'onboarding.commandCenter.tryoutDescription': '打开命令搜索。只有选择结果后才会运行命令。',
			'onboarding.stepProgress': '第 {0} 步，共 {1} 步',
			'onboarding.dismiss': '关闭引导',
			'onboarding.done': '完成',
			'onboarding.next': '下一步',
			'onboarding.help': '按 Tab 可移至“下一步”或“关闭引导”，按 Esc 关闭引导。',
			'onboarding.tryoutUnavailable': '此功能示例暂不可用。',
			'onboarding.tryoutConfirm': '试一试',
			'onboarding.tryout.run': '试用功能示例',
			'onboarding.enabled.title': '功能引导',
			'onboarding.enabled.description': '自动显示符合条件的功能引导。手动启动的引导仍可使用。',
			'onboarding.run': '启动功能引导',
			'onboarding.resetShownState': '重置已显示的功能引导',
			"markdown.alert.note": "备注",
			"markdown.alert.tip": "提示",
			"markdown.alert.important": "重要",
			"markdown.alert.warning": "警告",
			"markdown.alert.caution": "注意",
			"workbench.newUntitledFile": "新建无标题文本编辑器",
			"workbench.openFile": "打开文件...",
			"workbench.newFileFromTemplate": "从模板新建文件",
			"workbench.openFolder": "打开文件夹...",
			"workbench.toggleDeveloperTools": "开发者：切换开发者工具",
			'workbench.closeWindow': '关闭窗口',
			'workbench.closeSaveFailed': '窗口状态未能保存，因此无法关闭窗口。',
			'workbench.closeOtherWindows': '关闭其他窗口',
			'workbench.focusWindow': '聚焦窗口',
			'workbench.zoomIn': '放大',
			'workbench.zoomOut': '缩小',
			'workbench.zoomReset': '重置缩放',
			'workbench.switchWindow': '切换窗口...',
			'workbench.quickSwitchWindow': '快速切换窗口',
			'workbench.toggleWindowAlwaysOnTop': '切换窗口置顶',
			'workbench.enableWindowAlwaysOnTop': '窗口置顶',
			'workbench.disableWindowAlwaysOnTop': '取消窗口置顶',
			'workbench.toggleWindowTabsBar': '切换窗口标签栏',
			'workbench.newWindowTab': '新建窗口标签',
			'workbench.showNextWindowTab': '显示下一个窗口标签',
			'workbench.showPreviousWindowTab': '显示上一个窗口标签',
			'workbench.moveWindowTabToNewWindow': '将窗口标签移到新窗口',
			'workbench.mergeWindowTabs': '合并所有窗口标签',
			'workbench.zoomStatus': '缩放 {0}；激活后重置',
			'workbench.zoomSettingTitle': '窗口缩放级别',
			'workbench.zoomSettingDescription': '调整桌面窗口的缩放级别。',
			'settings.appearance.layout.description': '配置工作台布局和窗口缩放。',
			'workbench.untitledWindow': '无标题窗口',
			'workbench.currentWindow': '当前窗口',
			'workbench.switchWindowPlaceholder': '选择窗口',
			'workbench.installShellCommand': '在 PATH 中安装 ash 命令',
			'workbench.uninstallShellCommand': '从 PATH 中卸载 ash 命令',
			'workbench.shellCommandInstalled': 'ash 命令已安装到 {0}。',
			'workbench.shellCommandUninstalled': '已从 {0} 移除 ash 命令。',
			'editorWelcome.openFolder': '打开文件夹',
			'editorWelcome.cloneRepo': '克隆仓库',
			'editorWelcome.connectViaSsh': '通过 SSH 连接',
			'editorWelcome.connectGitHub': '连接 GitHub',
			'editorWelcome.actionUnavailable': '“{0}”暂不可用',
			'gettingStarted.title': '欢迎',
			'gettingStarted.openWelcome': '欢迎',
			'gettingStarted.recentProjects': '最近的项目',
			'gettingStarted.accessibilityHelp': '欢迎\n按 Tab 或 Shift+Tab 在操作和最近的项目之间移动。按 Enter 激活当前项目。',
			"workbench.browserFolderPermission": "需要授权访问浏览器文件夹",
			"workbench.browserFolderFileExists": "文件已存在",
			"workbench.browserFolderTargetExists": "目标文件已存在",
			"workbench.serverFolderChoose": "选择服务器上的文件夹",
			"workbench.serverFolderSelect": "选择此文件夹",
			"workbench.serverFolderAuthorizeTitle": "授权服务器文件夹",
			"workbench.serverFolderAuthorizeMessage": "允许此浏览器标签页打开和修改 {0} 中的文件吗？",
			"workbench.serverFolderAuthorizeDetail": "如果文件夹超出当前授权范围，还需要在服务器电脑上批准。",
			"workbench.serverFolderAuthorizeButton": "打开文件夹",
			"workbench.save": "保存",
			"workbench.newFile": "新建文件...",
			"workbench.newFileNoFolder": "打开文件夹后才能新建文件。",
			"workbench.newFileName": "新建文件名称",
			"workbench.newFileNamePlaceholder": "输入文件名",
			"workbench.newFileInvalidName": "请输入不含路径分隔符的文件名。",
			"workbench.newFileSelectFolder": "选择新文件所在的文件夹",
			"workbench.explorerSymbolicLink": "符号链接",
			"workbench.explorerUnknownFileType": "未知文件类型",
			"workbench.explorerDecoratedFile": "{0}，{1}",
			"workbench.copyPath": "复制路径",
			"workbench.downloadFile": "下载文件...",
			"workbench.copyRelativePath": "复制相对路径",
			"workbench.copyPathNoFile": "打开文件后才能复制其路径。",
			"workbench.copyPathUnsupported": "此编辑器没有文件路径。",
			"workbench.copyRelativePathOutsideWorkspace": "该文件不在当前工作区中。",
			"workbench.closeEditor": "关闭编辑器",
			"workbench.closeOtherEditors": "关闭其他编辑器",
			"workbench.pinEditor": "固定编辑器",
			"workbench.unpinEditor": "取消固定编辑器",
			"workbench.closeAllEditors": "关闭所有编辑器",
			"workbench.navigateEditorBack": "后退",
			"workbench.navigateEditorForward": "前进",
			"workbench.navigateBackInEditLocations": "返回上一编辑位置",
			"workbench.navigateForwardInEditLocations": "前往下一编辑位置",
			"workbench.navigateBackInNavigationLocations": "返回上一跳转位置",
			"workbench.navigateForwardInNavigationLocations": "前往下一跳转位置",
			"workbench.reopenClosedEditor": "重新打开已关闭的编辑器",
			"workbench.nextRecentlyUsedEditor": "打开下一个最近使用的编辑器",
			"workbench.previousRecentlyUsedEditor": "打开上一个最近使用的编辑器",
			"workbench.showAllEditors": "显示所有编辑器",
			"workbench.editorQuickAccessPlaceholder": "选择一个已打开的编辑器",
			"workbench.editorGroupNumber": "第 {0} 组",
			"workbench.editorPinnedTabHint": "已固定的标签。双击或按 Alt+Enter 可取消固定。",
			"workbench.editorUnpinnedTabHint": "双击或按 Alt+Enter 可固定此标签。",
			"workbench.editorOpenRetry": "重试",
			"workbench.editorOpenClose": "关闭编辑器",
			"workbench.editorOpenFailure": "无法打开 {0}",
			"workbench.editorOpenFailureGeneric": "无法打开编辑器",
			"workbench.editorOpenUnknownError": "打开此编辑器时发生未知错误。",
			"workbench.editorOpenAsBinary": "作为二进制文件打开",
			"workbench.editorTypePickerPlaceholder": "选择编辑器",
			"workbench.reopenWithEditor": "使用其他编辑器重新打开...",
			"workbench.focusTerminal": "聚焦终端",
			"workbench.settings": "Ash 设置",
			"workbench.openKeyboardShortcuts": "首选项：打开键盘快捷方式",
			"dropOrPaste.pasteAs": "选择性粘贴...",
			"dropOrPaste.selectPasteAction": "选择粘贴方式",
			"dropOrPaste.pasteOptions": "粘贴选项",
			"dropOrPaste.dropOptions": "拖放选项",
			"dropOrPaste.selectorHelp": "使用方向键选择编辑方式。按 Escape 返回编辑器。",
			"dropOrPaste.plainText": "插入纯文本",
			"dropOrPaste.absolutePaths": "插入路径",
			"dropOrPaste.uris": "插入 URI",
			"dropOrPaste.relativePaths": "插入相对路径",
			"dropOrPaste.html": "插入 HTML",
			"dropOrPaste.richClipboardUnavailable": "选择性粘贴需要读取剪贴板的权限。",
			"dropOrPaste.clipboardReadFailed": "无法读取剪贴板：{0}",
			"dropOrPaste.noPasteEdit": "此剪贴板内容没有可用的粘贴方式。",
			"dropOrPaste.pasteFailed": "无法粘贴：{0}",
			"dropOrPaste.dropFailed": "无法拖放内容：{0}",
			"dropOrPaste.resolveFailed": "无法解析编辑内容：{0}",
			"dropOrPaste.invalidEdit": "无法准备编辑：{0}",
			"dropOrPaste.snippetUnavailable": "此编辑器无法使用代码片段占位符导航。",
			"dropOrPaste.applyFailed": "无法应用编辑：{0}",
			"dropOrPaste.switchFailed": "无法切换编辑：{0}",
			"diffEditor.maxComputationTime.title": "最长计算时间",
			"diffEditor.maxComputationTime.description": "计算差异的最长时间（毫秒）。设为 0 则不限时。",
			"diffEditor.incomplete": "差异计算已达到时间上限，结果可能不完整。",
			"diffEditor.incompleteShort": "差异结果可能不完整",
			"diffEditor.original": "原始文件",
			"diffEditor.modified": "修改后的文件",
			"diffEditor.ariaLabel": "差异编辑器：{0} 与 {1}",
			"diffEditor.computing": "正在计算差异",
			"diffEditor.error": "无法计算差异：{0}",
			"diffEditor.noChanges": "没有差异",
			"diffEditor.changeLocation": "第 {0} 处差异，共 {1} 处，{2}",
			"diffEditor.noOriginalLine": "原始文件无对应行",
			"diffEditor.originalLine": "原始文件第 {0} 行",
			"diffEditor.noModifiedLine": "修改后文件无对应行",
			"diffEditor.modifiedLine": "修改后文件第 {0} 行",
			"diffEditor.hiddenLines": "隐藏 {0} 行",
			"diffEditor.showMoreAbove": "向上显示更多 {0} 行",
			"diffEditor.showMoreBelow": "向下显示更多 {0} 行",
			"diffEditor.showAll": "显示全部未修改的行",
			"diffEditor.revealSymbol": "跳转到 {0}",
			"diffEditor.revealedLines": "已显示 {0} 行未修改内容",
			"diffEditor.hideUnchanged.title": "隐藏未修改区域",
			"diffEditor.hideUnchanged.description": "折叠差异视图中较长的未修改区域。",
			"diffEditor.hideUnchanged.contextTitle": "上下文行数",
			"diffEditor.hideUnchanged.contextDescription": "在每处修改附近保留这些未修改的行。",
			"diffEditor.hideUnchanged.minimumTitle": "最少隐藏行数",
			"diffEditor.hideUnchanged.minimumDescription": "只有可隐藏的行数达到此值时才折叠。",
			"diffEditor.hideUnchanged.revealTitle": "展开行数",
			"diffEditor.hideUnchanged.revealDescription": "展开折叠区域时显示这些行。",
			"multiDiffEditor.ariaLabel": "多文件差异编辑器，共 {0} 个文件",
			"multiDiffEditor.changeLocation": "第 {0} 处差异，共 {1} 处，{2}",
			"multiDiffEditor.changeInFile": "{0} 中的差异",
			"multiDiffEditor.loadError": "无法加载 {0}",
			"multiDiffEditor.loading": "正在加载比较内容",
			"multiDiffEditor.expandItem": "展开 {0}",
			"multiDiffEditor.collapseItem": "折叠 {0}",
			"trace.address": "Trace 地址",
			"git.settings.group": "源代码管理",
			"git.settings.groupDescription": "配置 Git 自动获取和源代码管理差异标记。",
			"git.autofetch.title": "自动获取远端更新",
			"git.autofetch.description": "定期获取所有已打开仓库的远端更新，不更改本地分支或文件。",
			"git.autofetch.off": "关闭",
			"git.autofetch.default": "默认远端",
			"git.autofetch.all": "所有远端",
			"git.autofetchPeriod.title": "自动获取间隔",
			"git.autofetchPeriod.description": "每个仓库两次自动获取之间的秒数。",
			"trace.token": "Trace 令牌",
			"trace.connect": "连接",
			"trace.disconnect": "断开",
			"trace.clear": "清空",
			"trace.export": "导出筛选后的 OTLP",
			"trace.help": "帮助",
			"trace.filter": "按名称、结果或 Trace ID 筛选",
			"trace.timeline": "Trace 时间线",
			"trace.details": "Span 详情",
			"trace.hint": "Trace 查看器。按 Alt+F1 查看键盘操作和连接帮助。",
			"trace.count": "显示 {0} 条 / 保留 {1} 条 · 已丢弃 {2} 条",
			"trace.row": "{0} · {1} · +{2} 毫秒 · {3} 毫秒",
			"trace.empty": "暂无 span。连接后，在 Ash 中执行操作。",
			"trace.helpTitle": "Trace 查看器帮助",
			"trace.helpText": "启动 App Server 前开启采集：将 ASH_TRACE_WEBSOCKET_ADDR 设为 127.0.0.1:4319，将 ASH_TRACE_WEBSOCKET_TOKEN 设为随机的 64 位十六进制令牌。在此输入相同的地址和令牌。只接收连接后完成的 span。连接会开始新的采集；断开会保留已采集数据。最多保留 2,000 条 span 和 8 MiB，丢弃数量会显示。按 Tab 切换控件，用方向键、Home 和 End 选择 span。时间线以文字显示名称、结果、相对开始时间和耗时；Span 详情提供可选择复制的 OTLP JSON，包含 trace 和父 span ID。筛选也会限制导出的 OTLP 数据。令牌和采集数据只保存在当前编辑器中。按 Escape 关闭帮助。",
			"trace.succeeded": "成功",
			"trace.failed": "失败",
			"trace.cancelled": "已取消",
			"trace.disconnected": "已断开",
			"trace.connecting": "正在连接…",
			"trace.connected": "已连接 · 正在接收已完成的 span",
			"trace.configurationError": "请使用不带查询参数的本机回环 ws:// 地址，以及 64 位十六进制令牌。",
			"trace.connectionError": "连接失败。请检查 App Server 是否运行、地址和令牌是否正确。",
			"trace.protocolError": "Trace 数据格式无效，连接已关闭。",
			"trace.verbosity": "Trace 查看器无障碍帮助",
			"trace.verbosityDescription": "Trace 查看器获得焦点时朗读键盘帮助提示。",
			"trace.title": "Trace 查看器",
			"trace.open": "开发者：打开 Trace 查看器",
			"quickInput.title": "快速选择",
			"quickInput.inputTitle": "快速输入",
			"quickInput.results": "快速选择结果",
			"quickInput.empty": "没有匹配结果",
			"quickAccess.showAllCommands": "显示所有命令",
			"quickAccess.searchCommands": "搜索命令（输入 >、@ 或 ? 切换模式）",
			"quickAccess.commands": "命令",
			"quickAccess.commandPlaceholder": "输入要运行的命令名称",
			"quickAccess.helpPlaceholder": "选择搜索模式",
			"quickAccess.showModes": "显示搜索模式",
			"quickAccess.symbolPlaceholder": "输入工作区中的符号名称",
			"quickAccess.workspaceSymbols": "工作区中的符号",
			"quickAccess.goToWorkspaceSymbol": "转到工作区中的符号",
			"color.charts.foreground": "图表标签的前景色。",
			"color.charts.lines": "图表参考线的颜色。",
			"color.charts.red": "图表中红色数据系列的颜色。",
			"color.charts.blue": "图表中蓝色数据系列的颜色。",
			"color.charts.yellow": "图表中黄色数据系列的颜色。",
			"color.charts.orange": "图表中橙色数据系列的颜色。",
			"color.charts.green": "图表中绿色数据系列的颜色。",
			"color.charts.purple": "图表中紫色数据系列的颜色。",
			"color.input.foreground": "输入框文字的前景色。",
			"color.input.background": "输入框背景色。",
			"color.input.border": "输入框边框的颜色。",
			"color.input.placeholderForeground": "输入框占位文字的前景色。",
			"color.button.foreground": "默认按钮的前景色。",
			"color.button.border": "按钮明确显示轮廓时的边框颜色。",
			"color.button.background": "默认按钮的背景色。",
			"color.button.hoverBackground": "鼠标悬停时按钮的背景色。",
			"color.button.activeBackground": "按下按钮时的背景色。",
			"color.button.secondaryBackground": "次要按钮的背景色。",
			"color.button.primaryForeground": "主要按钮的前景色。",
			"color.button.primaryBackground": "主要按钮的背景色。",
			"color.button.primaryHoverBackground": "鼠标悬停时主要按钮的背景色。",
			"color.keybindingLabel.foreground": "快捷键标签的前景色。",
			"color.keybindingLabel.background": "快捷键标签的背景色。",
			"color.keybindingLabel.border": "快捷键标签的边框颜色。",
			"color.keybindingLabel.bottomBorder": "快捷键标签下边框的颜色。",
			"color.list.hoverBackground": "鼠标悬停时列表行的背景色。",
			"color.list.activeSelectionForeground": "列表中活动选中项的前景色。",
			"color.list.activeSelectionBackground": "列表中活动选中项的背景色。",
			"color.tree.indentGuidesStroke": "树形列表缩进引导线的颜色。",
			"color.menu.foreground": "命令菜单项的前景色。",
			"color.menu.selectionForeground": "选中菜单项的前景色。",
			"color.menu.selectionBackground": "选中菜单项的背景色。",
			"color.menu.background": "命令菜单的背景色。",
			"color.menu.hoverBackground": "鼠标悬停时菜单项的背景色。",
			"color.minimapSlider.background": "小地图视口滑块的背景色。",
			"color.minimapSlider.hoverBackground": "鼠标悬停时小地图视口滑块的背景色。",
			"color.minimapSlider.activeBackground": "拖动小地图视口滑块时的背景色。",
			"color.scrollbar.shadow": "编辑器滚动时显示的滚动条阴影颜色。",
			"color.scrollbar.sliderBackground": "滚动条滑块的背景色。",
			"color.scrollbar.sliderHoverBackground": "鼠标悬停时滚动条滑块的背景色。",
			"color.scrollbar.sliderActiveBackground": "拖动滚动条滑块时的背景色。",
			"color.sash.hoverBackground": "鼠标悬停时分隔条的背景色。",
			"color.quickInput.background": "快速选择面板的背景色。",
			"color.search.matchBackground": "搜索匹配内容的高亮背景色。",
			"color.selection.foreground": "选中文字的前景色。",
			"color.selection.background": "选中文字的背景色。",
			"color.textLink.activeForeground": "活动链接和编辑器中类似链接操作的前景色。",
			"color.contrastBorder": "高对比度主题中用于分隔元素的额外边框颜色。",
			"color.editor.background": "编辑器背景色。",
			"color.editor.foreground": "编辑器前景色。",
			"color.sectionHeader.foreground": "区域标题的前景色。",
			"color.workbench.background": "工作台背景色。",
			"color.editorGroup.border": "编辑器分组之间的边框颜色。",
			"color.editor.tabBackground": "未激活编辑器标签页的背景色。",
			"color.titleBar.background": "标题栏背景色。",
			"color.titleBar.foreground": "标题栏前景色。",
			"color.titleBar.actionForeground": "标题栏操作的前景色。",
			"color.titleBar.hoverBackground": "鼠标悬停时标题栏项目的背景色。",
			"color.commandCenter.foreground": "命令中心搜索文字和图标的颜色。",
			"color.commandCenter.background": "命令中心搜索框的背景色。",
			"color.commandCenter.border": "命令中心搜索框的边框颜色。",
			"color.commandCenter.hoverBackground": "鼠标悬停时命令中心搜索框的背景色。",
			"color.commandCenter.activeBorder": "命令中心搜索框激活时的边框颜色。",
			"color.sideBar.background": "主侧边栏背景色。",
			"color.auxiliaryBar.background": "辅助侧边栏背景色。",
			"color.panel.background": "面板背景色。",
			"color.compositeBar.foreground": "活动组合栏项目的前景色。",
			"color.compositeBar.inactiveForeground": "未激活组合栏项目的前景色。",
			"color.statusBar.foreground": "状态栏前景色。",
			"color.statusBar.background": "状态栏背景色。",
			"color.statusBarItem.hoverForeground": "鼠标悬停时状态栏项目的前景色。",
			"color.statusBarItem.hoverBackground": "鼠标悬停时状态栏项目的背景色。",
			"color.statusBarItem.compactHoverBackground": "紧凑状态栏分组中悬停项目的背景色。",
			"color.statusBarItem.activeBackground": "按下状态栏项目时的背景色。",
			"color.statusBarItem.remoteForeground": "远程状态栏项目的前景色。",
			"color.statusBarItem.remoteBackground": "远程状态栏项目的背景色。",
			"color.statusBarItem.remoteHoverForeground": "鼠标悬停时远程状态栏项目的前景色。",
			"color.statusBarItem.remoteHoverBackground": "鼠标悬停时远程状态栏项目的背景色。",
			"chat.settings.advisorAria": "聊天设置与顾问模型",
			"chat.settings.advisorPlaceholder": "选择顾问模型或打开所有设置",
			"chat.settings.advisorProviderRequired": "先在聊天设置中配置供应商，再选择顾问模型",
			"chat.settings.openAll": "打开所有设置",
			"chat.settings.advisorDisable": "关闭顾问",
			"chat.settings.advisorEnable": "开启顾问",
			"chat.settings.advisorClear": "清除已保存的顾问模型",
			"chat.settings.current": "当前选项",
			"chat.settings.advisorSaveFailed": "无法保存顾问模型",
			"chat.settings.openCommand": "打开聊天设置",
			"chat.providerKeys.manage": "管理模型 API 密钥",
			"chat.providerKeys.aria": "模型供应商 API 密钥",
			"chat.providerKeys.select": "选择要录入或替换 API 密钥的供应商",
			"chat.providerKeys.configured": "已保存 API 密钥",
			"chat.providerKeys.missing": "需要 API 密钥",
			"chat.providerKeys.optional": "未保存 API 密钥",
			"chat.providerKeys.inputTitle": "{0} 的 API 密钥",
			"chat.providerKeys.inputPlaceholder": "粘贴 API 密钥",
			"chat.providerKeys.required": "请输入 API 密钥",
			"chat.providerKeys.listFailed": "无法加载模型供应商",
			"chat.providerKeys.none": "没有可使用 API 密钥的模型供应商",
			"chat.providerKeys.saveFailed": "无法保存 API 密钥",
			"chat.providerKeys.refreshFailed": "API 密钥已保存，但无法刷新模型列表",
			"chat.providerKeys.saved": "已保存 {0} 的 API 密钥",
			"chat.advisor.questionRequired": "请在 /advisor 后输入问题",
			"chat.advisor.modelUnavailable": "顾问模型不可用：{0}",
			"chat.advisor.turnActive": "请等待当前轮次结束后再咨询顾问",
			"chat.advisor.configure": "请先在聊天设置中配置顾问模型，再请求第二意见",
			"quickCommand.label": "命令面板",
			"gotoSymbol.label": "转到符号...",
			"gotoSymbol.dialog": "转到符号",
			"gotoSymbol.placeholder": "输入符号名称",
			"iPadShowKeyboard.label": "显示键盘",
			"gotoOffset": "转到字符偏移量...",
			"gotoOffset.dialog": "转到字符偏移量",
			"gotoOffset.input": "字符偏移量",
			"gotoOffset.placeholder": "偏移量",
			"gotoLine": "转到行/列...",
			"toggleMinimap": "切换小地图",
			"context.minimap.enabled": "小地图",
			"context.minimap.enabled.description": "显示文档的紧凑概览。",
			"context.minimap.renderCharacters": "显示字符",
			"context.minimap.renderCharacters.description": "在小地图中绘制文本字符。",
			"context.minimap.size": "纵向尺寸",
			"context.minimap.size.description": "选择小地图如何使用编辑器高度。",
			"context.minimap.size.proportional": "按比例",
			"context.minimap.size.fill": "填充",
			"context.minimap.size.fit": "适应",
			"context.minimap.slider": "显示滑块",
			"context.minimap.slider.description": "选择小地图滑块何时可见。",
			"context.minimap.slider.mouseover": "鼠标悬停时",
			"context.minimap.slider.always": "始终显示",
			"context.minimap.side": "位置",
			"context.minimap.side.description": "将小地图放在编辑器左侧或右侧。",
			"context.minimap.side.right": "右侧",
			"context.minimap.side.left": "左侧",
			"toggleRenderWhitespace": "切换空白字符显示",
			"toggleRenderControlCharacters": "切换控制字符显示",
			"toggle.wordwrap": "视图: 切换自动换行",
			"wordWrap.enabled": "自动换行已开启",
			"wordWrap.disabled": "自动换行已关闭",
			"gotoLine.dialog": "转到行或列",
			"gotoLine.input": "行号及可选列号",
			"gotoLine.placeholder": "行[:列]",
			"toggleHighContrast.label": "切换高对比度主题",
			"inspectTokens.label": "开发者：检查词法单元",
			"forceRetokenize": "开发者：强制重新分词",
			"caret.moveLeft": "将选中文本左移",
			"caret.moveRight": "将选中文本右移",
			"insertFinalNewLine": "插入文件末尾换行符",
			"parameterHints.dialog": "参数提示",
			"parameterHints.navigation": "按上、下方向键切换当前签名，按 Escape 关闭。",
			"parameterHints.close": "按 Escape 关闭。",
			"inspectTokens.title": "词法单元详情",
			"inspectTokens.language": "语言",
			"inspectTokens.scope": "词法单元类型",
			"inspectTokens.modifiers": "修饰符",
			"inspectTokens.foreground": "前景色",
			"inspectTokens.analyzing": "正在分析…",
			"inspectTokens.comment": "注释",
			"inspectTokens.string": "字符串",
			"inspectTokens.regex": "正则表达式",
			"inspectTokens.other": "其他",
			"quickCommand.placeholder": "输入 > 查找命令、? 查看帮助，或 @ 查找符号",
			"quickHelp.dialog": "快速访问帮助",
			"quickHelp.placeholder": "选择命令或输入文字筛选",
			"folding.fold.description": "折叠选定的范围。",
			"folding.unfold.description": "展开选定的折叠范围。",
			"folding.arguments": "折叠选项",
			"folding.arguments.description": "levels 指定处理层数，默认为 1。direction 选择向上（up）或向下（down）。selectionLines 使用从 0 开始的行号替代当前选区。折叠时若不指定 levels 和 direction，则处理各行所在范围或其上层首个尚未折叠的范围。",
		},
		"ash.menu": {
			file: "文件",
			edit: "编辑",
			selection: "选择",
			view: "查看",
			go: "转到",
			run: "运行",
			terminal: "终端",
			help: "帮助",
		},
		"ash.actions": {
			openAgentsWindow: "打开 Agents 窗口",
			openInAgents: "在 Agents 中打开",
			openInAgentsWindow: "在 Agents 窗口中打开",
			showPrimarySidebar: "显示主侧栏",
			hidePrimarySidebar: "隐藏主侧栏",
			showSecondarySidebar: "显示辅助侧栏",
			hideSecondarySidebar: "隐藏辅助侧栏",
			showPanel: "显示面板",
			hidePanel: "隐藏面板",
			maximizePanel: "最大化面板",
			restoreEditorArea: "恢复编辑器区域",
			closePanel: "关闭面板",
		},
		"ash.views": {
			explorer: "资源管理器",
			search: "搜索",
			git: "Git",
			changes: "更改",
			agentReview: "Agent 审查",
			graph: "图表",
			chat: "聊天",
			agent: "Agent",
			agentSessions: "Agent 会话",
			problems: "问题",
			output: "输出",
			terminal: "终端",
			testing: "测试",
			tasks: "任务",
			runAndDebug: "运行和调试",
			debugConsole: "调试控制台",
			ports: "端口",
			refactorPreview: "重构预览",
		},
		"ash.regions": {
			primarySidebar: "主侧栏",
			primarySidebarViews: "主侧栏视图",
			agentSidebar: "Agent 侧栏",
			agentSidebarViews: "Agent 侧栏视图",
			auxiliarySidebar: "辅助侧栏",
			auxiliarySidebarViews: "辅助侧栏视图",
			panel: "面板",
			panelViews: "面板视图",
			additionalViews: "其他视图",
			applicationMenu: "应用程序菜单",
			titleBarLeftActions: "标题栏左侧操作",
			searchCommands: "搜索命令",
			editor: "编辑器",
			editorActions: "编辑器操作",
			openEditors: "打开的编辑器",
			editorShortcuts: "编辑器快捷方式",
		},
		"ash.marketplace": {
			searchMarketplace: "搜索 Marketplace",
			searchLanguageExtensions: "搜索语言扩展",
			searchPackages: "搜索插件、技能、MCP…",
			browse: "浏览 Marketplace",
			packageTypes: "Marketplace 软件包类型",
			filterAll: "全部",
			filterPlugins: "插件",
			filterMcps: "MCP",
			filterSkills: "技能",
			filterLanguages: "语言",
			filterLocalization: "界面语言",
			filterThemes: "主题",
			loading: "正在加载 Marketplace…",
			unavailable: "Marketplace 暂不可用。",
			noMatching: "没有匹配的软件包。",
			packageCount: "{count} 个软件包",
			packageCountPlural: "{count} 个软件包",
			noTypeFound: "未找到 {type} 软件包",
			explore: "探索 Marketplace 软件包",
			tryDifferent: "请尝试其他搜索词，或清除当前筛选条件。",
			installDescription: "从已签名目录安装插件、技能、MCP 服务、语言支持和主题。",
			clearFilters: "清除筛选条件",
			installed: "已安装 · 需单独激活",
			removalPending: "等待移除",
			available: "可安装",
			install: "安装",
			uninstall: "卸载",
			officialMcp: "已列入官方 MCP Registry · {name}@{version}",
			official: "Marketplace 官方软件包",
			thirdParty: "第三方软件包",
			operationFailed: "Marketplace 操作失败。",
		},
		"ash.settings": {
			"chrome.search": "搜索设置",
			"chrome.categories": "设置类别",
			"chrome.noResults": "未找到设置。",
			"chrome.modalTitle": "Ash 设置",
			"displayLanguage.title": "显示语言",
			"displayLanguage.configure": "配置显示语言",
			"displayLanguage.clearPreference": "清除显示语言偏好",
			"displayLanguage.choose": "选择显示语言",
			"displayLanguage.current": "当前使用",
			"displayLanguage.installPack": "安装语言包",
			"displayLanguage.searchFailed": "无法搜索语言包：{0}",
			"displayLanguage.noLocale": "安装的软件包没有新增可用的显示语言。",
			"displayLanguage.changeFailed": "无法切换显示语言：{0}",
			"displayLanguage.description": "选择 Ash 界面使用的语言。",
			"displayLanguage.restart": "部分界面将在重新打开设置后更新。",
			"displayLanguage.builtin": "内置",
			"displayLanguage.marketplace": "Marketplace",
			"displayLanguage.installMore": "从 Marketplace 安装更多语言",
			"displayLanguage.loading": "正在加载可用语言…",
			"displayLanguage.unavailable": "Marketplace 语言包暂时不可用。",
			"displayLanguage.install": "安装",
			"displayLanguage.installed": "已安装",
			"displayLanguage.select": "界面语言",
			"categories.general.label": "常规",
			"categories.general.description": "配置应用核心行为和辅助功能。",
			"categories.appearance.label": "外观",
			"categories.appearance.description": "自定义 Ash 的视觉外观。",
			"categories.editor.label": "编辑器",
			"categories.editor.description": "配置文本编辑、字体、搜索和差异显示。",
			"groups.agents.label": "Agent",
			"groups.agents.description": "创建 Agent 与团队，并配置它们共享的能力。",
			"categories.agents.label": "我的 Agent",
			"categories.agents.description": "管理可复用 Agent 及其受限的子 Agent 委托。",
			"categories.teams.label": "团队",
			"categories.teams.description": "通过明确的成员、角色与协调方式组合可复用的多 Agent 团队。",
			"categories.agent-defaults.label": "默认设置",
			"categories.agent-defaults.description": "选择默认 Agent 和共享执行行为。",
			"categories.models.label": "模型",
			"categories.models.description": "选择模型并配置模型特定行为。",
			"categories.rules.label": "规则",
			"categories.rules.description": "配置 Agent 遵循的指令和规则。",
			"categories.skills.label": "技能",
			"categories.skills.description": "管理 Agent 可激活的可复用技能。",
			"categories.tools-and-mcps.label": "工具与 MCP",
			"categories.tools-and-mcps.description": "配置工具和 Model Context Protocol 连接。",
			"categories.hooks.label": "Hooks",
			"categories.hooks.description": "配置 Agent 工作流事件前后的自动化操作。",
		},
	},
};

export const builtinLanguagePackCatalogs: readonly LanguagePackCatalog[] = [english, chinese];
