//! OpenAI/Codex backend business APIs, separate from model wire protocols.

mod account;
mod analytics;
mod analytics_types;
mod client;
mod config;
mod costs;
mod tasks;
mod usage;

pub use account::AccountEntry;
pub use account::AccountProfile;
pub use account::Accounts;
pub use account::CreditNudge;
pub use account::ProfileIdentity;
pub use account::ProfileInvocation;
pub use account::ProfileMetadata;
pub use account::ProfileStats;
pub use account::TokenUsageBucket;
pub use analytics::AnalyticsReport;
pub use analytics::AnalyticsResponse;
pub use analytics::PlanLimitBreakdown;
pub use analytics::PlanLimitHistory;
pub use analytics::PlanLimitPeriod;
pub use analytics::PlanLimitValue;
pub use analytics_types::ActiveUsersSummary;
pub use analytics_types::ClientActiveUsersCount;
pub use analytics_types::ClientWorkspaceUsageCount;
pub use analytics_types::ConsumptionUsageGroup;
pub use analytics_types::CreditUsageEventBySurface;
pub use analytics_types::CreditUsageEventsResponse;
pub use analytics_types::CurrentUserCreditUsageDatum;
pub use analytics_types::CurrentUserCreditUsageResponse;
pub use analytics_types::CurrentUserCreditUsageSeries;
pub use analytics_types::DailyProductSurfaceUsage;
pub use analytics_types::DailyProductSurfaceUsageResponse;
pub use analytics_types::DailySkillUsageMetricsResponse;
pub use analytics_types::DailySkillUsageOverview;
pub use analytics_types::DailyWorkspaceUsageCount;
pub use analytics_types::DailyWorkspaceUsageCountResponse;
pub use analytics_types::ModelActivitySummary;
pub use analytics_types::ModelUsage;
pub use analytics_types::PersonalUsageAttribution;
pub use analytics_types::PluginUsageBucket;
pub use analytics_types::PluginUsageMetricsResponse;
pub use analytics_types::PluginUsageOverview;
pub use analytics_types::ProductSurfacePremiumUsageValues;
pub use analytics_types::SkillUsageOverview;
pub use analytics_types::WorkspaceUsageCount;
pub use analytics_types::WorkspaceUsageGroup;
pub use client::BackendClient;
pub use client::CHATGPT_BACKEND_BASE_URL;
pub use client::RequestError;
pub use client::RouteStyle;
pub use config::ConfigBundle;
pub use config::DeliveredToml;
pub use config::ManagedLayers;
pub use config::TomlFragment;
pub use config::UserSettings;
pub use config::WorkspaceMessage;
pub use config::WorkspaceMessages;
pub use costs::ApiKeyResponseCost;
pub use costs::ApiKeyTurnCost;
pub use costs::ApiKeyTurnCostStatus;
pub use costs::ChatGptThreadCosts;
pub use costs::ChatGptTurnCost;
pub use costs::TaskUsage;
pub use costs::TaskUsageAmounts;
pub use costs::TaskUsageGroup;
pub use costs::TaskUsageResponse;
pub use costs::TaskUsageStatus;
pub use costs::TaskUsageThread;
pub use costs::ThreadUsage;
pub use costs::ThreadUsageGroup;
pub use tasks::GitPullRequest;
pub use tasks::SiblingTurns;
pub use tasks::TaskAuthor;
pub use tasks::TaskContent;
pub use tasks::TaskDetails;
pub use tasks::TaskDiff;
pub use tasks::TaskError;
pub use tasks::TaskItem;
pub use tasks::TaskList;
pub use tasks::TaskListItem;
pub use tasks::TaskListQuery;
pub use tasks::TaskMetadata;
pub use tasks::TaskPullRequest;
pub use tasks::TaskTurn;
pub use tasks::TaskWorklog;
pub use tasks::TaskWorklogContent;
pub use tasks::TaskWorklogMessage;
pub use usage::CreditBalance;
pub use usage::RateLimit;
pub use usage::RateLimitReached;
pub use usage::RateLimitStatus;
pub use usage::RateLimitWindow;
pub use usage::RateLimits;
pub use usage::ResetCredit;
pub use usage::ResetCreditCode;
pub use usage::ResetCreditResult;
pub use usage::ResetCreditSelection;
pub use usage::ResetCredits;
pub use usage::ResetCreditsSummary;
pub use usage::SpendControl;
pub use usage::SpendLimit;

#[cfg(test)]
mod test_support;

#[cfg(test)]
mod transport_tests;
