import type { GitCompareChangesParams, GitCompareChangesResult, GitCommitMessageResult, GitCommitDetailsResult } from '../../../../../.build/protocol/typescript/index.js';
import type { GitInitParams, GitCatalogResult, GitCommandParams, GitCommandResult, GitIndexDiffResult, GitIndexEditParams } from '../../../../../.build/protocol/typescript/index.js';
import type { ConfigCommandResult, ConfigReadResult, ConfigUpdateParams, GitBranchListResult, GitBranchSwitchParams, GitChangeFileParams, GitChangeFileResult, GitConflictFileParams, GitConflictFileResult, GitCompleteConflictParams, GitCloneParams, GitCloneResult, GitCommitChangesParams, GitCommitChangesResult, GitCommitFileParams, GitCommitFileResult, GitCommitParams, GitCommitResult, GitFetchParams, GitGraphParams, GitGraphResult, GitHistoryResult, GitOperationResult, GitPathsParams, GitRepositoriesResult, GitRepositoryParams, GitStatusResult } from "../../../../../.build/protocol/typescript/index.js";
import type { GitCheckIgnoreParams, GitCheckIgnoreResult } from '../../../../../.build/protocol/typescript/index.js';
import type { CancellationToken } from '../../../base/common/cancellation.js';
import type { GitBranchCreateParams, GitBranchDeleteParams, GitWorktreeCreateParams, GitWorktreeCreateResult, GitWorktreeDeleteParams, GitWorktreeListResult, GitWorktreeResolveParams, GitWorktreeResolveResult } from '../../../../../.build/protocol/typescript/index.js';

export interface IGitApi {
	initialize(params: GitInitParams): Promise<GitRepositoriesResult>;
	catalog(params: GitRepositoryParams): Promise<GitCatalogResult>;
	executeCommand(params: GitCommandParams): Promise<GitCommandResult>;
	indexDiff(params: GitChangeFileParams): Promise<GitIndexDiffResult>;
	editIndex(params: GitIndexEditParams): Promise<GitOperationResult>;
	clone(params: GitCloneParams): Promise<GitCloneResult>;
	readConfig(): Promise<ConfigReadResult>;
	updateConfig(params: ConfigUpdateParams): Promise<ConfigCommandResult>;
	repositories(): Promise<GitRepositoriesResult>;
	status(params: GitRepositoryParams): Promise<GitStatusResult>;
	checkIgnore(params: Omit<GitCheckIgnoreParams, 'operationId'>, token?: CancellationToken): Promise<GitCheckIgnoreResult>;
	history(params: GitRepositoryParams): Promise<GitHistoryResult>;
	branches(params: GitRepositoryParams): Promise<GitBranchListResult>;
	createBranch(params: GitBranchCreateParams): Promise<GitBranchListResult>;
	deleteBranch(params: GitBranchDeleteParams): Promise<GitBranchListResult>;
	switchBranch(params: GitBranchSwitchParams): Promise<GitOperationResult>;
	worktrees(params: GitRepositoryParams): Promise<GitWorktreeListResult>;
	createWorktree(params: GitWorktreeCreateParams): Promise<GitWorktreeCreateResult>;
	deleteWorktree(params: GitWorktreeDeleteParams): Promise<GitWorktreeListResult>;
	resolveWorktree(params: GitWorktreeResolveParams): Promise<GitWorktreeResolveResult>;
	graph(params: GitGraphParams): Promise<GitGraphResult>;
	compareChanges(params: GitCompareChangesParams): Promise<GitCompareChangesResult>;
	commitMessage(params: GitCommitChangesParams): Promise<GitCommitMessageResult>;
	commitDetails(params: GitCommitChangesParams): Promise<GitCommitDetailsResult>;
	commitChanges(params: GitCommitChangesParams): Promise<GitCommitChangesResult>;
	commitFile(params: GitCommitFileParams): Promise<GitCommitFileResult>;
	changeFile(params: GitChangeFileParams): Promise<GitChangeFileResult>;
	conflictFile(params: GitConflictFileParams): Promise<GitConflictFileResult>;
	completeConflict(params: GitCompleteConflictParams): Promise<GitOperationResult>;
	stage(params: GitPathsParams): Promise<GitOperationResult>;
	unstage(params: GitPathsParams): Promise<GitOperationResult>;
	discardWorktree(params: GitPathsParams): Promise<GitOperationResult>;
	commit(params: GitCommitParams): Promise<GitCommitResult>;
	fetch(params: GitFetchParams): Promise<GitOperationResult>;
	pull(params: GitRepositoryParams): Promise<GitOperationResult>;
	push(params: GitRepositoryParams): Promise<GitOperationResult>;
}
