[package]
name = "ash-extensions"
version.workspace = true
edition.workspace = true
license-file.workspace = true
publish.workspace = true

[lib]
name = "extensions"

[dependencies]
extension-protocol = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
thiserror = { workspace = true }

[dev-dependencies]
host = { package = "ash-editor-extension-host", path = "../editor-extension-host" }

[lints]
workspace = true
