import { expect, test } from '../../../automation/test.js';
import { readFile } from 'node:fs/promises';

test.use({ openWorkspace: false });

test('browser opens an authorized local folder and saves its files', async ({ target, workbench }) => {
	test.skip(target.kind !== 'browser' || target.workbenchMode !== 'code' || target.appServerMode !== 'disabled', 'This scenario requires the standalone Code browser');
	const page = workbench.page;
	const folderName = await page.evaluate(async () => {
		const root = await navigator.storage.getDirectory();
		const name = `ash-browser-%中-${crypto.randomUUID()}`;
		const folder = await root.getDirectoryHandle(name, { create: true });
		await folder.getDirectoryHandle('src', { create: true });
		const file = await folder.getFileHandle('hello %中.txt', { create: true });
		const writable = await file.createWritable();
		await writable.write('first value');
		await writable.close();
		Object.defineProperty(window, 'showDirectoryPicker', { configurable: true, value: async () => folder });
		return name;
	});
	await page.getByRole('button', { name: 'Application menu' }).click();
	await page.getByRole('menu').first().getByRole('menuitem', { name: 'File' }).click();
	await expect(page.getByRole('menu').last().getByRole('menuitem', { name: 'Open Folder...' })).toHaveCount(1);
	await page.keyboard.press('Escape');
	await page.keyboard.press('Escape');

	const showSidebar = page.getByRole('button', { name: 'Show Primary Side Bar', exact: true });
	if (await showSidebar.isVisible()) await showSidebar.click();
	await page.getByRole('button', { name: 'Open Folder', exact: true }).click();
	const explorer = page.locator('.ash-explorer');
	const fileRow = explorer.locator('.ash-tree-row').filter({ hasText: 'hello %中.txt' });
	await expect(fileRow).toHaveCount(1);
	if (await showSidebar.isVisible()) await showSidebar.click();
	await expect(explorer).toBeVisible();
	await expect(fileRow).toBeVisible();
	await expect(page.locator('[data-statusbar-item-id="ash.status.workspacePermissions"]')).toHaveCount(0);
	const fileTree = explorer.getByRole('tree');
	await fileTree.focus();
	await page.keyboard.press('Alt+F1');
	const accessibilityHelp = page.getByRole('dialog', { name: 'Accessibility Help' });
	await expect(accessibilityHelp).toBeVisible();
	await expect(accessibilityHelp.getByRole('textbox', { name: 'Accessibility Help' })).toHaveValue(/Use the arrow keys/);
	await page.keyboard.press('Escape');
	await expect(accessibilityHelp).toHaveCount(0);
	await expect(fileTree).toBeFocused();
	await page.keyboard.press('Alt+F2');
	const accessibleView = page.getByRole('dialog', { name: 'Accessible View' });
	await expect(accessibleView.getByRole('textbox', { name: 'Accessible View' })).toHaveValue(/hello %中\.txt/);
	await page.keyboard.press('Escape');
	await expect(fileTree).toBeFocused();
	await page.keyboard.press('Control+f');
	const explorerFind = page.getByRole('searchbox', { name: 'Find files in Explorer' });
	await expect(explorerFind).toBeFocused();
	await explorerFind.fill('hello');
	await expect(fileRow).toHaveClass(/find-match/);
	await explorerFind.press('Escape');
	await expect(fileTree).toBeFocused();
	await fileRow.click();
	await page.context().grantPermissions(['clipboard-read', 'clipboard-write']);
	await page.keyboard.press('F1');
	const commandQuery = page.locator('.ash-quick-pick').getByRole('combobox');
	await commandQuery.fill('Copy Relative Path');
	await expect(page.locator('.ash-quick-pick-row-label', { hasText: 'Copy Relative Path' })).toBeVisible();
	await page.keyboard.press('Enter');
	await expect.poll(() => page.evaluate(() => navigator.clipboard.readText())).toBe('hello %中.txt');
	const input = workbench.editors.groupAt(0).content.locator('.stanza-editor-input');
	await expect(input).toBeAttached();
	await input.focus();
	await input.press('Control+A');
	await input.type('second value');
	await expect(page.getByRole('tab', { name: 'Explorer, 1 unsaved file' })).toBeVisible();
	await input.press('Control+S');
	await expect(page.getByRole('tab', { name: 'Explorer', exact: true })).toBeVisible();
	await expect.poll(() => page.evaluate(async name => {
		const folder = await (await navigator.storage.getDirectory()).getDirectoryHandle(name);
		return (await (await folder.getFileHandle('hello %中.txt')).getFile()).text();
	}, folderName)).toBe('second value');
	await page.keyboard.press('Control+k');
	await page.keyboard.press('e');
	const openEditors = page.locator('[data-view-id="workbench.explorer.openEditorsView"]');
	await expect(openEditors).toBeVisible();
	const openEditorsTree = openEditors.getByRole('tree');
	await expect(openEditorsTree).toBeFocused();
	await expect(openEditorsTree.getByRole('treeitem', { name: /hello %中\.txt/ })).toBeVisible();
	await page.keyboard.press('Alt+F1');
	const openEditorsHelp = page.getByRole('dialog', { name: 'Accessibility Help' });
	await expect(openEditorsHelp.getByRole('textbox', { name: 'Accessibility Help' })).toHaveValue(/Press Delete to close/);
	await page.keyboard.press('Escape');
	await expect(openEditorsTree).toBeFocused();
	await page.keyboard.press('Alt+F2');
	await expect(page.getByRole('dialog', { name: 'Accessible View' }).getByRole('textbox', { name: 'Accessible View' })).toHaveValue(/hello %中\.txt/);
	await page.keyboard.press('Escape');
	await expect(openEditorsTree).toBeFocused();
	await page.keyboard.press('F1');
	await page.locator('.ash-quick-pick').getByRole('combobox').fill('Download File...');
	await expect(page.locator('.ash-quick-pick-row-label', { hasText: 'Download File...' })).toBeVisible();
	const [download] = await Promise.all([
		page.waitForEvent('download'),
		page.keyboard.press('Enter'),
	]);
	expect(download.suggestedFilename()).toBe('hello %中.txt');
	expect(await readFile(await download.path(), 'utf8')).toBe('second value');
	await page.keyboard.press('F1');
	await page.locator('.ash-quick-pick').getByRole('combobox').fill('New File...');
	await expect(page.locator('.ash-quick-pick-row-label', { hasText: 'New File...' })).toBeVisible();
	await page.keyboard.press('Enter');
	const newFileName = page.locator('.ash-quick-pick-input input[aria-label="New File Name"]');
	await newFileName.fill('created.txt');
	await newFileName.press('Enter');
	await expect(explorer.locator('.ash-tree-row').filter({ hasText: 'created.txt' })).toHaveCount(1);
	await expect.poll(() => page.evaluate(async name => {
		const folder = await (await navigator.storage.getDirectory()).getDirectoryHandle(name);
		return (await (await folder.getFileHandle('created.txt')).getFile()).text();
	}, folderName)).toBe('');
	const sourceFolderRow = explorer.locator('.ash-tree-row').filter({ hasText: 'src' });
	await sourceFolderRow.click();
	await page.keyboard.press('F1');
	await page.locator('.ash-quick-pick').getByRole('combobox').fill('New File...');
	await page.keyboard.press('Enter');
	const nestedFileName = page.locator('.ash-quick-pick-input input[aria-label="New File Name"]');
	await nestedFileName.fill('nested.txt');
	await nestedFileName.press('Enter');
	await expect(explorer.locator('.ash-tree-row').filter({ hasText: 'nested.txt' })).toHaveCount(1);
	await expect.poll(() => page.evaluate(async name => {
		const folder = await (await navigator.storage.getDirectory()).getDirectoryHandle(name);
		const source = await folder.getDirectoryHandle('src');
		return (await (await source.getFileHandle('nested.txt')).getFile()).text();
	}, folderName)).toBe('');
	const originalEditor = openEditorsTree.getByRole('treeitem', { name: /hello %中\.txt/ });
	await originalEditor.getByRole('button', { name: 'Close hello %中.txt' }).focus();
	await page.keyboard.press('Enter');
	await expect(originalEditor).toHaveCount(0);
	const nestedEditor = openEditorsTree.getByRole('treeitem', { name: /nested\.txt/ });
	await nestedEditor.click();
	await openEditorsTree.focus();
	await page.keyboard.press('Delete');
	await expect(nestedEditor).toHaveCount(0);
	await page.getByRole('button', { name: 'Application menu' }).click();
	await page.getByRole('menu').first().getByRole('menuitem', { name: 'File' }).click();
	await expect(page.getByRole('menu').last().getByRole('menuitem', { name: 'Open Folder...' })).toHaveCount(1);
});

test('browser nests related files when Explorer file nesting is enabled', async ({ target, workbench }) => {
	test.skip(target.kind !== 'browser' || target.workbenchMode !== 'code' || target.appServerMode !== 'disabled', 'This scenario requires the standalone Code browser');
	const page = workbench.page;
	await page.evaluate(async () => {
		const root = await navigator.storage.getDirectory();
		const folder = await root.getDirectoryHandle(`ash-nesting-${crypto.randomUUID()}`, { create: true });
		for (const name of ['app.ts', 'app.js', 'note.source', 'note.output']) {
			const file = await folder.getFileHandle(name, { create: true });
			const writer = await file.createWritable();
			await writer.write(name);
			await writer.close();
		}
		Object.defineProperty(window, 'showDirectoryPicker', { configurable: true, value: async () => folder });
	});
	await page.getByRole('button', { name: 'Application menu' }).click();
	await page.getByRole('menu').first().getByRole('menuitem', { name: 'File' }).click();
	await page.keyboard.press('Escape');
	await page.keyboard.press('Escape');
	const showSidebar = page.getByRole('button', { name: 'Show Primary Side Bar', exact: true });
	if (await showSidebar.isVisible()) await showSidebar.click();
	await page.getByRole('button', { name: 'Open Folder', exact: true }).click();
	const explorer = page.locator('.ash-explorer');
	const parent = explorer.locator('.ash-tree-row').filter({ hasText: 'app.ts' });
	const child = explorer.locator('.ash-tree-row').filter({ hasText: 'app.js' });
	await expect(parent).toHaveCount(1);
	if (await showSidebar.isVisible()) await showSidebar.click();
	await expect(parent).toBeVisible();
	await expect(child).toBeVisible();

	await page.getByRole('button', { name: 'Manage' }).click();
	await page.getByRole('menu').last().getByRole('menuitem', { name: 'Settings' }).click();
	const settings = page.locator('.ash-settings-editor');
	await expect(settings).toBeVisible();
	await settings.locator('[data-settings-category-id="editor"]').click();
	await settings.getByRole('searchbox', { name: 'Search settings' }).fill('explorer.fileNesting.enabled');
	const nestingToggle = settings.locator('[data-configuration-key="explorer.fileNesting.enabled"]');
	await expect(nestingToggle).toBeVisible();
	await nestingToggle.focus();
	await page.keyboard.press('Space');
	await expect(nestingToggle).toBeChecked();
	await expect(parent).toHaveAttribute('aria-expanded', 'true');
	await expect(child).toBeVisible();
	await settings.getByRole('searchbox', { name: 'Search settings' }).fill('explorer.fileNesting.patterns');
	const patterns = settings.locator('[data-configuration-key="explorer.fileNesting.patterns"]');
	await expect(patterns).toBeVisible();
	await patterns.getByRole('button', { name: 'Add pattern' }).click();
	await patterns.locator('[data-pattern-part="key"]').last().fill('*.source');
	await patterns.locator('[data-pattern-part="value"]').last().fill('${capture}.output');
	await patterns.locator('[data-pattern-part="value"]').last().press('Tab');
	const customParent = explorer.locator('.ash-tree-row').filter({ hasText: 'note.source' });
	const customChild = explorer.locator('.ash-tree-row').filter({ hasText: 'note.output' });
	await expect(customParent).toHaveAttribute('aria-expanded', 'true');
	await expect(customChild).toBeVisible();
	await page.locator('.ash-modal-editor-close').click();
	await parent.locator('.ash-tree-twistie').click();
	await expect(child).toHaveCount(0);
	await parent.locator('.ash-tree-twistie').click();
	await expect(child).toBeVisible();
	await customParent.locator('.ash-tree-twistie').click();
	await expect(customChild).toHaveCount(0);
	await customParent.locator('.ash-tree-twistie').click();
	await expect(customChild).toBeVisible();
	await child.click();
	await expect(workbench.editors.groupAt(0).content.locator('.stanza-editor-input')).toBeAttached();
});
