import { emptyEditorServiceState } from '../../../../test/common/testEditorService.js';
import '../../../../../editor/test/browser/testEditorDom.js';
import assert from 'node:assert/strict';
import { suite, test } from 'mocha';
import { DeferredPromise } from '../../../../../base/common/async.js';
import { CancellationToken, CancellationTokenSource } from '../../../../../base/common/cancellation.js';
import { DisposableStore } from '../../../../../base/common/lifecycle.js';
import { Event } from '../../../../../base/common/event.js';
import { Range } from '../../../../../editor/common/core/range.js';
import type { LanguageDocumentSymbol } from '../../../../../editor/common/languages.js';
import { TextModel } from '../../../../../editor/common/model/textModel.js';
import { ILanguageFeaturesService } from '../../../../../editor/common/services/languageFeatures.js';
import { LanguageFeaturesService } from '../../../../../editor/common/services/languageFeaturesService.js';
import type { IEditorPane } from '../../../../common/editor.js';
import { IEditorService, type EditorOpenOptions, type EditorOpenTarget } from '../../../../services/editor/common/editorService.js';
import { IOutlineService, OutlineTarget } from '../../../../services/outline/browser/outline.js';
import { OutlineService } from '../../../../services/outline/browser/outlineService.js';
import { createTestCodeEditor } from '../../../../../editor/test/browser/testCodeEditor.js';
import { InstantiationService } from '../../../../../platform/instantiation/common/instantiationService.js';
import { DocumentSymbolsOutlineCreator } from '../../browser/outline/documentSymbolsOutline.js';

suite('DocumentSymbolsOutline', () => {
	test('uses real editor symbols, tracks nested cursor positions, and navigates selection ranges', async () => {
		using lifetime = new DisposableStore();
		const services = lifetime.add(new InstantiationService());
		const features = lifetime.add(new LanguageFeaturesService());
		const outlines = lifetime.add(new OutlineService());
		services.registerInstance(ILanguageFeaturesService, features);
		services.registerInstance(IOutlineService, outlines);
		const opened: { options: EditorOpenOptions | undefined; target: EditorOpenTarget | undefined; }[] = [];
		services.registerInstance(IEditorService, { ...emptyEditorServiceState, onDidActiveEditorChange: Event.None, onDidVisibleEditorsChange: Event.None, activeEditor: undefined, visibleEditors: [], focusActiveEditor: () => { }, openEditor: async (_input, options, target) => { opened.push({ options, target }); } });
		const model = lifetime.add(new TextModel('function outer() {\n  inner();\n}', { languageId: 'typescript' }));
		const editor = lifetime.add(createTestCodeEditor({ container: document.createElement('div'), model, languageFeaturesService: features }));
		const pane: IEditorPane = { id: 'test', getId: () => 'test', getTitle: () => 'Test', getControl: () => editor, onDidFocus: Event.None, onDidBlur: Event.None, focus: () => editor.focus(), hasFocus: () => editor.hasTextFocus(), setInput: async () => { }, clearInput: () => { }, layout: () => { }, setVisible: () => { }, isVisible: () => true, dispose: () => { }, [Symbol.dispose]: () => { } };
		lifetime.add(features.documentSymbolProvider.register('*', { provideDocumentSymbols: () => [{ name: 'outer', kind: 'function', range: new Range(1, 1, 3, 2), selectionRange: new Range(1, 10, 1, 15), children: [{ name: 'inner', kind: 'function', range: new Range(2, 3, 2, 11), selectionRange: new Range(2, 3, 2, 8) }] }] }));
		lifetime.add(services.createInstance(DocumentSymbolsOutlineCreator));
		const outline = lifetime.add((await outlines.createOutline(pane, OutlineTarget.OutlinePane, CancellationToken.None))!);
		assert.equal(outline.isEmpty, false);
		const roots = [...outline.config.treeDataSource.getChildren(outline)];
		assert.deepEqual(roots.map(entry => entry.symbol.name), ['outer']);
		editor.setPosition({ lineNumber: 2, column: 5 });
		assert.equal(outline.activeElement?.symbol.name, 'inner');
		await outline.reveal(outline.activeElement!, { pinned: true }, true, true);
		assert.deepEqual(opened.map(call => ({ target: call.target, pinned: call.options?.pinned, selection: call.options?.selection })), [{ target: 'sideGroup', pinned: true, selection: new Range(2, 3, 2, 8) }]);
		model.setValue('replaced');
		await outline.reveal(roots[0], {}, false, true);
		assert.equal(opened.length, 1, 'stale symbol ranges cannot navigate a newer model version');
	});

	test('cancellation aborts providers and finishes without waiting for late symbols', async () => {
		using lifetime = new DisposableStore();
		const services = lifetime.add(new InstantiationService());
		const features = lifetime.add(new LanguageFeaturesService());
		const outlines = lifetime.add(new OutlineService());
		services.registerInstance(ILanguageFeaturesService, features);
		services.registerInstance(IOutlineService, outlines);
		services.registerInstance(IEditorService, { ...emptyEditorServiceState, onDidActiveEditorChange: Event.None, onDidVisibleEditorsChange: Event.None, activeEditor: undefined, visibleEditors: [], focusActiveEditor: () => { }, openEditor: async () => { } });
		const model = lifetime.add(new TextModel('pending'));
		const editor = lifetime.add(createTestCodeEditor({ container: document.createElement('div'), model, languageFeaturesService: features }));
		const pane: IEditorPane = { id: 'test', getId: () => 'test', getTitle: () => 'Test', getControl: () => editor, onDidFocus: Event.None, onDidBlur: Event.None, focus: () => { }, hasFocus: () => false, setInput: async () => { }, clearInput: () => { }, layout: () => { }, setVisible: () => { }, isVisible: () => true, dispose: () => { }, [Symbol.dispose]: () => { } };
		const pending = new DeferredPromise<readonly LanguageDocumentSymbol[]>();
		let signal: AbortSignal | undefined;
		lifetime.add(features.documentSymbolProvider.register('*', { provideDocumentSymbols: (_request, cancellation) => { signal = cancellation; return pending.p; } }));
		lifetime.add(services.createInstance(DocumentSymbolsOutlineCreator));
		using token = new CancellationTokenSource();
		const result = outlines.createOutline(pane, OutlineTarget.OutlinePane, token.token);
		token.cancel();
		await assert.rejects(result, /cancelled/);
		assert.equal(signal?.aborted, true);
		pending.complete([]);
	});
});
