// Generated by `ash-app-server-protocol generate_protocol`. Do not edit.
import type { WebListenInfo } from './WebListenInfo.js';
import type { WebSessionInfo } from './WebSessionInfo.js';

export function decodeWebListenInfo(value: unknown): WebListenInfo {
	const info = record(value, ['endpoint', 'ticket', 'pid']);
	if (typeof info.endpoint !== 'string' || typeof info.ticket !== 'string' || !/^[a-f0-9]{64}$/.test(info.ticket) || typeof info.pid !== 'number' || !Number.isSafeInteger(info.pid) || info.pid <= 0) { throw new Error('Invalid Web launch record'); }
	const endpoint = new URL(info.endpoint);
	if (endpoint.protocol !== 'http:' || endpoint.hostname !== '127.0.0.1' || !endpoint.port || endpoint.pathname !== '/' || endpoint.search || endpoint.hash || endpoint.username || endpoint.password) { throw new Error('Expected a loopback HTTP endpoint'); }
	return { endpoint: info.endpoint, ticket: info.ticket, pid: info.pid };
}

export function decodeWebSessionInfo(value: unknown): WebSessionInfo {
	const info = record(value, ['token', 'workspaceId', 'workspaceRoot']);
	if (typeof info.token !== 'string' || !/^[a-f0-9]{64}$/.test(info.token) || typeof info.workspaceId !== 'string' || !info.workspaceId || typeof info.workspaceRoot !== 'string' || !info.workspaceRoot) { throw new Error('Invalid Web session record'); }
	return { token: info.token, workspaceId: info.workspaceId, workspaceRoot: info.workspaceRoot };
}

function record(value: unknown, keys: readonly string[]): Record<string, unknown> {
	if (!value || typeof value !== 'object' || Array.isArray(value) || Object.keys(value).length !== keys.length || keys.some(key => !Object.hasOwn(value, key))) { throw new Error('Invalid Web protocol record'); }
	return value as Record<string, unknown>;
}
